### ISSUE TITLE
SSL Error: OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_record', 'decryption failed or bad record mac')] 

### ISSUE THREAD

**Issue by ppsarkar** [snowflakedb/snowflake-connector-python#101]
$ pip freeze
asn1crypto==0.24.0
azure-common==1.1.12
azure-nspkg==2.0.0
azure-storage==0.36.0
boto3==1.7.48
botocore==1.10.63
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
cryptography==2.2.2
docutils==0.14
future==0.16.0
idna==2.7
ijson==2.3
jmespath==0.9.3
numpy==1.14.5
pandas==0.23.1
pip-autoremove==0.9.1
psutil==5.4.6
pyasn1==0.4.3
pyasn1-modules==0.2.2
pycparser==2.18
pycryptodome==3.6.3
PyJWT==1.6.4
pyOpenSSL==17.5.0
python-dateutil==2.7.3
pytz==2018.5
PyYAML==3.12
requests==2.19.1
s3transfer==0.1.13
six==1.11.0
snowflake-connector-python==1.6.5
teradata==15.10.0.10
urllib3==1.23
virtualenv==16.0.0

[DEBUG:snowflake.connector.connection:678]--:--sql=[USE DATABASE AIDM_EDW_DEV], sequence_id=[2], is_file_transfer=[None]
[DEBUG:snowflake.connector.network:649]--:--socket timeout: 60
[DEBUG:snowflake.connector.network:790]--:--Active requests sessions: 1, idle: 0
[DEBUG:snowflake.connector.network:530]--:--remaining request timeout: None, retry cnt: 1
[DEBUG:snowflake.connector.network:649]--:--socket timeout: 60
[DEBUG:snowflake.connector.network:802]--:--Active requests sessions: 0, idle: 1
[DEBUG:snowflake.connector.network:802]--:--Active requests sessions: 0, idle: 1
[INFO:snowflake.connector.telemetry:106]--:--Failed to upload metrics to telemetry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/ssl_wrap_socket.py", line 220, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1715, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1521, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/telemetry.py", line 96, in send_batch
    method='post', client=None)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 282, in request
    timeout=self._connection.network_timeout)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 449, in _post_request
    no_retry=no_retry, socket_timeout=socket_timeout)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 516, in fetch
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 579, in _request_exec_wrapper
    raise e
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 542, in _request_exec_wrapper
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 770, in _request_exec
    raise err
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 675, in _request_exec
    auth=SnowflakeAuth(token),
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/ssl_wrap_socket.py", line 236, in recv_into
    return self.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/ssl_wrap_socket.py", line 220, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1715, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1546, in _raise_ssl_error
    _raise_current_error()
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_record', 'decryption failed or bad record mac')]
[DEBUG:snowflake.connector.network:580]--:--Ignored error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/ssl_wrap_socket.py", line 220, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1715, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1521, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/ssl_wrap_socket.py", line 220, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1715, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1521, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 542, in _request_exec_wrapper
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 770, in _request_exec
    raise err
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 675, in _request_exec
    auth=SnowflakeAuth(token),
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/ssl_wrap_socket.py", line 236, in recv_into
    return self.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/ssl_wrap_socket.py", line 236, in recv_into
    return self.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/ssl_wrap_socket.py", line 220, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1715, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1546, in _raise_ssl_error
    _raise_current_error()
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_record', 'decryption failed or bad record mac')]
[INFO:snowflake.connector.telemetry:106]--:--Failed to upload metrics to telemetry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/ssl_wrap_socket.py", line 220, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1715, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1521, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/telemetry.py", line 96, in send_batch
    method='post', client=None)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 282, in request
    timeout=self._connection.network_timeout)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 449, in _post_request
    no_retry=no_retry, socket_timeout=socket_timeout)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 516, in fetch
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 579, in _request_exec_wrapper
    raise e
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 542, in _request_exec_wrapper
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 770, in _request_exec
    raise err
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/network.py", line 675, in _request_exec
    auth=SnowflakeAuth(token),
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/ssl_wrap_socket.py", line 236, in recv_into
    return self.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/ssl_wrap_socket.py", line 220, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1715, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1546, in _raise_ssl_error
    _raise_current_error()
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_record', 'decryption failed or bad record mac')]

**Comment by smtakeda** [comment]
Is this reproducible?

**Comment by smtakeda** [comment]
have not seen this error or got report. Closing for now.
