### ISSUE TITLE
SNOW-615583: Error when using connector in airflow snowflake hook: module 'snowflake' has no attribute 'connector' 

### ISSUE THREAD

**Issue by dollschasingmen** [snowflakedb/snowflake-connector-python#1167]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   3.7.x

2. What operating system and processor architecture are you using?

  Linux-5.10.25-linuxkit-x86_64-with-debian-10.12

3. What are the component versions in the environment (`pip freeze`)?

aiohttp==3.8.0
aiosignal==1.2.0
alembic==1.7.4
amqp==5.0.6
anyio==3.3.4
apache-airflow==2.2.2
apache-airflow-providers-amazon==2.4.0
apache-airflow-providers-apache-hive==2.0.3
apache-airflow-providers-celery==2.1.0
apache-airflow-providers-databricks==2.0.2
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-http==2.0.1
apache-airflow-providers-imap==2.0.1
apache-airflow-providers-jdbc==2.0.1
apache-airflow-providers-mysql==2.1.1
apache-airflow-providers-postgres==2.3.0
apache-airflow-providers-slack==4.1.0
**apache-airflow-providers-snowflake==2.3.0**
apache-airflow-providers-sqlite==2.0.1
apache-airflow-providers-ssh==2.3.0
apispec==3.3.2
argcomplete==1.12.3
asn1crypto==1.4.0
async-timeout==4.0.2
asynctest==0.13.0
attrs==20.3.0
Babel==2.9.1
bcrypt==3.2.0
beautifulsoup4==4.7.1
billiard==3.6.4.0
blinker==1.4
boto==2.49.0
boto3==1.18.65
botocore==1.21.65
cached-property==1.5.2
cattrs==1.5.0
celery==5.2.0
certifi==2020.12.5
cffi==1.15.0
charset-normalizer==2.0.7
click==8.0.3
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
clickclick==20.10.2
colorama==0.4.4
colorlog==4.8.0
commonmark==0.9.1
confluent-kafka==1.9.0
croniter==1.0.15
cryptography==3.4.8
decorator==5.1.0
defusedxml==0.7.1
Deprecated==1.2.13
dill==0.3.1.1
dnspython==2.1.0
docutils==0.16
email-validator==1.1.3
Flask==1.1.2
Flask-AppBuilder==3.3.4
Flask-Babel==2.0.0
Flask-Caching==1.10.1
Flask-JWT-Extended==3.25.1
Flask-Login==0.4.1
Flask-OpenID==1.3.0
Flask-SQLAlchemy==2.5.1
Flask-WTF==0.14.3
flower==1.0.0
frozenlist==1.3.0
future==0.18.2
graphviz==0.18
gunicorn==20.1.0
h11==0.12.0
hmsclient==0.1.1
httpcore==0.13.7
httpx==0.19.0
humanize==3.12.0
idna==3.3
importlib-metadata==4.8.1
importlib-resources==5.4.0
inflection==0.5.1
iso8601==1.0.0
isodate==0.6.0
itsdangerous==1.1.0
JayDeBeApi==1.2.3
Jinja2==2.11.3
jmespath==0.10.0
JPype1==1.3.0
jsonpath-ng==1.5.3
jsonschema==3.2.0
kombu==5.2.1
lazy-object-proxy==1.4.3
lockfile==0.12.2
lxml==4.9.0
Mako==1.1.5
Markdown==3.3.4
MarkupSafe==1.1.1
marshmallow==3.14.0
marshmallow-enum==1.5.1
marshmallow-oneofschema==3.0.1
marshmallow-sqlalchemy==0.26.1
multidict==6.0.2
mysql-connector-python==8.0.27
mysqlclient==2.0.3
ndg-httpsclient==0.5.1
numpy==1.20.3
openapi-schema-validator==0.1.5
openapi-spec-validator==0.3.1
oscrypto==1.2.1
packaging==21.0
pandas==1.3.4
paramiko==2.8.0
pendulum==2.1.2
ply==3.11
prison==0.2.1
prometheus-client==0.12.0
prompt-toolkit==3.0.22
protobuf==3.17.3
psutil==5.8.0
psycopg2-binary==2.9.1
pure-sasl==0.6.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pycryptodomex==3.11.0
Pygments==2.10.0
PyHive==0.6.4
PyJWT==1.7.1
PyNaCl==1.4.0
pyOpenSSL==20.0.1
pyparsing==2.4.7
pyrsistent==0.18.0
pysftp==0.2.9
python-daemon==2.3.0
python-dateutil==2.8.2
python-nvd3==0.15.0
python-slugify==4.0.1
python3-openid==3.2.0
pytz==2021.3
pytzdata==2020.1
PyYAML==5.4.1
redis==4.3.3
redshift-connector==2.0.907
requests==2.26.0
rfc3986==1.5.0
rich==10.13.0
s3transfer==0.5.0
sasl==0.3.1
scramp==1.4.1
setproctitle==1.2.2
six==1.16.0
slack-sdk==3.11.2
sniffio==1.2.0
**snowflake-connector-python==2.7.0**
**snowflake-sqlalchemy==1.2.4**
soupsieve==2.3
SQLAlchemy==1.3.24
SQLAlchemy-JSONField==1.0.0
sqlalchemy-redshift==0.8.9
SQLAlchemy-Utils==0.37.9
sshtunnel==0.4.0
swagger-ui-bundle==0.0.9
tabulate==0.8.9
tenacity==8.0.1
termcolor==1.1.0
text-unidecode==1.3
thrift==0.15.0
thrift-sasl==0.4.3
tornado==6.1
typing-extensions==3.10.0.2
unicodecsv==0.14.1
urllib3==1.26.7
vine==5.0.0
watchtower==1.0.6
wcwidth==0.2.5
Werkzeug==1.0.1
wrapt==1.14.1
WTForms==2.3.3
yarl==1.7.2
zipp==3.6.0

4. What did you do?

Try attempt to run sql in snowflake using the snowflake hook

5. What did you expect to see?

I expected to see the sql run properly.

6. Can you set logging to DEBUG and collect the logs?

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/airflow/plugins/snowflake_ingest_plugin/operators/snowflake_sql_operator.py", line 108, in execute
    parameters=full_parameters
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 271, in run
    with self.get_conn() as conn:
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 223, in get_conn
    conn = connector.connect(**conn_config)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/snowflake/connector/__init__.py", line 50, in Connect
    return SnowflakeConnection(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/snowflake/connector/connection.py", line 286, in __init__
    self.connect(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/snowflake/connector/connection.py", line 503, in connect
    self.__config(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/snowflake/connector/connection.py", line 825, in __config
    self._paramstyle = snowflake.connector.paramstyle
AttributeError: module 'snowflake' has no attribute 'connector'

---------------------------------

I saw a previous similar issue that was closed (https://github.com/snowflakedb/snowflake-connector-python/issues/334) but I didn't see any resolution to it.

**Comment by lroberts7** [comment]
I just ran into this issue myself. I downgraded from `snowflake-connector-python-2.7.11` to `snowflake-connector-python-2.7.6` and it resolved the problem for me.
