### ISSUE TITLE
SNOW-648645: Snowflake-connector-python 2.7.0 snowflake.connector.errors.OperationalError: 253003

### ISSUE THREAD

**Issue by pkrish123** [snowflakedb/snowflake-connector-python#1230]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?
```
Python 3.8.13 (default, Aug  2 2022, 11:48:37) 
[GCC 10.2.1 20210110]
```

2. What operating system and processor architecture are you using?
```
Linux-5.10.104-linuxkit-x86_64-with-glibc2.2.5
```

4. What are the component versions in the environment (`pip freeze`)?
```
alembic==1.8.1
amqp==5.1.1
anyio==3.6.1
apache-airflow==2.3.0
apache-airflow-providers-amazon==3.3.0
apache-airflow-providers-celery==3.0.0
apache-airflow-providers-common-sql==1.0.0
apache-airflow-providers-ftp==3.1.0
apache-airflow-providers-google==6.7.0
apache-airflow-providers-http==4.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-jdbc==3.2.0
apache-airflow-providers-mysql==3.2.0
apache-airflow-providers-postgres==5.2.0
apache-airflow-providers-redis==3.0.0
apache-airflow-providers-slack==5.1.0
apache-airflow-providers-snowflake==2.3.0
apache-airflow-providers-sqlite==3.2.0
apispec==3.3.2
appdirs==1.4.4
argcomplete==1.12.3
asn1crypto==1.5.1
astroid==2.5
attrs==20.3.0
azure-common==1.1.28
azure-core==1.25.0
azure-storage-blob==12.13.1
Babel==2.10.3
beautifulsoup4==4.11.1
billiard==3.6.4.0
black==20.8b1
blinker==1.4
boto3==1.15.0
botocore==1.18.18
cachelib==0.9.0
cachetools==5.2.0
cattrs==1.5.0
celery==5.2.7
certifi==2022.6.15
cffi==1.15.1
chardet==4.0.0
charset-normalizer==2.0.12
click==8.1.3
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
clickclick==20.10.2
colorama==0.4.5
colorlog==4.8.0
commonmark==0.9.1
connexion==2.14.0
cron-descriptor==1.2.31
croniter==1.3.5
cryptography==3.4.8
decorator==5.1.1
defusedxml==0.7.1
Deprecated==1.2.13
dill==0.3.5.1
distlib==0.3.5
dnspython==2.2.1
docopt==0.6.2
docutils==0.19
email-validator==1.2.1
et-xmlfile==1.1.0
filelock==3.8.0
Flask==1.1.2
Flask-AppBuilder==3.4.5
Flask-Babel==2.0.0
Flask-Caching==1.11.1
Flask-JWT-Extended==3.25.1
Flask-Login==0.4.1
Flask-OpenID==1.3.0
Flask-Session==0.4.0
Flask-SQLAlchemy==2.5.1
Flask-WTF==0.14.3
flower==1.2.0
future==0.18.2
google-ads==14.0.0
google-api-core==2.8.2
google-api-python-client==1.12.11
google-auth==2.10.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.5.2
google-cloud-aiplatform==1.16.1
google-cloud-appengine-logging==1.1.3
google-cloud-audit-log==0.2.4
google-cloud-automl==2.8.0
google-cloud-bigquery==2.30.1
google-cloud-bigquery-datatransfer==3.7.0
google-cloud-bigquery-storage==2.14.1
google-cloud-bigtable==1.7.2
google-cloud-build==3.9.0
google-cloud-container==1.0.3
google-cloud-core==2.3.2
google-cloud-datacatalog==3.9.0
google-cloud-dataplex==1.1.0
google-cloud-dataproc==5.0.0
google-cloud-dataproc-metastore==1.6.0
google-cloud-dlp==1.0.2
google-cloud-kms==2.12.0
google-cloud-language==1.3.2
google-cloud-logging==3.2.1
google-cloud-memcache==1.4.1
google-cloud-monitoring==2.11.0
google-cloud-orchestration-airflow==1.4.1
google-cloud-os-login==2.7.1
google-cloud-pubsub==2.13.5
google-cloud-redis==2.9.0
google-cloud-resource-manager==1.6.0
google-cloud-secret-manager==1.0.2
google-cloud-spanner==1.19.3
google-cloud-speech==1.3.4
google-cloud-storage==1.44.0
google-cloud-tasks==2.10.1
google-cloud-texttospeech==1.0.3
google-cloud-translate==1.7.2
google-cloud-videointelligence==1.16.3
google-cloud-vision==1.0.2
google-cloud-workflows==1.7.1
google-crc32c==1.3.0
google-resumable-media==2.3.3
googleapis-common-protos==1.56.4
graphviz==0.20.1
greenlet==1.1.2
grpc-google-iam-v1==0.12.4
grpcio==1.47.0
grpcio-gcp==0.2.2
grpcio-status==1.47.0
gunicorn==20.1.0
h11==0.12.0
httpcore==0.15.0
httplib2==0.20.4
httpx==0.23.0
humanize==4.3.0
idna==2.9
importlib-metadata==4.12.0
importlib-resources==5.9.0
inflection==0.5.1
iniconfig==1.1.1
isodate==0.6.1
isort==5.10.1
itsdangerous==1.1.0
JayDeBeApi==1.2.3
jeepney==0.8.0
Jinja2==3.0.3
jmespath==0.10.0
JPype1==1.4.0
json-merge-patch==0.2
jsonpath-ng==1.5.3
jsonschema==4.12.1
keyring==22.0.1
kombu==5.2.4
lazy-object-proxy==1.7.1
lockfile==0.12.2
looker-sdk==22.10.0
lxml==4.9.1
Mako==1.2.1
Markdown==3.4.1
MarkupSafe==2.0.1
marshmallow==3.17.0
marshmallow-enum==1.5.1
marshmallow-oneofschema==3.0.1
marshmallow-sqlalchemy==0.26.1
mccabe==0.6.1
-e git+ssh://git@github.com/foolwealth/dpt-airflow-container.git@3dbfdd6e8f324575adfaa7e4a9c28e4050f8b415#egg=mm_airflow
msrest==0.7.1
mypy-boto3-rds==1.24.54
mypy-boto3-redshift-data==1.24.36.post1
mypy-extensions==0.4.3
mysql-connector-python==8.0.30
mysqlclient==2.0.1
nox==2020.12.31
num2words==0.5.10
numpy==1.23.2
oauthlib==3.2.0
openpyxl==3.0.10
oscrypto==1.3.0
packaging==21.3
pandas==1.2.5
pandas-gbq==0.13.2
pathspec==0.9.0
pendulum==2.1.2
pipdeptree==2.2.1
pkgutil_resolve_name==1.3.10
platformdirs==2.5.2
pluggy==1.0.0
ply==3.11
prison==0.2.1
prometheus-client==0.14.1
prompt-toolkit==3.0.30
proto-plus==1.18.1
protobuf==3.19.0
psutil==5.9.1
psycopg2==2.9.3
psycopg2-binary==2.8.6
py==1.11.0
pyarrow==3.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pycryptodomex==3.15.0
pycurl==7.45.1
pydata-google-auth==1.4.0
Pygments==2.13.0
PyJWT==1.7.1
pylint==2.7.0
pymssql==2.1.5
PyMySQL==1.0.2
pyOpenSSL==20.0.1
pyparsing==3.0.9
pyrsistent==0.18.1
pytest==6.2.5
python-daemon==2.3.1
python-dateutil==2.8.2
python-dotenv==0.20.0
python-nvd3==0.15.0
python-slugify==6.1.2
python3-openid==3.2.0
pytz==2021.3
pytzdata==2020.1
PyYAML==5.4.1
redis==3.5.3
redshift-connector==2.0.908
regex==2022.6.2
requests==2.26.0
requests-oauthlib==1.3.1
requests-toolbelt==0.9.1
rfc3986==1.5.0
rich==12.5.1
rsa==4.9
s3transfer==0.3.7
scramp==1.4.1
SecretStorage==3.3.3
sentry-sdk==1.9.0
setproctitle==1.3.2
six==1.16.0
slack-sdk==3.18.1
sniffio==1.2.0
snowflake-connector-python==2.4.6
snowflake-sqlalchemy==1.3.1
soupsieve==2.3.2.post1
SQLAlchemy==1.4.9
sqlalchemy-bigquery==1.4.4
SQLAlchemy-JSONField==1.0.0
sqlalchemy-redshift==0.8.11
SQLAlchemy-Utils==0.38.3
swagger-ui-bundle==0.0.9
tabulate==0.8.10
tenacity==8.0.1
termcolor==1.1.0
text-unidecode==1.3
toml==0.10.2
tornado==6.2
typed-ast==1.5.4
typing_extensions==4.3.0
unicodecsv==0.14.1
uritemplate==3.0.1
urllib3==1.25.11
vine==5.0.0
virtualenv==20.16.3
watchtower==2.0.1
wcwidth==0.2.5
Werkzeug==1.0.1
wrapt==1.12.1
WTForms==2.3.3
xlrd==2.0.1
zipp==3.8.1
```

5. What did you do?
Trying to write a dataframe to a Snowflake table using write_pandas from an Airflow DAG.

6. What did you expect to see?
I expect for the write to successfully complete, but instead I see:
```
Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/decryption/decryption.py", line 206, in decrypt_field_and_save
    write_pandas(conn, pandas_df, table, db, schema)
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/pandas_tools.py", line 173, in write_pandas
    cursor.execute(upload_sql, _is_internal=True)
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 747, in execute
    data = sf_file_transfer_agent.result()
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/file_transfer_agent.py", line 716, in result
    Error.errorhandler_wrapper(
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 268, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 323, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 202, in default_errorhandler
    raise error_class(
snowflake.connector.errors.OperationalError: 253003: 253003: HTTPError('400 Client Error: Bad Request for url: https://sfc-va2-ds1-15-customer-stage.s3-accelerate.amazonaws.com/xxbo-s-v2su3968/stages/2d59c6f1-2cb5-4edf-845b-62c0a64cc449/file0.txt')
```

7. Can you set logging to DEBUG and collect the logs?

```
  2022-08-18 18:20:37,457] {connectionpool.py:452} DEBUG - https://sfc-va2-ds1-15-customer-stage.s3-accelerate.amazonaws.com:443 "HEAD /xxbo-s-v2su3968/stages/8c37f9de-ab16-49aa-85b3-ba911a694e00/file0.txt HTTP/1.1" 400 0
2022-08-18 18:20:37,458 - ThreadPoolExecutor-4_0 network.py:1111 - _use_requests_session() - DEBUG - Session status for SessionPool 'b'sfc-va2-ds1-15-customer-stage.s3-accelerate.amazonaws.com'', SessionPool 0/1 active sessions
[2022-08-18 18:20:37,458] {network.py:1111} DEBUG - Session status for SessionPool 'b'sfc-va2-ds1-15-customer-stage.s3-accelerate.amazonaws.com'', SessionPool 0/1 active sessions
2022-08-18 18:20:37,458 - ThreadPoolExecutor-4_0 file_transfer_agent.py:577 - function_and_callback_wrapper() - ERROR - An exception was raised in <bound method SnowflakeStorageClient.prepare_upload of <snowflake.connector.s3_storage_client.SnowflakeS3RestClient object at 0x7fe8529e3790>>
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.8/site-packages/snowflake/connector/file_transfer_agent.py", line 574, in function_and_callback_wrapper
    work(*args, **kwargs),
  File "/usr/local/airflow/.local/lib/python3.8/site-packages/snowflake/connector/storage_client.py", line 212, in prepare_upload
    self.preprocess()
  File "/usr/local/airflow/.local/lib/python3.8/site-packages/snowflake/connector/storage_client.py", line 190, in preprocess
    self.get_file_header(meta.dst_file_name)  # Check if file exists on remote
  File "/usr/local/airflow/.local/lib/python3.8/site-packages/snowflake/connector/s3_storage_client.py", line 387, in get_file_header
    response.raise_for_status()
  File "/usr/local/airflow/.local/lib/python3.8/site-packages/snowflake/connector/vendored/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
snowflake.connector.vendored.requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://sfc-va2-ds1-15-customer-stage.s3-accelerate.amazonaws.com/xxbo-s-v2su3968/stages/8c37f9de-ab16-49aa-85b3-ba911a694e00/file0.txt
```

**Comment by pkrish123** [comment]
Workaround for this is to downgrade snowflake-connector-python to version 2.4.6
