### ISSUE TITLE
SNOW-684591: Deadlock During OCSP Validation

### ISSUE THREAD

**Issue by daychr** [snowflakedb/snowflake-connector-python#1299]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

3.9.14

2. What operating system and processor architecture are you using?

Linux-5.4.0-1072-azure-x86_64-with-glibc2.31

3. What are the component versions in the environment (`pip freeze`)?

   apache-airflow==2.4.1+astro.1
   apache-airflow-providers-snowflake==2.5.0
   snowflake-connector-python==2.7.1
   snowflake-sqlalchemy==1.4.2

4. What did you do?

   I am using Airflow to run relatively simple Snowflake queries using a SnowflakeHook. These queries usually finish in <30 seconds, but approximately 5-10% of the time the task executing them deadlocks and runs forever until being killed manually by a user or by Airflow when the DAG timeout is reached. When the task is terminated, I see that execution hung while the Snowflake connector was performing OCSP validation. Setting "insecure_mode=True" on the Snowflake connection resolves the problem but this solution is not ideal. I've tried upgrading both snowflake-connector-python and apache-airflow-providers-snowflake to their latest versions (2.8.0 and 3.3.0) with no change in behavior. 

5. What did you expect to see?

   OCSP validation and the connection should succeed or fail in a timely and clear manner.

6. Can you set logging to DEBUG and collect the logs?

```
[2022-10-22T21:50:30.888+0000] {network.py:1117} DEBUG - Session status for SessionPool 'my_snowflake_instance.snowflakecomputing.com', SessionPool 1/1 active sessions
[2022-10-22T21:50:30.888+0000] {network.py:823} DEBUG - remaining request timeout: 5, retry cnt: 1
[2022-10-22T21:50:30.993+0000] {network.py:804} DEBUG - Request guid: 02c1e2f9-6e31-4556-a41a-9e083a582e8e
[2022-10-22T21:50:30.993+0000] {network.py:973} DEBUG - socket timeout: 60
[2022-10-22T21:50:31.086+0000] {connectionpool.py:971} DEBUG - Starting new HTTPS connection (1): my_snowflake_instance.snowflakecomputing.com:443
[2022-10-22T21:50:31.229+0000] {connectionpool.py:452} DEBUG - https://my_snowflake_instance.snowflakecomputing.com:443 "POST /telemetry/send?request_guid=02c1e2f9-6e31-4556-a41a-9e083a582e8e HTTP/1.1" 200 86
[2022-10-22T21:50:31.230+0000] {network.py:1002} DEBUG - SUCCESS
[2022-10-22T21:50:31.230+0000] {network.py:1122} DEBUG - Session status for SessionPool 'my_snowflake_instance.snowflakecomputing.com', SessionPool 0/1 active sessions
[2022-10-22T21:50:31.230+0000] {network.py:711} DEBUG - ret[code] = None, after post request
[2022-10-22T21:50:31.230+0000] {telemetry.py:133} DEBUG - Successfully uploading metrics to telemetry.
[2022-10-22T21:50:31.231+0000] {connection.py:512} INFO - No async queries seem to be running, deleting session
[2022-10-22T21:50:31.231+0000] {network.py:1117} DEBUG - Session status for SessionPool 'my_snowflake_instance.snowflakecomputing.com', SessionPool 1/1 active sessions
[2022-10-22T21:50:31.231+0000] {network.py:823} DEBUG - remaining request timeout: 5, retry cnt: 1
[2022-10-22T21:50:31.231+0000] {network.py:804} DEBUG - Request guid: d7a94e0d-f2d5-491b-a66f-ebafdd03e6e6
[2022-10-22T21:50:31.232+0000] {network.py:973} DEBUG - socket timeout: 60
[2022-10-22T21:50:31.540+0000] {ssl_wrap_socket.py:83} DEBUG - OCSP Mode: FAIL_OPEN, OCSP response cache file name: None
[2022-10-22T21:50:31.540+0000] {ocsp_snowflake.py:506} DEBUG - ocsp_response_cache_uri: file:///home/astro/.cache/snowflake/ocsp_response_cache.json
[2022-10-22T21:50:31.541+0000] {ocsp_snowflake.py:507} DEBUG - OCSP_VALIDATION_CACHE size: 188
[2022-10-22T21:50:31.541+0000] {ocsp_snowflake.py:289} DEBUG - OCSP response cache server is enabled: http://ocsp.snowflakecomputing.com/ocsp_response_cache.json
[2022-10-22T21:50:31.541+0000] {ocsp_snowflake.py:325} DEBUG - OCSP dynamic cache server RETRY URL: None
[2022-10-22T21:50:31.603+0000] {connectionpool.py:452} DEBUG - https://my_snowflake_instance.snowflakecomputing.com:443 "POST /session?delete=true&request_guid=d7a94e0d-f2d5-491b-a66f-ebafdd03e6e6 HTTP/1.1" 200 76
[2022-10-22T21:50:31.604+0000] {network.py:1002} DEBUG - SUCCESS
[2022-10-22T21:50:31.605+0000] {network.py:1122} DEBUG - Session status for SessionPool 'my_snowflake_instance.snowflakecomputing.com', SessionPool 0/1 active sessions
[2022-10-22T21:50:31.605+0000] {network.py:711} DEBUG - ret[code] = None, after post request
[2022-10-22T21:50:31.607+0000] {connection.py:523} DEBUG - Session is closed
[2022-10-22T21:50:32.896+0000] {taskinstance.py:851} DEBUG - Refreshing TaskInstance <TaskInstance: blender_tables_snowflake.deduplicate_raw_data scheduled__2022-10-22T21:30:00+00:00 [running]> from DB
[2022-10-22T21:50:32.984+0000] {base_job.py:229} DEBUG - [heartbeat]

<removed repeated refresh/heartbeat logs for ~26 minutes> 

[2022-10-22T22:16:41.742+0000] {taskinstance.py:851} DEBUG - Refreshing TaskInstance <TaskInstance: blender_tables_snowflake.deduplicate_raw_data scheduled__2022-10-22T21:30:00+00:00 [running]> from DB
[2022-10-22T22:16:41.785+0000] {local_task_job.py:221} WARNING - DagRun timed out after 0:30:03.276675.
[2022-10-22T22:16:41.785+0000] {base_job.py:229} DEBUG - [heartbeat]
[2022-10-22T22:16:46.846+0000] {taskinstance.py:851} DEBUG - Refreshing TaskInstance <TaskInstance: blender_tables_snowflake.deduplicate_raw_data scheduled__2022-10-22T21:30:00+00:00 [skipped]> from DB
[2022-10-22T22:16:46.899+0000] {local_task_job.py:221} WARNING - DagRun timed out after 0:30:08.391427.
[2022-10-22T22:16:46.900+0000] {local_task_job.py:227} WARNING - State of this instance has been externally set to skipped. Terminating instance.
[2022-10-22T22:16:46.900+0000] {base_job.py:229} DEBUG - [heartbeat]
[2022-10-22T22:16:46.901+0000] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 46. PIDs of all processes in the group: [46]
[2022-10-22T22:16:46.902+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 46
[2022-10-22T22:16:46.902+0000] {taskinstance.py:1562} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-22T22:16:46.903+0000] {ocsp_snowflake.py:723} DEBUG - Caught here > Task received SIGTERM signal
[2022-10-22T22:16:46.985+0000] {ocsp_snowflake.py:1705} DEBUG - Caught here - Task received SIGTERM signal
[2022-10-22T22:16:47.085+0000] {ocsp_snowflake.py:554} DEBUG - Caught - 254017: 254017: Exception raised while decoding OCSP Response Cache Task received SIGTERM signal
[2022-10-22T22:16:47.086+0000] {ocsp_snowflake.py:524} DEBUG - Failed to read OCSP response cache file file:///home/astro/.cache/snowflake/ocsp_response_cache.json: 254017: 254017: Exception raised while decoding OCSP Response Cache Task received SIGTERM signal, No worry. It will validate with OCSP server. Ignoring...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/snowflake/connector/ocsp_snowflake.py", line 1701, in decode_ocsp_response_cache
    SnowflakeOCSP.OCSP_CACHE.update_or_delete_cache(
  File "/usr/local/lib/python3.9/site-packages/snowflake/connector/ocsp_snowflake.py", line 724, in update_or_delete_cache
    raise ex
  File "/usr/local/lib/python3.9/site-packages/snowflake/connector/ocsp_snowflake.py", line 718, in update_or_delete_cache
    OCSPCache.update_cache(ocsp, cert_id, ocsp_response)
  File "/usr/local/lib/python3.9/site-packages/snowflake/connector/ocsp_snowflake.py", line 736, in update_cache
    with OCSPCache.CACHE_LOCK:
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1564, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/snowflake/connector/ocsp_snowflake.py", line 515, in read_file
    OCSPCache.read_ocsp_response_cache_file(
  File "/usr/local/lib/python3.9/site-packages/snowflake/connector/ocsp_snowflake.py", line 555, in read_ocsp_response_cache_file
    raise ex
  File "/usr/local/lib/python3.9/site-packages/snowflake/connector/ocsp_snowflake.py", line 541, in read_ocsp_response_cache_file
    ocsp.decode_ocsp_response_cache(json.load(f))
  File "/usr/local/lib/python3.9/site-packages/snowflake/connector/ocsp_snowflake.py", line 1709, in decode_ocsp_response_cache
    raise RevocationCheckError(
snowflake.connector.errors.RevocationCheckError: 254017: 254017: Exception raised while decoding OCSP Response Cache Task received SIGTERM signal
[2022-10-22T22:16:47.088+0000] {ocsp_snowflake.py:1063} DEBUG - validating certificate: my_snowflake_instance.snowflakecomputing.com
[2022-10-22T22:16:47.097+0000] {ocsp_asn1crypto.py:434} DEBUG - # of certificates: 2
[2022-10-22T22:16:47.099+0000] {ocsp_asn1crypto.py:439} DEBUG - subject: {'country_name': 'US', 'state_or_province_name': 'California', 'locality_name': 'San Mateo', 'organization_name': 'Snowflake Inc.', 'common_name': '*.east-us-2.azure.snowflakecomputing.com'}, issuer: {'country_name': 'US', 'organization_name': 'DigiCert Inc', 'common_name': 'DigiCert TLS RSA SHA256 2020 CA1'}
[2022-10-22T22:16:47.183+0000] {ocsp_asn1crypto.py:439} DEBUG - subject: {'country_name': 'US', 'organization_name': 'DigiCert Inc', 'common_name': 'DigiCert TLS RSA SHA256 2020 CA1'}, issuer: {'country_name': 'US', 'organization_name': 'DigiCert Inc', 'organizational_unit_name': 'www.digicert.com', 'common_name': 'DigiCert Global Root CA'}
[2022-10-22T22:16:47.187+0000] {ocsp_asn1crypto.py:460} DEBUG - not found issuer_der: {'country_name': 'US', 'organization_name': 'DigiCert Inc', 'organizational_unit_name': 'www.digicert.com', 'common_name': 'DigiCert Global Root CA'}
[2022-10-22T22:16:47.190+0000] {ocsp_snowflake.py:682} DEBUG - hit cache for subject: {'country_name': 'US', 'state_or_province_name': 'California', 'locality_name': 'San Mateo', 'organization_name': 'Snowflake Inc.', 'common_name': '*.east-us-2.azure.snowflakecomputing.com'}
[2022-10-22T22:16:47.192+0000] {ocsp_snowflake.py:682} DEBUG - hit cache for subject: {'country_name': 'US', 'organization_name': 'DigiCert Inc', 'common_name': 'DigiCert TLS RSA SHA256 2020 CA1'}
[2022-10-22T22:16:47.195+0000] {ocsp_snowflake.py:682} DEBUG - hit cache for subject: {'country_name': 'US', 'state_or_province_name': 'California', 'locality_name': 'San Mateo', 'organization_name': 'Snowflake Inc.', 'common_name': '*.east-us-2.azure.snowflakecomputing.com'}
[2022-10-22T22:16:47.285+0000] {ocsp_snowflake.py:1237} DEBUG - using OCSP response cache
[2022-10-22T22:16:47.286+0000] {ocsp_asn1crypto.py:328} DEBUG - Certificate is NOT attached in Basic OCSP Response. Using issuer's certificate
[2022-10-22T22:16:47.286+0000] {ocsp_asn1crypto.py:336} DEBUG - Verifying the OCSP response is signed by the issuer.

  ```

**Comment by daychr** [comment]
We've identified a potential conflict with [OpenLineage](https://openlineage.io/blog/python-client/) that may be responsible for this behavior. This package is enabled by default in [Astronomer](https://docs.astronomer.io/astro/set-up-data-lineage) 4.2.0+ and attempts to collect metadata before the Snowflake query is run. Because we are not currently using this feature, we tried disabling OpenLineage by passing the environmental variable OPENLINEAGE_DISABLED=True. After doing so, the connection failures went away. We will raise this issue with Astronomer support as we may want to enable this feature again in the near future.

**Comment by markfickett** [comment]
I'm running into a hanging call in the Snowflake Python connector that has a stack going through `ssl_wrap_socket_with_ocsp`, so I wonder if it's related in some way.

The stack trace (from `py-spy` on the hung process, starting with our `snowflake_connector.py` wrapper at the bottom on up to the top of the stack) is:

```
Thread 1 (idle): "MainThread"
    _execute_child (subprocess.py:1754)
    __init__ (subprocess.py:951)
    _findSoname_ldconfig (ctypes/util.py:289)
    find_library (ctypes/util.py:329)
    _load_backend_lib (cffi/api.py:818)
    _make_ffi_library (cffi/api.py:832)
    dlopen (cffi/api.py:150)
    load_lib (Cryptodome/Util/_raw_api.py:97)
    <module> (Cryptodome/Math/_IntegerGMP.py:100)
    _call_with_frames_removed (<frozen importlib._bootstrap>:228)
    exec_module (<frozen importlib._bootstrap_external>:850)
    _load_unlocked (<frozen importlib._bootstrap>:680)
    _find_and_load_unlocked (<frozen importlib._bootstrap>:986)
    _find_and_load (<frozen importlib._bootstrap>:1007)
    <module> (Cryptodome/Math/Numbers.py:34)
    _call_with_frames_removed (<frozen importlib._bootstrap>:228)
    exec_module (<frozen importlib._bootstrap_external>:850)
    _load_unlocked (<frozen importlib._bootstrap>:680)
    _find_and_load_unlocked (<frozen importlib._bootstrap>:986)
    _find_and_load (<frozen importlib._bootstrap>:1007)
    <module> (Cryptodome/PublicKey/RSA.py:42)
    _call_with_frames_removed (<frozen importlib._bootstrap>:228)
    exec_module (<frozen importlib._bootstrap_external>:850)
    _load_unlocked (<frozen importlib._bootstrap>:680)
    _find_and_load_unlocked (<frozen importlib._bootstrap>:986)
    _find_and_load (<frozen importlib._bootstrap>:1007)
    _call_with_frames_removed (<frozen importlib._bootstrap>:228)
    _handle_fromlist (<frozen importlib._bootstrap>:1058)
    <module> (connector/ocsp_asn1crypto.py:31)
    _call_with_frames_removed (<frozen importlib._bootstrap>:228)
    exec_module (<frozen importlib._bootstrap_external>:850)
    _load_unlocked (<frozen importlib._bootstrap>:680)
    _find_and_load_unlocked (<frozen importlib._bootstrap>:986)
    _find_and_load (<frozen importlib._bootstrap>:1007)
    ssl_wrap_socket_with_ocsp (connector/ssl_wrap_socket.py:78)
    connect (connector/vendored/urllib3/connection.py:411)
    _validate_conn (connector/vendored/urllib3/connectionpool.py:1010)
    _make_request (connector/vendored/urllib3/connectionpool.py:382)
    urlopen (connector/vendored/urllib3/connectionpool.py:699)
    send (connector/vendored/requests/adapters.py:439)
    send (connector/vendored/requests/sessions.py:655)
    request (connector/vendored/requests/sessions.py:542)
    _request_exec (connector/network.py:1009)
    _request_exec_wrapper (connector/network.py:838)
    fetch (connector/network.py:795)
    _post_request (connector/network.py:705)
    authenticate (connector/auth.py:257)
    __authenticate (connector/connection.py:1014)
    _authenticate (connector/connection.py:994)
    __open_connection (connector/connection.py:731)
    connect (connector/connection.py:492)
    __init__ (connector/connection.py:279)
    Connect (connector/__init__.py:51)
    open_snowflake (snowflake_connector.py:88)
... more application code ...
```

This is in a Docker container running on EKS Kubernetes. So it's PID 1 in the container, and `strace` shows:

```
# strace -p 1
strace: Process 1 attached
futex(0x7ff897a1a740, FUTEX_WAIT_PRIVATE, 0, NULL
```

In more detail (with locals and native stack frames) the top of the stack is:

```
Thread 1 (idle): "MainThread"
    syscall (libc-2.28.so)
    0x7ff8adbcbe46 (grpc/_cython/cygrpc.cpython-39-x86_64-linux-gnu.so)
    0x7ff8adbcbd92 (grpc/_cython/cygrpc.cpython-39-x86_64-linux-gnu.so)
    0x7ff8ad7184da (grpc/_cython/cygrpc.cpython-39-x86_64-linux-gnu.so)
    0x7ff8ad964457 (grpc/_cython/cygrpc.cpython-39-x86_64-linux-gnu.so)
    0x7ff8ad96590b (grpc/_cython/cygrpc.cpython-39-x86_64-linux-gnu.so)
    0x7ff8ad980c4e (grpc/_cython/cygrpc.cpython-39-x86_64-linux-gnu.so)
    0x7ff8b04d3758 (libc-2.28.so)
    fork (libc-2.28.so)
    0x7ff8afe13972 (_posixsubprocess.cpython-39-x86_64-linux-gnu.so)
    _execute_child (subprocess.py:1754)
        Arguments:
            self: <Popen at 0x7ff88156cc10>
            args: ["/sbin/ldconfig", "-p"]
            preexec_fn: None
            close_fds: True
            pass_fds: ()
            cwd: None
            env: {"LC_ALL": "C", "LANG": "C"}
            startupinfo: None
            creationflags: 0
            shell: False
            p2cread: 16
            p2cwrite: -1
            c2pread: 17
            c2pwrite: 18
            errread: -1
            errwrite: 16
            restore_signals: True
            gid: None
            gids: None
            uid: None
            umask: -1
            start_new_session: False
        Locals:
            orig_executable: "/sbin/ldconfig"
            errpipe_read: 19
            errpipe_write: 20
            low_fds_to_close: []
            env_list: [<bytes at 0x7ff88156cd50>, <bytes at 0x7ff88156cd20>]
            k: <bytes at 0x7ff88156ccf0>
            v: "C"
            executable_list: (<bytes at 0x7ff88156ccc0>)
            fds_to_keep: <set at 0x7ff882b19200>
```

**Comment by sfc-gh-yixie** [comment]
@sfc-gh-aling I remember you fixed it with the newer version?

**Comment by sfc-gh-achandrasekaran** [comment]
This has since been fixed

**Comment by wolfier** [comment]
Which version of `snowflake-connector-python` was this issue fixed in?

**Comment by sfc-gh-achandrasekaran** [comment]
3.0.1
