### ISSUE TITLE
After installing snowflake connector with this command pip install snowflake-connector-python is installing cryptography version36.0 therefore it is giving below error.

### ISSUE THREAD

**Issue by somilagarwalgit** [snowflakedb/snowflake-connector-python#1300]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?
 -  3.7.10  

2. What operating system and processor architecture are you using?

 - Linux-4.14.291-218.527.amzn2.x86_64-x86_64-with-glibc2.2.5

3. What are the component versions in the environment (`pip freeze`)?

 - asn1crypto==1.5.1
aws-cfn-bootstrap==2.0
beautifulsoup4==4.9.3
boto==2.49.0
boto3==1.25.2
botocore==1.28.2
certifi==2022.9.24
cffi==1.15.1
charset-normalizer==2.0.12
click==8.1.1
cryptography==36.0.2
docutils==0.14
filelock==3.8.0
idna==3.4
jmespath==1.0.0
joblib==1.1.0
lockfile==0.11.0
lxml==4.8.0
mysqlclient==1.4.2
nltk==3.7
nose==1.3.4
numpy==1.20.0
oscrypto==1.3.0
pandas==1.3.5
psycopg2-binary==2.9.4
py-dateutil==2.2
pyarrow==9.0.0
pycparser==2.21
pycryptodomex==3.15.0
PyJWT==2.6.0
pyOpenSSL==22.1.0
pystache==0.5.4
python-daemon==2.2.3
python-dateutil==2.8.2
python37-sagemaker-pyspark==1.4.1
pytz==2022.1
PyYAML==5.4.1
regex==2021.11.10
requests==2.28.1
s3transfer==0.6.0
simplejson==3.2.0
six==1.13.0
snowflake==0.0.3
snowflake-connector-python==2.8.0
tqdm==4.63.1
typing-extensions==4.4.0
urllib3==1.26.12
windmill==1.6

4. What did you do?

  I am executing spark submit command in AWS EMR to run a data pipeline.

5. What did you expect to see?

   Ideally it should make connection with snowflake but it is giving an cryptography version issue. 

6. Can you set logging to DEBUG and collect the logs?

   ```
Traceback (most recent call last):
  File "/home/hadoop/Framework/Data_Processing/SparkHub/run.py", line 41, in <module>
    from hub_app import *
  File "/home/hadoop/Framework/Data_Processing/SparkHub/hub_app/__init__.py", line 1, in <module>
    from hub_app.entity import *
  File "/home/hadoop/Framework/Data_Processing/SparkHub/hub_app/entity.py", line 8, in <module>
    import boto3
  File "/home/hadoop/.local/lib/python3.7/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/home/hadoop/.local/lib/python3.7/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/hadoop/.local/lib/python3.7/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/home/hadoop/.local/lib/python3.7/site-packages/botocore/client.py", line 17, in <module>
    from botocore import waiter, xform_name
  File "/home/hadoop/.local/lib/python3.7/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/home/hadoop/.local/lib/python3.7/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/home/hadoop/.local/lib/python3.7/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/home/hadoop/.local/lib/python3.7/site-packages/botocore/docs/client.py", line 14, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/home/hadoop/.local/lib/python3.7/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/home/hadoop/.local/lib/python3.7/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/home/hadoop/.local/lib/python3.7/site-packages/botocore/utils.py", line 35, in <module>
    import botocore.httpsession
  File "/home/hadoop/.local/lib/python3.7/site-packages/botocore/httpsession.py", line 46, in <module>
    from urllib3.contrib.pyopenssl import (
  File "/home/hadoop/.local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "/home/hadoop/.local/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/home/hadoop/.local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/home/hadoop/.local/lib/python3.7/site-packages/OpenSSL/crypto.py", line 3232, in <module>
    name="load_pkcs7_data",
TypeError: deprecated() got an unexpected keyword argument 'name'
   ```

**Comment by coboyoyo** [comment]
same

**Comment by sfc-gh-yixie** [comment]
@somilagarwalgit Do you still have the same error with the latest version of connector?

**Comment by sfc-gh-yixie** [comment]
@sfc-gh-mkeller @sfc-gh-aling I remember you guys looked into cryptography. Is this solved?

**Comment by sfc-gh-aling** [comment]
we've loosened the restriction on cryptography in our latest release, it should be resolved by installing the latest cryptography library.

I'm closing the issue, please let us know if the issue still exists
