### ISSUE TITLE
SNOW-688679: AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

### ISSUE THREAD

**Issue by drew-hansen** [snowflakedb/snowflake-connector-python#1316]
I am getting the following error since the 2.8.1 release yesterday. I believe the error is coming from pyOpenSSL:

AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

1. What version of Python are you using?

   3.8.14

2. What operating system and processor architecture are you using?

   Ubuntu 20.04.5

3. What are the component versions in the environment (`pip freeze`)?

   pip freeze fails (as did my script)

4. What did you do?

   It fails on the import. 

5. What did you expect to see?

   The import to succeed.

6. Can you set logging to DEBUG and collect the logs?
As mentioned, pip freeze fails. here is the output

  2022-11-03T14:32:35.4240778Z pip freeze
2022-11-03T14:32:35.4241392Z ========================== Starting Command Output ===========================
2022-11-03T14:32:35.4263021Z [command]/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/4ef8d3ab-a269-4fcd-a0b6-0e70e1d328da.sh
2022-11-03T14:32:36.0763348Z Traceback (most recent call last):
2022-11-03T14:32:36.0763840Z   File "/usr/bin/pip", line 11, in <module>
2022-11-03T14:32:36.0765210Z     load_entry_point('pip==20.0.2', 'console_scripts', 'pip')()
2022-11-03T14:32:36.0766087Z   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
2022-11-03T14:32:36.0766668Z     return get_distribution(dist).load_entry_point(group, name)
2022-11-03T14:32:36.0782721Z   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
2022-11-03T14:32:36.0783307Z     return ep.load()
2022-11-03T14:32:36.0784020Z   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
2022-11-03T14:32:36.0784510Z     return self.resolve()
2022-11-03T14:32:36.0794165Z   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
2022-11-03T14:32:36.0796385Z     module = __import__(self.module_name, fromlist=['__name__'], level=0)
2022-11-03T14:32:36.0797243Z   File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
2022-11-03T14:32:36.0798327Z     from pip._internal.cli.autocompletion import autocomplete
2022-11-03T14:32:36.0799279Z   File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
2022-11-03T14:32:36.0800709Z     from pip._internal.cli.main_parser import create_main_parser
2022-11-03T14:32:36.0801655Z   File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
2022-11-03T14:32:36.0802220Z     from pip._internal.cli import cmdoptions
2022-11-03T14:32:36.0802990Z   File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
2022-11-03T14:32:36.0803914Z     from pip._internal.exceptions import CommandError
2022-11-03T14:32:36.0804727Z   File "/usr/lib/python3/dist-packages/pip/_internal/exceptions.py", line 10, in <module>
2022-11-03T14:32:36.0805626Z     from pip._vendor.six import iteritems
2022-11-03T14:32:36.0806378Z   File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 65, in <module>
2022-11-03T14:32:36.0806865Z     vendored("cachecontrol")
2022-11-03T14:32:36.0807549Z   File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
2022-11-03T14:32:36.0808763Z     __import__(modulename, globals(), locals(), level=0)
2022-11-03T14:32:36.0811357Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-11-03T14:32:36.0811970Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2022-11-03T14:32:36.0812510Z   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
2022-11-03T14:32:36.0813069Z   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
2022-11-03T14:32:36.0813573Z   File "<frozen zipimport>", line 259, in load_module
2022-11-03T14:32:36.0814529Z   File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
2022-11-03T14:32:36.0815613Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-11-03T14:32:36.0816134Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2022-11-03T14:32:36.0816658Z   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
2022-11-03T14:32:36.0817179Z   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
2022-11-03T14:32:36.0834622Z   File "<frozen zipimport>", line 259, in load_module
2022-11-03T14:32:36.0835991Z   File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
2022-11-03T14:32:36.0836901Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-11-03T14:32:36.0837530Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2022-11-03T14:32:36.0839570Z   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
2022-11-03T14:32:36.0840195Z   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
2022-11-03T14:32:36.0840779Z   File "<frozen zipimport>", line 259, in load_module
2022-11-03T14:32:36.0841834Z   File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/adapter.py", line 5, in <module>
2022-11-03T14:32:36.0842556Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-11-03T14:32:36.0843221Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2022-11-03T14:32:36.0843825Z   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
2022-11-03T14:32:36.0844520Z   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
2022-11-03T14:32:36.0849956Z   File "<frozen zipimport>", line 259, in load_module
2022-11-03T14:32:36.0851025Z   File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py", line 95, in <module>
2022-11-03T14:32:36.0851661Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-11-03T14:32:36.0852184Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2022-11-03T14:32:36.0852735Z   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
2022-11-03T14:32:36.0853280Z   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
2022-11-03T14:32:36.0853787Z   File "<frozen zipimport>", line 259, in load_module
2022-11-03T14:32:36.0854647Z   File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
2022-11-03T14:32:36.0866187Z   File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
2022-11-03T14:32:36.0866707Z     from OpenSSL import crypto, SSL
2022-11-03T14:32:36.0868036Z   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
2022-11-03T14:32:36.0868880Z     class X509StoreFlags(object):
2022-11-03T14:32:36.0869620Z   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
2022-11-03T14:32:36.0870163Z     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
2022-11-03T14:32:36.0870888Z AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
2022-11-03T14:32:36.1043506Z Error in sys.excepthook:
2022-11-03T14:32:36.1043925Z Traceback (most recent call last):
2022-11-03T14:32:36.1045491Z   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
2022-11-03T14:32:36.1046132Z     from apport.fileutils import likely_packaged, get_recent_crashes
2022-11-03T14:32:36.1046958Z   File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
2022-11-03T14:32:36.1048186Z     from apport.report import Report
2022-11-03T14:32:36.1049167Z   File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
2022-11-03T14:32:36.1049649Z     import apport.fileutils
2022-11-03T14:32:36.1050327Z   File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
2022-11-03T14:32:36.1050905Z     import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
2022-11-03T14:32:36.1052034Z   File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
2022-11-03T14:32:36.1052519Z     import requests
2022-11-03T14:32:36.1052944Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-11-03T14:32:36.1053483Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2022-11-03T14:32:36.1054017Z   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
2022-11-03T14:32:36.1054558Z   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
2022-11-03T14:32:36.1055062Z   File "<frozen zipimport>", line 259, in load_module
2022-11-03T14:32:36.1055907Z   File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py", line 95, in <module>
2022-11-03T14:32:36.1056537Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-11-03T14:32:36.1057074Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2022-11-03T14:32:36.1057615Z   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
2022-11-03T14:32:36.1058153Z   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
2022-11-03T14:32:36.1058656Z   File "<frozen zipimport>", line 259, in load_module
2022-11-03T14:32:36.1059503Z   File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
2022-11-03T14:32:36.1060364Z   File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
2022-11-03T14:32:36.1060831Z     from OpenSSL import crypto, SSL
2022-11-03T14:32:36.1062422Z   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
2022-11-03T14:32:36.1063001Z     class X509StoreFlags(object):
2022-11-03T14:32:36.1063743Z   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
2022-11-03T14:32:36.1064299Z     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
2022-11-03T14:32:36.1065100Z AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
2022-11-03T14:32:36.1113067Z 
2022-11-03T14:32:36.1113573Z Original exception was:
2022-11-03T14:32:36.1113977Z Traceback (most recent call last):
2022-11-03T14:32:36.1114388Z   File "/usr/bin/pip", line 11, in <module>
2022-11-03T14:32:36.1115280Z     load_entry_point('pip==20.0.2', 'console_scripts', 'pip')()
2022-11-03T14:32:36.1116148Z   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
2022-11-03T14:32:36.1116762Z     return get_distribution(dist).load_entry_point(group, name)
2022-11-03T14:32:36.1117587Z   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
2022-11-03T14:32:36.1118387Z     return ep.load()
2022-11-03T14:32:36.1119125Z   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
2022-11-03T14:32:36.1119629Z     return self.resolve()
2022-11-03T14:32:36.1120343Z   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
2022-11-03T14:32:36.1121320Z     module = __import__(self.module_name, fromlist=['__name__'], level=0)
2022-11-03T14:32:36.1122251Z   File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
2022-11-03T14:32:36.1122774Z     from pip._internal.cli.autocompletion import autocomplete
2022-11-03T14:32:36.1123503Z   File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
2022-11-03T14:32:36.1124042Z     from pip._internal.cli.main_parser import create_main_parser
2022-11-03T14:32:36.1124763Z   File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
2022-11-03T14:32:36.1125859Z     from pip._internal.cli import cmdoptions
2022-11-03T14:32:36.1126639Z   File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
2022-11-03T14:32:36.1127173Z     from pip._internal.exceptions import CommandError
2022-11-03T14:32:36.1128121Z   File "/usr/lib/python3/dist-packages/pip/_internal/exceptions.py", line 10, in <module>
2022-11-03T14:32:36.1129004Z     from pip._vendor.six import iteritems
2022-11-03T14:32:36.1129882Z   File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 65, in <module>
2022-11-03T14:32:36.1130540Z     vendored("cachecontrol")
2022-11-03T14:32:36.1131377Z   File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
2022-11-03T14:32:36.1131902Z     __import__(modulename, globals(), locals(), level=0)
2022-11-03T14:32:36.1132391Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-11-03T14:32:36.1132910Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2022-11-03T14:32:36.1133434Z   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
2022-11-03T14:32:36.1133953Z   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
2022-11-03T14:32:36.1134445Z   File "<frozen zipimport>", line 259, in load_module
2022-11-03T14:32:36.1135274Z   File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
2022-11-03T14:32:36.1135892Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-11-03T14:32:36.1136410Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2022-11-03T14:32:36.1136923Z   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
2022-11-03T14:32:36.1137628Z   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
2022-11-03T14:32:36.1138323Z   File "<frozen zipimport>", line 259, in load_module
2022-11-03T14:32:36.1139300Z   File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
2022-11-03T14:32:36.1139998Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-11-03T14:32:36.1140513Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2022-11-03T14:32:36.1141028Z   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
2022-11-03T14:32:36.1141553Z   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
2022-11-03T14:32:36.1142044Z   File "<frozen zipimport>", line 259, in load_module
2022-11-03T14:32:36.1142849Z   File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/adapter.py", line 5, in <module>
2022-11-03T14:32:36.1143460Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-11-03T14:32:36.1143979Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2022-11-03T14:32:36.1144494Z   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
2022-11-03T14:32:36.1145330Z   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
2022-11-03T14:32:36.1145838Z   File "<frozen zipimport>", line 259, in load_module
2022-11-03T14:32:36.1146678Z   File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py", line 95, in <module>
2022-11-03T14:32:36.1147310Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-11-03T14:32:36.1147849Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2022-11-03T14:32:36.1149874Z   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
2022-11-03T14:32:36.1150438Z   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
2022-11-03T14:32:36.1150946Z   File "<frozen zipimport>", line 259, in load_module
2022-11-03T14:32:36.1151903Z   File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
2022-11-03T14:32:36.1152756Z   File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
2022-11-03T14:32:36.1153262Z     from OpenSSL import crypto, SSL
2022-11-03T14:32:36.1153948Z   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
2022-11-03T14:32:36.1154438Z     class X509StoreFlags(object):
2022-11-03T14:32:36.1155319Z   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
2022-11-03T14:32:36.1156044Z     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
2022-11-03T14:32:36.1156785Z AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
2022-11-03T14:32:36.1545790Z ##[error]Bash exited with code '1'.
2022-11-03T14:32:36.1561802Z ##[section]Finishing: freeze

**Comment by thrichardson-twist** [comment]
Our production pipeline is broken for this as well.

**Comment by sfc-gh-achandrasekaran** [comment]
This has since been fixed with a pyopenssl update.
