### ISSUE TITLE
SNOW-691434: snowflake.connector.network.RetryRequest: HTTPSConnectionPool(host='xxx', port=443): Read timed out. (read timeout=60)

### ISSUE THREAD

**Issue by adityakumar1990** [snowflakedb/snowflake-connector-python#1324]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?
   python 3.10

2. What operating system and processor architecture are you using?
   Linux

3. What are the component versions in the environment (`pip freeze`)?

snowflake-connector-python==2.7.11

4. What did you do?

I am making concurrently multiple connection with host , sometimes it is working as expected ,but seems like when actual data operation happening for huge data for some customers(For each customer generating separate connection) I am getting below error
ERROR|2022-11-09 09:16:31,520: HTTPSConnectionPool(host='xxxxx.xxxx.snowflakecomputing.com', port=443): Read timed out. (read timeout=60)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/contrib/pyopenssl.py", line 332, in recv_into
    raise timeout("The read operation timed out")
socket.timeout: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
snowflake.connector.vendored.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='xxx.xxxx.snowflakecomputing.com', port=443): Read timed out. (read timeout=60)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/network.py", line 1018, in _request_exec
    raw_ret = session.request(
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
snowflake.connector.vendored.requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='xxx.xxxx.snowflakecomputing.com', port=443): Read timed out. (read timeout=60)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/network.py", line 837, in _request_exec_wrapper
    return_object = self._request_exec(
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/network.py", line 1105, in _request_exec
    raise RetryRequest(err)
snowflake.connector.network.RetryRequest: HTTPSConnectionPool(host='xxx.xxx.snowflakecomputing.com', port=443): Read timed out. (read timeout=60)

5. What did you expect to see?

   What should have happened and what happened instead?

6. Can you set logging to DEBUG and collect the logs?

ERROR|2022-11-09 09:16:31,520: HTTPSConnectionPool(host='xxxxx.xxxx.snowflakecomputing.com', port=443): Read timed out. (read timeout=60)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/contrib/pyopenssl.py", line 332, in recv_into
    raise timeout("The read operation timed out")
socket.timeout: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
snowflake.connector.vendored.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='xxx.xxxx.snowflakecomputing.com', port=443): Read timed out. (read timeout=60)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/network.py", line 1018, in _request_exec
    raw_ret = session.request(
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/vendored/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
snowflake.connector.vendored.requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='xxx.xxxx.snowflakecomputing.com', port=443): Read timed out. (read timeout=60)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/network.py", line 837, in _request_exec_wrapper
    return_object = self._request_exec(
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/network.py", line 1105, in _request_exec
    raise RetryRequest(err)
snowflake.connector.network.RetryRequest: HTTPSConnectionPool(host='xxx.xxx.snowflakecomputing.com', port=443): Read timed out. (read timeout=60)

can you help me understand the main reason and any way we can increase the timeout period or any other mean to fix this issue

**Comment by adityakumar1990** [comment]
Any update on this gyus?

**Comment by sfc-gh-yixie** [comment]
@sfc-gh-mkeller  @sfc-gh-aling How about allowing users to configure the number of retries and backoff time?

**Comment by sfc-gh-achandrasekaran** [comment]
@adityakumar1990 no updates yet. We will discuss internally today

**Comment by sfc-gh-achandrasekaran** [comment]
We added custom retry support recently ( as of 3.4.0 ) so you should be able to leverage that!

**Comment by vipinanandcpp** [comment]
`def _download(
        self, connection: SnowflakeConnection | None = None, **kwargs
    ) -> Response:
        """Downloads the data that the ``ResultBatch`` is pointing at."""
        sleep_timer = 1
        backoff = (
            connection._backoff_generator
            if connection is not None
            else exponential_backoff()()
        )
        for retry in range(**MAX_DOWNLOAD_RETRY**):
            try:
                with TimerContextManager() as download_metric:
                    logger.debug(f"started downloading result batch id: {self.id}")
                    chunk_url = self._remote_chunk_info.url
                    request_data = {
                        "url": chunk_url,
                        "headers": self._chunk_headers,
                        "timeout": **DOWNLOAD_TIMEOUT**,
                    }
                    # Try to reuse a connection if possible
                    if connection and connection._rest is not None:
                        with connection._rest._use_requests_session() as session:
                            logger.debug(
                                f"downloading result batch id: {self.id} with existing session {session}"
                            )
                            response = session.request("get", **request_data)
                    else:
                        logger.debug(
                            f"downloading result batch id: {self.id} with new session"
                        )
                        response = requests.get(**request_data)

                    if response.status_code == OK:
                        logger.debug(
                            f"successfully downloaded result batch id: {self.id}"
                        )
                        break

                    # Raise error here to correctly go in to exception clause
                    if is_retryable_http_code(response.status_code):
                        # retryable server exceptions
                        error: Error = get_http_retryable_error(response.status_code)
                        raise RetryRequest(error)
                    elif response.status_code == UNAUTHORIZED:
                        # make a unauthorized error
                        raise_okta_unauthorized_error(None, response)
                    else:
                        raise_failed_request_error(None, chunk_url, "get", response)

            except (RetryRequest, Exception) as e:
                if retry == MAX_DOWNLOAD_RETRY - 1:
                    # Re-throw if we failed on the last retry
                    e = e.args[0] if isinstance(e, RetryRequest) else e
                    raise e
                sleep_timer = next(backoff)
                logger.exception(
                    f"Failed to fetch the large result set batch "
                    f"{self.id} for the {retry + 1} th time, "
                    f"backing off for {sleep_timer}s for the reason: '{e}'"
                )
                time.sleep(sleep_timer)

        self._metrics[DownloadMetrics.download.value] = (
            download_metric.get_timing_millis()
        )
        return response` going back to this code, would it be possible to let users configure this? I am not sure if 7 and 10 seconds here (https://github.com/snowflakedb/snowflake-connector-python/blob/main/src/snowflake/connector/result_batch.py) were set based on empirical observations or just arbitrarily
