### ISSUE TITLE
SNOW-716553: requirements_39 throws an error during pip install

### ISSUE THREAD

**Issue by rchada** [snowflakedb/snowflake-connector-python#1380]
### I am trying to install Snowflake -connector-python for python3.9.15 on an Ubantu EC2 instance. Executing the Install command shown below throws an "ERROR: Invalid requirement: '<!DOCTYPE html>....'. 

Install Command for requirements_39.reqs
------------------------------------------------
python3 -m pip install -r https://github.com/snowflakedb/snowflake-connector-python/blob/main/tested_requirements/requirements_39.reqs -t  .

ERROR THROWN
---------------------
ERROR: Invalid requirement: !DOCTYPE html (from line 8 of https://github.com/snowflakedb/snowflake-connector-python/blob/main/tested_requirements/requirements_39.reqs)

**Comment by sfc-gh-sfan** [comment]
I don't think you can just use a link here because this link gives you an HTML file (try `curl https://github.com/snowflakedb/snowflake-connector-python/blob/main/tested_requirements/requirements_39.reqs`). You can download the requirement file and run `python3 -m pip install -r ./requirements_39.reqs -t .`

**Comment by rchada** [comment]
Did not work. Throws a ModuleNotFoundError: No module named 'zlib'

(venv) ubuntu@ip-172-31-93-214:~/snowflake_test$ python3 -m pip install -r ./requirements_39.reqs -t .
Traceback (most recent call last):
  File "/home/ubuntu/opt/python-3.9.15/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/opt/python-3.9.15/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/snowflake_test/venv/lib/python3.9/site-packages/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/home/ubuntu/snowflake_test/venv/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/ubuntu/snowflake_test/venv/lib/python3.9/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/ubuntu/snowflake_test/venv/lib/python3.9/site-packages/pip/_internal/cli/main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "/home/ubuntu/snowflake_test/venv/lib/python3.9/site-packages/pip/_internal/build_env.py", line 20, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "/home/ubuntu/snowflake_test/venv/lib/python3.9/site-packages/pip/_internal/cli/spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "/home/ubuntu/snowflake_test/venv/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 13, in <module>
    from pip._vendor.rich.console import (
  File "/home/ubuntu/snowflake_test/venv/lib/python3.9/site-packages/pip/_vendor/rich/console.py", line 7, in <module>
    import zlib
ModuleNotFoundError: No module named 'zlib'

**Comment by sfc-gh-mkeller** [comment]
@rchada I'm fairly certain that `zlib` is an optional standard Python module.
If you can't import it it is because your binary was compiled without `zlib` being available on you machine.
How did you install python and what OS are you using?

**Comment by sfc-gh-achandrasekaran** [comment]
@rchada is this still happening?

**Comment by rchada** [comment]
@sfc-gh-achandrasekaran , I gave up on it. Did not try again :-)

**Comment by sfc-gh-achandrasekaran** [comment]
Ok thanks. Closing this issue. Please feel free to reopen as needed
