### ISSUE TITLE
SNOW-733835: ReauthenticationRequest Error upon externalbrowser Authentication

### ISSUE THREAD

**Issue by seb-kro** [snowflakedb/snowflake-connector-python#1415]
1. What version of Python are you using?

   Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ]

2. What operating system and processor architecture are you using?

   macOS-13.2-arm64-arm-64bit

3. What are the component versions in the environment (`pip freeze`)?

   snowflake-connector-python==2.9.0
   snowflake-sqlalchemy==1.4.4

4. What did you do?

```
import sqlalchemy as sa
from snowflake.sqlalchemy import URL as SnowflakeUrl

params =  dict(
    account="<account>", port=443,
    warehouse="<warehouse>", database="<database>", driver="Snowflake Driver",
    authenticator="externalbrowser", role="<role>",
    user="<user>")

url = SnowflakeUrl(**params)
connect_args = {'client_session_keep_alive': True}
engine = sa.create_engine(url, connect_args=connect_args)
con = engine.connect()
con.close()
```

5. What did you expect to see?

   Successful authentication / execution of the snippet above.

   Instead the error shown below occurs _**when the ID Token is invalid**_. This usually seems to occur after some time out following previously successful connections. However, I was also able to trigger the error by manually adjusting the persisted token to a different value using macOS Keychain Access. If the snippet is executed again after the error, it is executed successfully.

   I might be wrong, but my suspicion is that this is caused by `connection.SnowflakeConnection.authenticate_with_retry` calling `_authenticate` again with the same `auth_instance` (`AuthByIdToken`) after the first call to `_authenticate` fails. And that this causes the function to use the same ID token again despite the implemented clean up. I.e., it might be necessary to create a new `auth_instance` of type `AuthByWebBrowser` instead when using `externalbrowser` authentication.

6. Can you set logging to DEBUG and collect the logs?

   Logging and stack trace with some of the more sensitive data replaced:

```
Traceback (most recent call last):
/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/bin/python /Users/<mac_user>/source/drive/base/tests/sources/tmp.py 
2023-01-27 17:35:34,181 - MainThread ssl_wrap_socket.py:43 - inject_into_urllib3() - DEBUG - Injecting ssl_wrap_socket_with_ocsp
2023-01-27 17:35:34,181 - MainThread _auth.py:91 - <module>() - DEBUG - cache directory: /Users/<mac_user>/Library/Caches/Snowflake
2023-01-27 17:35:34,246 - MainThread connection.py:280 - __init__() - INFO - Snowflake Connector for Python Version: 2.9.0, Python Version: 3.10.8, Platform: macOS-13.2-arm64-arm-64bit
2023-01-27 17:35:34,246 - MainThread connection.py:536 - connect() - DEBUG - connect
2023-01-27 17:35:34,246 - MainThread connection.py:832 - __config() - DEBUG - __config
2023-01-27 17:35:34,246 - MainThread connection.py:965 - __config() - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
2023-01-27 17:35:34,246 - MainThread connection.py:983 - __config() - INFO - Setting use_openssl_only mode to False
2023-01-27 17:35:34,246 - MainThread converter.py:145 - __init__() - DEBUG - use_numpy: False
2023-01-27 17:35:34,246 - MainThread connection.py:729 - __open_connection() - DEBUG - REST API object was created: <account>.snowflakecomputing.com:443
2023-01-27 17:35:40,658 - MainThread _auth.py:171 - authenticate() - DEBUG - authenticate
2023-01-27 17:35:40,660 - MainThread _auth.py:201 - authenticate() - DEBUG - assertion content: <token_id>
2023-01-27 17:35:40,660 - MainThread _auth.py:204 - authenticate() - DEBUG - account=<account_name>, user=<user>, database=<database>, schema=None, warehouse=<warehouse>, role=<role>, request_id=b38f231b-9be3-41a5-9a8a-de3675a08266
2023-01-27 17:35:40,660 - MainThread _auth.py:237 - authenticate() - DEBUG - body['data']: {'CLIENT_APP_ID': 'PythonConnector', 'CLIENT_APP_VERSION': '2.9.0', 'SVN_REVISION': None, 'ACCOUNT_NAME': '<account_name>', 'LOGIN_NAME': '<user>', 'CLIENT_ENVIRONMENT': {'APPLICATION': 'PythonConnector', 'OS': 'Darwin', 'OS_VERSION': 'macOS-13.2-arm64-arm-64bit', 'PYTHON_VERSION': '3.10.8', 'PYTHON_RUNTIME': 'CPython', 'PYTHON_COMPILER': 'Clang 14.0.6 ', 'OCSP_MODE': 'FAIL_OPEN', 'TRACING': 10, 'LOGIN_TIMEOUT': 120, 'NETWORK_TIMEOUT': None}, 'AUTHENTICATOR': 'ID_TOKEN', 'TOKEN': '<token_id>', 'SESSION_PARAMETERS': {'AUTOCOMMIT': False, 'CLIENT_SESSION_KEEP_ALIVE': True, 'CLIENT_PREFETCH_THREADS': 4, 'CLIENT_STORE_TEMPORARY_CREDENTIAL': True}}
2023-01-27 17:35:40,660 - MainThread _auth.py:247 - authenticate() - DEBUG - Timeout set to 120
2023-01-27 17:35:40,666 - MainThread retry.py:351 - from_int() - DEBUG - Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
2023-01-27 17:35:40,666 - MainThread retry.py:351 - from_int() - DEBUG - Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
2023-01-27 17:35:40,666 - MainThread network.py:1155 - _use_requests_session() - DEBUG - Session status for SessionPool '<account>.snowflakecomputing.com', SessionPool 1/1 active sessions
2023-01-27 17:35:40,666 - MainThread network.py:835 - _request_exec_wrapper() - DEBUG - remaining request timeout: 120, retry cnt: 1
2023-01-27 17:35:40,666 - MainThread network.py:816 - add_request_guid() - DEBUG - Request guid: ac83a4e5-3515-4f8e-ace4-861b80d7dd45
2023-01-27 17:35:40,666 - MainThread network.py:1014 - _request_exec() - DEBUG - socket timeout: 60
2023-01-27 17:35:40,670 - MainThread connectionpool.py:1003 - _new_conn() - DEBUG - Starting new HTTPS connection (1): <account>.snowflakecomputing.com:443
2023-01-27 17:35:40,972 - MainThread ocsp_snowflake.py:485 - reset_cache_dir() - DEBUG - cache directory: /Users/<mac_user>/Library/Caches/Snowflake
2023-01-27 17:35:41,017 - MainThread ssl_wrap_socket.py:80 - ssl_wrap_socket_with_ocsp() - DEBUG - OCSP Mode: FAIL_OPEN, OCSP response cache file name: None
2023-01-27 17:35:41,017 - MainThread ocsp_snowflake.py:523 - reset_ocsp_response_cache_uri() - DEBUG - ocsp_response_cache_uri: file:///Users/<mac_user>/Library/Caches/Snowflake/ocsp_response_cache.json
2023-01-27 17:35:41,017 - MainThread ocsp_snowflake.py:526 - reset_ocsp_response_cache_uri() - DEBUG - OCSP_VALIDATION_CACHE size: 202
2023-01-27 17:35:41,017 - MainThread ocsp_snowflake.py:333 - reset_ocsp_dynamic_cache_server_url() - DEBUG - OCSP response cache server is enabled: http://ocsp.snowflakecomputing.com/ocsp_response_cache.json
2023-01-27 17:35:41,017 - MainThread ocsp_snowflake.py:346 - reset_ocsp_dynamic_cache_server_url() - DEBUG - OCSP dynamic cache server RETRY URL: None
2023-01-27 17:35:41,017 - MainThread ocsp_snowflake.py:956 - validate() - DEBUG - validating certificate: <account>.snowflakecomputing.com
2023-01-27 17:35:41,018 - MainThread ocsp_asn1crypto.py:427 - extract_certificate_chain() - DEBUG - # of certificates: 4
2023-01-27 17:35:41,018 - MainThread ocsp_asn1crypto.py:432 - extract_certificate_chain() - DEBUG - subject: OrderedDict([('common_name', '*.eu-central-1.snowflakecomputing.com')]), issuer: OrderedDict([('country_name', 'US'), ('organization_name', 'Amazon'), ('organizational_unit_name', 'Server CA 1B'), ('common_name', 'Amazon')])
2023-01-27 17:35:41,018 - MainThread ocsp_asn1crypto.py:432 - extract_certificate_chain() - DEBUG - subject: OrderedDict([('country_name', 'US'), ('organization_name', 'Amazon'), ('organizational_unit_name', 'Server CA 1B'), ('common_name', 'Amazon')]), issuer: OrderedDict([('country_name', 'US'), ('organization_name', 'Amazon'), ('common_name', 'Amazon Root CA 1')])
2023-01-27 17:35:41,018 - MainThread ocsp_asn1crypto.py:432 - extract_certificate_chain() - DEBUG - subject: OrderedDict([('country_name', 'US'), ('organization_name', 'Amazon'), ('common_name', 'Amazon Root CA 1')]), issuer: OrderedDict([('country_name', 'US'), ('state_or_province_name', 'Arizona'), ('locality_name', 'Scottsdale'), ('organization_name', 'Starfield Technologies, Inc.'), ('common_name', 'Starfield Services Root Certificate Authority - G2')])
2023-01-27 17:35:41,019 - MainThread ocsp_asn1crypto.py:432 - extract_certificate_chain() - DEBUG - subject: OrderedDict([('country_name', 'US'), ('state_or_province_name', 'Arizona'), ('locality_name', 'Scottsdale'), ('organization_name', 'Starfield Technologies, Inc.'), ('common_name', 'Starfield Services Root Certificate Authority - G2')]), issuer: OrderedDict([('country_name', 'US'), ('organization_name', 'Starfield Technologies, Inc.'), ('organizational_unit_name', 'Starfield Class 2 Certification Authority')])
2023-01-27 17:35:41,020 - MainThread ocsp_asn1crypto.py:112 - read_cert_bundle() - DEBUG - reading certificate bundle: /opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/certifi/cacert.pem
2023-01-27 17:35:41,026 - MainThread ocsp_asn1crypto.py:453 - create_pair_issuer_subject() - DEBUG - not found issuer_der: OrderedDict([('country_name', 'US'), ('organization_name', 'Starfield Technologies, Inc.'), ('organizational_unit_name', 'Starfield Class 2 Certification Authority')])
2023-01-27 17:35:41,026 - MainThread ocsp_snowflake.py:722 - find_cache() - DEBUG - hit cache for subject: OrderedDict([('common_name', '*.eu-central-1.snowflakecomputing.com')])
2023-01-27 17:35:41,027 - MainThread ocsp_asn1crypto.py:227 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2025-09-15 19:41:06+00:00
2023-01-27 17:35:41,027 - MainThread ocsp_snowflake.py:722 - find_cache() - DEBUG - hit cache for subject: OrderedDict([('country_name', 'US'), ('organization_name', 'Amazon'), ('organizational_unit_name', 'Server CA 1B'), ('common_name', 'Amazon')])
2023-01-27 17:35:41,028 - MainThread ocsp_asn1crypto.py:227 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2025-09-15 19:45:34+00:00
2023-01-27 17:35:41,028 - MainThread ocsp_snowflake.py:722 - find_cache() - DEBUG - hit cache for subject: OrderedDict([('country_name', 'US'), ('organization_name', 'Amazon'), ('common_name', 'Amazon Root CA 1')])
2023-01-27 17:35:41,029 - MainThread ocsp_asn1crypto.py:227 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2023-06-22 07:00:00+00:00
2023-01-27 17:35:41,029 - MainThread ocsp_snowflake.py:722 - find_cache() - DEBUG - hit cache for subject: OrderedDict([('country_name', 'US'), ('state_or_province_name', 'Arizona'), ('locality_name', 'Scottsdale'), ('organization_name', 'Starfield Technologies, Inc.'), ('common_name', 'Starfield Services Root Certificate Authority - G2')])
2023-01-27 17:35:41,030 - MainThread ocsp_snowflake.py:1013 - _validate() - DEBUG - ok
2023-01-27 17:35:43,079 - MainThread connectionpool.py:456 - _make_request() - DEBUG - https://<account>.snowflakecomputing.com:443 "POST /session/v1/login-request?request_id=b38f231b-9be3-41a5-9a8a-de3675a08266&databaseName=<database>&warehouse=<warehouse>&roleName=<role>&request_guid=ac83a4e5-3515-4f8e-ace4-861b80d7dd45 HTTP/1.1" 200 403
2023-01-27 17:35:43,080 - MainThread network.py:1040 - _request_exec() - DEBUG - SUCCESS
2023-01-27 17:35:43,080 - MainThread network.py:1160 - _use_requests_session() - DEBUG - Session status for SessionPool '<account>.snowflakecomputing.com', SessionPool 0/1 active sessions
2023-01-27 17:35:43,080 - MainThread network.py:715 - _post_request() - DEBUG - ret[code] = 390195, after post request
2023-01-27 17:35:43,081 - MainThread _auth.py:366 - authenticate() - DEBUG - completed authentication
2023-01-27 17:35:43,096 - MainThread connection.py:1078 - authenticate_with_retry() - DEBUG - ID token expired. Reauthenticating...: 390195 (08001): None: The provided ID Token is invalid.
2023-01-27 17:35:43,096 - MainThread _auth.py:171 - authenticate() - DEBUG - authenticate
2023-01-27 17:35:43,096 - MainThread _auth.py:201 - authenticate() - DEBUG - assertion content: <token_id>
2023-01-27 17:35:43,096 - MainThread _auth.py:204 - authenticate() - DEBUG - account=<account_name>, user=<user>, database=<database>, schema=None, warehouse=<warehouse>, role=<role>, request_id=762fd170-1185-423d-a9a6-350c30150922
2023-01-27 17:35:43,096 - MainThread _auth.py:237 - authenticate() - DEBUG - body['data']: {'CLIENT_APP_ID': 'PythonConnector', 'CLIENT_APP_VERSION': '2.9.0', 'SVN_REVISION': None, 'ACCOUNT_NAME': '<account_name>', 'LOGIN_NAME': '<user>', 'CLIENT_ENVIRONMENT': {'APPLICATION': 'PythonConnector', 'OS': 'Darwin', 'OS_VERSION': 'macOS-13.2-arm64-arm-64bit', 'PYTHON_VERSION': '3.10.8', 'PYTHON_RUNTIME': 'CPython', 'PYTHON_COMPILER': 'Clang 14.0.6 ', 'OCSP_MODE': 'FAIL_OPEN', 'TRACING': 10, 'LOGIN_TIMEOUT': 120, 'NETWORK_TIMEOUT': None}, 'AUTHENTICATOR': 'ID_TOKEN', 'TOKEN': '<token_id>', 'SESSION_PARAMETERS': {'AUTOCOMMIT': False, 'CLIENT_SESSION_KEEP_ALIVE': True, 'CLIENT_PREFETCH_THREADS': 4, 'CLIENT_STORE_TEMPORARY_CREDENTIAL': True}}
2023-01-27 17:35:43,096 - MainThread _auth.py:247 - authenticate() - DEBUG - Timeout set to 120
2023-01-27 17:35:43,096 - MainThread network.py:1155 - _use_requests_session() - DEBUG - Session status for SessionPool '<account>.snowflakecomputing.com', SessionPool 1/1 active sessions
2023-01-27 17:35:43,096 - MainThread network.py:835 - _request_exec_wrapper() - DEBUG - remaining request timeout: 120, retry cnt: 1
2023-01-27 17:35:43,096 - MainThread network.py:816 - add_request_guid() - DEBUG - Request guid: 33f7cc07-8055-44f0-9baa-1539e74ba8ef
2023-01-27 17:35:43,096 - MainThread network.py:1014 - _request_exec() - DEBUG - socket timeout: 60
2023-01-27 17:35:45,574 - MainThread connectionpool.py:456 - _make_request() - DEBUG - https://<account>.snowflakecomputing.com:443 "POST /session/v1/login-request?request_id=762fd170-1185-423d-a9a6-350c30150922&databaseName=<database>&warehouse=<warehouse>&roleName=<role>&request_guid=33f7cc07-8055-44f0-9baa-1539e74ba8ef HTTP/1.1" 200 403
2023-01-27 17:35:45,576 - MainThread network.py:1040 - _request_exec() - DEBUG - SUCCESS
2023-01-27 17:35:45,576 - MainThread network.py:1160 - _use_requests_session() - DEBUG - Session status for SessionPool '<account>.snowflakecomputing.com', SessionPool 0/1 active sessions
2023-01-27 17:35:45,576 - MainThread network.py:715 - _post_request() - DEBUG - ret[code] = 390195, after post request
2023-01-27 17:35:45,576 - MainThread _auth.py:366 - authenticate() - DEBUG - completed authentication
2023-01-27 17:35:45,584 - MainThread _auth.py:673 - delete_temporary_credential() - ERROR - Failed to delete credential in the keyring: err=[Can't delete password in keychain: (-25300, 'Item not found')]
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1075, in authenticate_with_retry
    self._authenticate(auth_instance)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1096, in _authenticate
    auth.authenticate(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/snowflake/connector/auth/_auth.py", line 374, in authenticate
    raise ReauthenticationRequest(
snowflake.connector.network.ReauthenticationRequest: 390195 (08001): None: The provided ID Token is invalid.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/<mac_user>/source/drive/base/tests/sources/tmp.py", line 25, in <module>
    con = engine.connect()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/snowflake/connector/__init__.py", line 51, in Connect
    return SnowflakeConnection(**kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/snowflake/connector/connection.py", line 302, in __init__
    self.connect(**kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/snowflake/connector/connection.py", line 566, in connect
    self.__open_connection()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/snowflake/connector/connection.py", line 819, in __open_connection
    self.authenticate_with_retry(self.auth_class)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1079, in authenticate_with_retry
    self._authenticate(auth_instance)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1096, in _authenticate
    auth.authenticate(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py_3_10/lib/python3.10/site-packages/snowflake/connector/auth/_auth.py", line 374, in authenticate
    raise ReauthenticationRequest(
snowflake.connector.network.ReauthenticationRequest: 390195 (08001): None: The provided ID Token is invalid.
2023-01-27 17:35:45,655 - MainThread connection.py:581 - close() - INFO - closed
2023-01-27 17:35:45,655 - MainThread connection.py:597 - close() - DEBUG - Exception encountered in closing connection. ignoring...: 'SnowflakeConnection' object has no attribute '_telemetry'

Process finished with exit code 1
```

**Comment by tekumara** [comment]
Also seeing the above when using `snowflake-connector-python[secure-local-storage]` and `externalbrowser` auth on macOS.

Here's the stack trace:

```python
        logger.debug("completed authentication")
        if not ret["success"]:
            errno = ret.get("code", ER_FAILED_TO_CONNECT_TO_DB)
            if errno == ID_TOKEN_INVALID_LOGIN_REQUEST_GS_CODE:
                # clear stored id_token if failed to connect because of id_token
                # raise an exception for reauth without id_token
                self._rest.id_token = None
                delete_temporary_credential(self._rest._host, user, ID_TOKEN)
>               raise ReauthenticationRequest(
                    ProgrammingError(
                        msg=ret["message"],
                        errno=int(errno),
                        sqlstate=SQLSTATE_CONNECTION_WAS_NOT_ESTABLISHED,
                    )
                )
E               snowflake.connector.network.ReauthenticationRequest: 390195 (08001): The provided ID Token is invalid.
```

It occurs when the ID Token has expired (ie: after 4 hours). Re-running the program resolves the issue. However I would expect this to be handled by the snowflake connector, ie: if the token has expired, instead of throwing an exception, reauthenticate to obtain a new ID token.

**Comment by saulbein** [comment]
Seeing the same issue on Majaro linux, with `snowflake-connector-python==2.9.0`. Re-running solves the issue, but it's very annoying to have to run the same thing twice when the code seems to be supposed to handle the reauthentication requests.

**Comment by marcotielen** [comment]
+1

**Comment by ac4wong** [comment]
Any suggested workaround?  I am running a loop to load csv into snowflake (each takes ~ an hour).  At some point (I have 10+ csv), it will crash with this exact error.   
Is there any way to explicitly reset the ID expiry time programmatically?

**Comment by sfc-gh-mkeller** [comment]
I'd ❤️  if you people could verify my proposed bug fix before we merge it.
It can be installed with the following command `pip install git+https://github.com/snowflakedb/snowflake-connector-python@mkeller/SNOW-733835-extermalbrowser_reauth`

I've tested it with the reported way of doing:
> by manually adjusting the persisted token to a different value using macOS Keychain Access

**Comment by saulbein** [comment]
Verified the new version works with the Linux file cache with these steps:
1. Modified `.cache/snowflake/temporary_credential.json` to have an invalid token
2. Reproduced the bug using `snowflake-connector-python==3.0.0`, it crashed with the reported `ReauthenticationRequest` exception
3. Installed the `@mkeller/SNOW-733835-extermalbrowser_reauth` branch version
4. Modified the cached token again
5. The bug didn't happen

**Comment by tekumara** [comment]
I'm still getting this error using `snowflake-connector-python @ git+https://github.com/snowflakedb/snowflake-connector-python@14d92b00c4d3221401250c9f131ff59efb34de71`

I authenticate, wait 4 hours, and then try to auth again and get the dreaded:

> ReauthenticationRequest: 390195 (08001): The provided ID Token is invalid.
