### ISSUE TITLE
Errors with pyasn1 module

### ISSUE THREAD

**Issue by tuzonghua** [snowflakedb/snowflake-connector-python#152]
Updated my version of the Snowflake Python connector to latest and ran into the issue below. Logs suggest an issue with pyasn1 or potentially pyasn1-modules.

1. Python version: Python 2.7.13

2. Linux-3.10.0-514.21.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core

3. pip list: 
```
Package                    Version
-------------------------- -----------
appdirs                    1.4.3
asn1crypto                 0.23.0
azure-common               1.1.18
azure-nspkg                3.0.2
azure-storage-blob         1.4.0
azure-storage-common       1.4.0
azure-storage-nspkg        3.1.0
backports-abc              0.5
bcrypt                     3.1.6
boto                       2.48.0
boto3                      1.9.92
botocore                   1.12.92
certifi                    2018.11.29
cffi                       1.11.5
chardet                    3.0.4
ConfigArgParse             0.12.0
configparser               3.3.0.post2
cryptography               2.5
datadog                    0.16.0
decorator                  4.3.2
defusedxml                 0.5.0
docutils                   0.14
dropbox                    6.1
egnyte                     0.5.3
enum34                     1.1.6
future                     0.17.1
futures                    3.2.0
idna                       2.8
ijson                      2.3
ipaddress                  1.0.22
jira                       1.0.15
jmespath                   0.9.3
lockfile                   0.12.2
luigi                      2.7.9
MySQL-python               1.2.5
ndg-httpsclient            0.4.4
oauthlib                   3.0.1
ordereddict                1.1
packaging                  16.8
paramiko                   2.4.2
pbr                        3.1.1
pip                        19.0.2
psycopg2                   2.7.7
ptyprocess                 0.6.0
pyasn1                     0.4.5
pyasn1-modules             0.0.9
pycparser                  2.19
pycryptodomex              3.7.3
PyGithub                   1.35
PyJWT                      1.7.1
PyNaCl                     1.3.0
pyOpenSSL                  17.0.0
pyparsing                  2.3.1
pysftp                     0.2.9
python-daemon              2.1.2
python-dateutil            2.8.0
python-magic               0.4.15
pytz                       2018.9
pyzmq                      16.0.0
requests                   2.21.0
requests-oauthlib          1.2.0
requests-toolbelt          0.9.1
s3cmd                      2.0.2
s3transfer                 0.2.0
scp                        0.10.2
setuptools                 36.5.0
simplejson                 3.16.0
singledispatch             3.4.0.3
six                        1.12.0
snowflake-connector-python 1.7.6
snowflake-sqlalchemy       1.0.7
SQLAlchemy                 1.2.17
terminado                  0.6
tlslite                    0.4.9
tornado                    4.5.3
urllib3                    1.22
virtualenv                 15.1.0
wheel                      0.30.0
```

4. Logs (truncated):
```
3980 - 2019-02-12 21:47:20,026 - CRITICAL - bad news ...
Traceback (most recent call last):
  File "/path/to/script.py", line 95, in start
    self._run()
  . . . 
  File "/path/to/venv/lib/python2.7/site-packages/snowflake/connector/connection.py", line 175, in __init__
    self.connect(**kwargs)
  File "/path/to/venv/lib/python2.7/site-packages/snowflake/connector/connection.py", line 439, in connect
    self.__open_connection()
  File "/path/to/venv/lib/python2.7/site-packages/snowflake/connector/connection.py", line 639, in __open_connection
    self.__authenticate(auth_instance)
  File "/path/to/venv/lib/python2.7/site-packages/snowflake/connector/connection.py", line 863, in __authenticate
    session_parameters=self._session_parameters,
  File "/path/to/venv/lib/python2.7/site-packages/snowflake/connector/auth.py", line 225, in authenticate
    socket_timeout=self._rest._connection.login_timeout)
  File "/path/to/venv/lib/python2.7/site-packages/snowflake/connector/network.py", line 530, in _post_request
    _include_retry_params=_include_retry_params)
  File "/path/to/venv/lib/python2.7/site-packages/snowflake/connector/network.py", line 608, in fetch
    **kwargs)
  File "/path/to/venv/lib/python2.7/site-packages/snowflake/connector/network.py", line 666, in _request_exec_wrapper
    conn, full_url, cause)
  File "/path/to/venv/lib/python2.7/site-packages/snowflake/connector/network.py", line 696, in handle_invalid_certificate_error
    u'errno': ER_FAILED_TO_REQUEST,
  File "/path/to/venv/lib/python2.7/site-packages/snowflake/connector/errors.py", line 100, in errorhandler_wrapper
    connection.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/path/to/venv/lib/python2.7/site-packages/snowflake/connector/errors.py", line 73, in default_errorhandler
    done_format_msg=errorvalue.get(u'done_format_msg'))
OperationalError: 250003: Failed to execute request: <TagSet object at 0x7f4e9611ac50 tags 0:0:4> not in asn1Spec: <AuthorityInfoAccessSyntax value object at 0x7f4e96131ed0 componentType=<AccessDescription schema object at 0x7f4e96224e90 componentType=<NamedTypes object at 0x7f4e96224a90 types <NamedType object at 0x7f4e96224990 type accessMethod=<ObjectIdentifier schema object at 0x7f4e96224910 tagSet <TagSet object at 0x7f4e9bb7dd50 tags 0:0:6>>>, <NamedType object at 0x7f4e96224a50 type accessLocation=<GeneralName schema object at 0x7f4e962249d0 componentType=<NamedTypes object at 0x7f4e9621c850 types <NamedType object at 0x7f4e96215b50 type otherName=<AnotherName schema object at 0x7f4e96215c90 componentType=<NamedTypes object at 0x7f4e96215610 types <NamedType object at 0x7f4e96215590 type type-id=<ObjectIdentifier schema object at 0x7f4e96215550 tagSet <TagSet object at 0x7f4e9bb7dd50 tags 0:0:6>>>, <NamedType object at 0x7f4e962155d0 type value=<Any schema object at 0x7f4e9621
5750 tagSet <TagSet object at 0x7f4e96215690 tags 128:32:0> encoding iso-8859-1>>> tagSet=<TagSet object at 0x7f4e96215cd0 tags 128:32:0> subtypeSpec=<ConstraintsIntersection object at 0x7f4e9bb8a9d0> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb8aa10>>>, <NamedType object at 0x7f4e96215c10 type rfc822Name=<IA5String schema object at 0x7f4e96215e10 tagSet <TagSet object at 0x7f4e96215e50 tags 128:0:1> encoding us-ascii>>, <NamedType object at 0x7f4e96215d90 type dNSName=<IA5String schema object at 0x7f4e96215f90 tagSet <TagSet object at 0x7f4e96215fd0 tags 128:0:2> encoding us-ascii>>, <NamedType object at 0x7f4e96215f10 type x400Address=<ORAddress schema object at 0x7f4e9621c150 componentType=<NamedTypes object at 0x7f4e9627d510 types <NamedType object at 0x7f4e9627d3d0 type built-in-standard-attributes=<BuiltInStandardAttributes value object at 0x7f4e9627d250 componentType=<NamedTypes object at 0x7f4e96272ad0 types <OptionalNamedType object at 0x7f4e96272350 type country-n
ame=<CountryName schema object at 0x7f4e962722d0 componentType=<NamedTypes object at 0x7f4e96267e90 types <NamedType object at 0x7f4e96267c10 type x121-dcc-code=<NumericString schema object at 0x7f4e96267c90 subtypeSpec <ConstraintsIntersection object at 0x7f4e96267cd0 consts <ValueSizeConstraint object at 0x7f4e96267c50 consts <Integer value object at 0x7f4e9635c3d0 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [3]>, <Integer value object at 0x7f4e9635c3d0 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [3]>>> tagSet <TagSet object at 0x7f4e9bb93290 tags 0:0:18> encoding us-ascii>>, <NamedType object at 0x7f4e96267d50 type iso-3166-alpha2-code=<PrintableString schema object at 0x7f4e96267e10 subtypeSpec <ConstraintsIntersection object at 0x7f4e96267e50 consts <ValueSizeConstraint object at 0x7f4e96267dd0 consts <Integer value object at 0x7f4e9635c390 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [2]>, <Integer value object at 0x7f4e9635c390 t
agSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [2]>>> tagSet <TagSet object at 0x7f4e9bb93310 tags 0:0:19> encoding us-ascii>>> subtypeSpec=<ConstraintsIntersection object at 0x7f4e9bb93090> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb93110 consts <ValueSizeConstraint object at 0x7f4e9bb930d0 consts 1, 1>> tagSet=<TagSet object at 0x7f4e96267b50 tags 64:32:1>>>, <OptionalNamedType object at 0x7f4e962723d0 type administration-domain-name=<AdministrationDomainName schema object at 0x7f4e96272390 componentType=<NamedTypes object at 0x7f4e96267710 types <NamedType object at 0x7f4e96267490 type numeric=<NumericString schema object at 0x7f4e96267510 subtypeSpec <ConstraintsIntersection object at 0x7f4e96267550 consts <ValueSizeConstraint object at 0x7f4e962674d0 consts 0, <Integer value object at 0x7f4e9635c4d0 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [16]>>> tagSet <TagSet object at 0x7f4e9bb93290 tags 0:0:18> encoding us-ascii>>, <NamedType object
  at 0x7f4e962675d0 type printable=<PrintableString schema object at 0x7f4e96267690 subtypeSpec <ConstraintsIntersection object at 0x7f4e962676d0 consts <ValueSizeConstraint object at 0x7f4e96267650 consts 0, <Integer value object at 0x7f4e9635c4d0 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [16]>>> tagSet <TagSet object at 0x7f4e9bb93310 tags 0:0:19> encoding us-ascii>>> subtypeSpec=<ConstraintsIntersection object at 0x7f4e9bb93090> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb93110 consts <ValueSizeConstraint object at 0x7f4e9bb930d0 consts 1, 1>> tagSet=<TagSet object at 0x7f4e962673d0 tags 64:32:2>>>, <OptionalNamedType object at 0x7f4e96272410 type network-address=<NetworkAddress schema object at 0x7f4e96272510 subtypeSpec <ConstraintsIntersection object at 0x7f4e96267290 consts <ValueSizeConstraint object at 0x7f4e96267210 consts 1, <Integer value object at 0x7f4e9635c990 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [16]>>> tagSet <TagSet
object at 0x7f4e962724d0 tags 0:0:18-128:32:0> encoding us-ascii>>, <OptionalNamedType object at 0x7f4e96272450 type terminal-identifier=<TerminalIdentifier schema object at 0x7f4e96272610 subtypeSpec <ConstraintsIntersection object at 0x7f4e96267190 consts <ValueSizeConstraint object at 0x7f4e96267150 consts 1, <Integer value object at 0x7f4e9635c910 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [24]>>> tagSet <TagSet object at 0x7f4e962725d0 tags 0:0:19-128:32:1> encoding us-ascii>>, <OptionalNamedType object at 0x7f4e96272550 type private-domain-name=<PrivateDomainName schema object at 0x7f4e96272750 componentType=<NamedTypes object at 0x7f4e9625cd10 types <NamedType object at 0x7f4e9625ca50 type numeric=<NumericString schema object at 0x7f4e9625cb10 subtypeSpec <ConstraintsIntersection object at 0x7f4e9625cb50 consts <ValueSizeConstraint object at 0x7f4e9625cad0 consts 1, <Integer value object at 0x7f4e9635c4d0 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> pa
yload [16]>>> tagSet <TagSet object at 0x7f4e9bb93290 tags 0:0:18> encoding us-ascii>>, <NamedType object at 0x7f4e9625cbd0 type printable=<PrintableString schema object at 0x7f4e9625cc90 subtypeSpec <ConstraintsIntersection object at 0x7f4e9625ccd0 consts <ValueSizeConstraint object at 0x7f4e9625cc50 consts 1, <Integer value object at 0x7f4e9635c4d0 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [16]>>> tagSet <TagSet object at 0x7f4e9bb93310 tags 0:0:19> encoding us-ascii>>> tagSet=<TagSet object at 0x7f4e962726d0 tags 128:32:2> subtypeSpec=<ConstraintsIntersection object at 0x7f4e9bb93090> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb93110 consts <ValueSizeConstraint object at 0x7f4e9bb930d0 consts 1, 1>>>>, <OptionalNamedType object at 0x7f4e96272650 type organization-name=<OrganizationName schema object at 0x7f4e96272890 subtypeSpec <ConstraintsIntersection object at 0x7f4e9625c9d0 consts <ValueSizeConstraint object at 0x7f4e9625c950 consts 1, <Integer valu
e object at 0x7f4e9635c710 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [64]>>> tagSet <TagSet object at 0x7f4e96272850 tags 0:0:19-128:32:3> encoding us-ascii>>, <OptionalNamedType object at 0x7f4e962727d0 type numeric-user-identifier=<NumericUserIdentifier schema object at 0x7f4e96272990 subtypeSpec <ConstraintsIntersection object at 0x7f4e9625c8d0 consts <ValueSizeConstraint object at 0x7f4e9625c890 consts 1, <Integer value object at 0x7f4e9635c6d0 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [32]>>> tagSet <TagSet object at 0x7f4e96272950 tags 0:0:18-128:32:4> encoding us-ascii>>, <OptionalNamedType object at 0x7f4e962728d0 type personal-name=<PersonalName schema object at 0x7f4e96272a90 componentType=<NamedTypes object at 0x7f4e9625c210 types <NamedType object at 0x7f4e96252b90 type surname=<PrintableString schema object at 0x7f4e96252d10 subtypeSpec <ConstraintsIntersection object at 0x7f4e96252d50 consts <ValueSizeConstraint object at 0x7f4e96252
c10 consts 1, <Integer value object at 0x7f4e9635c8d0 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [40]>>> tagSet <TagSet object at 0x7f4e96252cd0 tags 0:0:19-128:32:0> encoding us-ascii>>, <OptionalNamedType object at 0x7f4e96252c50 type given-name=<PrintableString schema object at 0x7f4e96252f10 subtypeSpec <ConstraintsIntersection object at 0x7f4e96252f50 consts <ValueSizeConstraint object at 0x7f4e96252dd0 consts 1, <Integer value object at 0x7f4e9635c610 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [16]>>> tagSet <TagSet object at 0x7f4e96252ed0 tags 0:0:19-128:32:1> encoding us-ascii>>, <OptionalNamedType object at 0x7f4e96252e50 type initials=<PrintableString schema object at 0x7f4e9625c110 subtypeSpec <ConstraintsIntersection object at 0x7f4e9625c150 consts <ValueSizeConstraint object at 0x7f4e96252f90 consts 1, <Integer value object at 0x7f4e9635c650 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [5]>>> tagSet <TagSet object at 0x7
f4e9625c0d0 tags 0:0:19-128:32:2> encoding us-ascii>>, <OptionalNamedType object at 0x7f4e9625c050 type generation-qualifier=<PrintableString schema object at 0x7f4e9625c2d0 subtypeSpec <ConstraintsIntersection object at 0x7f4e9625c310 consts <ValueSizeConstraint object at 0x7f4e9625c190 consts 1, <Integer value object at 0x7f4e9635c5d0 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [3]>>> tagSet <TagSet object at 0x7f4e9625c290 tags 0:0:19-128:32:3> encoding us-ascii>>> tagSet=<TagSet object at 0x7f4e96272a50 tags 0:32:17-128:32:5> subtypeSpec=<ConstraintsIntersection object at 0x7f4e9bb8ae10> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb8ae50>>>, <OptionalNamedType object at 0x7f4e962729d0 type organizational-unit-names=<OrganizationalUnitNames value object at 0x7f4e96272b90 componentType=<OrganizationalUnitName schema object at 0x7f4e96252ad0 subtypeSpec <ConstraintsIntersection object at 0x7f4e96252a90 consts <ValueSizeConstraint object at 0x7f4e962529d0 con
sts 1, <Integer value object at 0x7f4e9635c750 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [32]>>> tagSet <TagSet object at 0x7f4e9bb93310 tags 0:0:19> encoding us-ascii> tagSet=<TagSet object at 0x7f4e96272b50 tags 0:32:16-128:32:6> subtypeSpec=<ConstraintsIntersection object at 0x7f4e96252b50 consts <ValueSizeConstraint object at 0x7f4e96252b10 consts 1, <Integer value object at 0x7f4e9635c790 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [4]>>> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb8a450>>>> subtypeSpec=<ConstraintsIntersection object at 0x7f4e9bb8a9d0> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb8aa10> tagSet=<TagSet object at 0x7f4e9bb8a8d0 tags 0:32:16>>>, <OptionalNamedType object at 0x7f4e9627d450 type built-in-domain-defined-attributes=<BuiltInDomainDefinedAttributes value object at 0x7f4e9627d410 componentType=<BuiltInDomainDefinedAttribute schema object at 0x7f4e96252850 componentType=<NamedTypes object at 0x7f4e962524
10 types <NamedType object at 0x7f4e96252150 type type=<PrintableString schema object at 0x7f4e96252210 subtypeSpec <ConstraintsIntersection object at 0x7f4e96252250 consts <ValueSizeConstraint object at 0x7f4e962521d0 consts 1, <Integer value object at 0x7f4e9635c450 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [8]>>> tagSet <TagSet object at 0x7f4e9bb93310 tags 0:0:19> encoding us-ascii>>, <NamedType object at 0x7f4e962522d0 type value=<PrintableString schema object at 0x7f4e96252390 subtypeSpec <ConstraintsIntersection object at 0x7f4e962523d0 consts <ValueSizeConstraint object at 0x7f4e96252350 consts 1, <Integer value object at 0x7f4e9635c490 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [128]>>> tagSet <TagSet object at 0x7f4e9bb93310 tags 0:0:19> encoding us-ascii>>> subtypeSpec=<ConstraintsIntersection object at 0x7f4e9bb8a9d0> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb8aa10> tagSet=<TagSet object at 0x7f4e9bb8a8d0 tags 0:32:16>> subty
peSpec=<ConstraintsIntersection object at 0x7f4e962528d0 consts <ValueSizeConstraint object at 0x7f4e96252510 consts 1, <Integer value object at 0x7f4e9635c410 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [4]>>> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb8a450> tagSet=<TagSet object at 0x7f4e9bb8a310 tags 0:32:16>>>, <OptionalNamedType object at 0x7f4e9627d4d0 type extension-attributes=<ExtensionAttributes value object at 0x7f4e9627d490 componentType=<ExtensionAttribute schema object at 0x7f4e96249fd0 componentType=<NamedTypes object at 0x7f4e96249a90 types <NamedType object at 0x7f4e96249890 type extension-attribute-type=<Integer schema object at 0x7f4e962499d0 subtypeSpec <ConstraintsIntersection object at 0x7f4e96249a10 consts <ValueSizeConstraint object at 0x7f4e962498d0 consts 0, <Integer value object at 0x7f4e9635c510 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [256]>>> tagSet <TagSet object at 0x7f4e96249990 tags 0:0:2-128:32:0>>>, <Na
medType object at 0x7f4e96249910 type extension-attribute-value=<Any schema object at 0x7f4e96249bd0 tagSet <TagSet object at 0x7f4e96249b50 tags 128:32:1> encoding iso-8859-1>>> subtypeSpec=<ConstraintsIntersection object at 0x7f4e9bb8a9d0> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb8aa10> tagSet=<TagSet object at 0x7f4e9bb8a8d0 tags 0:32:16>> subtypeSpec=<ConstraintsIntersection object at 0x7f4e96252110 consts <ValueSizeConstraint object at 0x7f4e962520d0 consts 1, <Integer value object at 0x7f4e9635c510 tagSet <TagSet object at 0x7f4e9bb7d150 tags 0:0:2> payload [256]>>> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb8a610> tagSet=<TagSet object at 0x7f4e9bb8a4d0 tags 0:32:17>>>> tagSet=<TagSet object at 0x7f4e9621c190 tags 128:32:3> subtypeSpec=<ConstraintsIntersection object at 0x7f4e9bb8a9d0> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb8aa10>>>, <NamedType object at 0x7f4e9621c0d0 type directoryName=<Name schema object at 0x7f4e9621c290 componentType=<
NamedTypes object at 0x7f4e96334790 types <NamedType object at 0x7f4e96334750 type =<RDNSequence value object at 0x7f4e963346d0 componentType=<RelativeDistinguishedName value object at 0x7f4e96334590 componentType=<AttributeTypeAndValue schema object at 0x7f4e963345d0 componentType=<NamedTypes object at 0x7f4e9635ce90 types <NamedType object at 0x7f4e9635cdd0 type type=<AttributeType schema object at 0x7f4e9635ccd0 tagSet <TagSet object at 0x7f4e9bb7dd50 tags 0:0:6>>>, <NamedType object at 0x7f4e9635ce50 type value=<AttributeValue schema object at 0x7f4e9635ce10 encoding iso-8859-1>>> subtypeSpec=<ConstraintsIntersection object at 0x7f4e9bb8a9d0> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb8aa10> tagSet=<TagSet object at 0x7f4e9bb8a8d0 tags 0:32:16>> subtypeSpec=<ConstraintsIntersection object at 0x7f4e9bb8a5d0> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb8a610> tagSet=<TagSet object at 0x7f4e9bb8a4d0 tags 0:32:17>> subtypeSpec=<ConstraintsIntersection object at 0x
7f4e9bb8a410> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb8a450> tagSet=<TagSet object at 0x7f4e9bb8a310 tags 0:32:16>>>> tagSet=<TagSet object at 0x7f4e9621c2d0 tags 128:0:4> subtypeSpec=<ConstraintsIntersection object at 0x7f4e9bb93090> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb93110 consts <ValueSizeConstraint object at 0x7f4e9bb930d0 consts 1, 1>>>>, <NamedType object at 0x7f4e9621c390 type ediPartyName=<EDIPartyName schema object at 0x7f4e9621c450 componentType=<NamedTypes object at 0x7f4e96215310 types <OptionalNamedType object at 0x7f4e9620af50 type nameAssigner=<DirectoryString schema object at 0x7f4e96215090 componentType=<NamedTypes object at 0x7f4e9633c0d0 types <NamedType object at 0x7f4e96334890 type teletexString=<TeletexString schema object at 0x7f4e96334990 subtypeSpec <ConstraintsIntersection object at 0x7f4e963349d0 consts <ValueSizeConstraint object at 0x7f4e96334950 consts 1, 64>> tagSet <TagSet object at 0x7f4e9bb93390 tags 0:0:20> encoding i
so-8859-1>>, <NamedType object at 0x7f4e96334a50 type printableString=<PrintableString schema object at 0x7f4e96334b10 subtypeSpec <ConstraintsIntersection object at 0x7f4e96334b50 consts <ValueSizeConstraint object at 0x7f4e96334ad0 consts 1, 64>> tagSet <TagSet object at 0x7f4e9bb93310 tags 0:0:19> encoding us-ascii>>, <NamedType object at 0x7f4e96334b90 type universalString=<UniversalString schema object at 0x7f4e96334c50 subtypeSpec <ConstraintsIntersection object at 0x7f4e96334c90 consts <ValueSizeConstraint object at 0x7f4e96334c10 consts 1, 64>> tagSet <TagSet object at 0x7f4e9bb93b90 tags 0:0:28> encoding utf-32-be>>, <NamedType object at 0x7f4e96334cd0 type utf8String=<UTF8String schema object at 0x7f4e96334d90 subtypeSpec <ConstraintsIntersection object at 0x7f4e96334dd0 consts <ValueSizeConstraint object at 0x7f4e96334d50 consts 1, 64>> tagSet <TagSet object at 0x7f4e9bb93e10 tags 0:0:12> encoding utf-8>>, <NamedType object at 0x7f4e96334e10 type bmpString=<BMPString sche
ma object at 0x7f4e96334ed0 subtypeSpec <ConstraintsIntersection object at 0x7f4e96334f10 consts <ValueSizeConstraint object at 0x7f4e96334e90 consts 1, 64>> tagSet <TagSet object at 0x7f4e9bb93cd0 tags 0:0:30> encoding utf-16-be>>, <NamedType object at 0x7f4e96334f50 type ia5String=<IA5String schema object at 0x7f4e9633c050 subtypeSpec <ConstraintsIntersection object at 0x7f4e9633c090 consts <ValueSizeConstraint object at 0x7f4e96334fd0 consts 1, 64>> tagSet <TagSet object at 0x7f4e9bb93650 tags 0:0:22> encoding us-ascii>>> tagSet=<TagSet object at 0x7f4e962150d0 tags 128:0:0> subtypeSpec=<ConstraintsIntersection object at 0x7f4e9bb93090> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb93110 consts <ValueSizeConstraint object at 0x7f4e9bb930d0 consts 1, 1>>>>, <NamedType object at 0x7f4e96215190 type partyName=<DirectoryString schema object at 0x7f4e96215210 componentType=<NamedTypes object at 0x7f4e9633c0d0 types <NamedType object at 0x7f4e96334890 type teletexString=<Teletex
String schema object at 0x7f4e96334990 subtypeSpec <ConstraintsIntersection object at 0x7f4e963349d0 consts <ValueSizeConstraint object at 0x7f4e96334950 consts 1, 64>> tagSet <TagSet object at 0x7f4e9bb93390 tags 0:0:20> encoding iso-8859-1>>, <NamedType object at 0x7f4e96334a50 type printableString=<PrintableString schema object at 0x7f4e96334b10 subtypeSpec <ConstraintsIntersection object at 0x7f4e96334b50 consts <ValueSizeConstraint object at 0x7f4e96334ad0 consts 1, 64>> tagSet <TagSet object at 0x7f4e9bb93310 tags 0:0:19> encoding us-ascii>>, <NamedType object at 0x7f4e96334b90 type universalString=<UniversalString schema object at 0x7f4e96334c50 subtypeSpec <ConstraintsIntersection object at 0x7f4e96334c90 consts <ValueSizeConstraint object at 0x7f4e96334c10 consts 1, 64>> tagSet <TagSet object at 0x7f4e9bb93b90 tags 0:0:28> encoding utf-32-be>>, <NamedType object at 0x7f4e96334cd0 type utf8String=<UTF8String schema object at 0x7f4e96334d90 subtypeSpec <ConstraintsIntersectio
n object at 0x7f4e96334dd0 consts <ValueSizeConstraint object at 0x7f4e96334d50 consts 1, 64>> tagSet <TagSet object at 0x7f4e9bb93e10 tags 0:0:12> encoding utf-8>>, <NamedType object at 0x7f4e96334e10 type bmpString=<BMPString schema object at 0x7f4e96334ed0 subtypeSpec <ConstraintsIntersection object at 0x7f4e96334f10 consts <ValueSizeConstraint object at 0x7f4e96334e90 consts 1, 64>> tagSet <TagSet object at 0x7f4e9bb93cd0 tags 0:0:30> encoding utf-16-be>>, <NamedType object at 0x7f4e96334f50 type ia5String=<IA5String schema object at 0x7f4e9633c050 subtypeSpec <ConstraintsIntersection object at 0x7f4e9633c090 consts <ValueSizeConstraint object at 0x7f4e96334fd0 consts 1, 64>> tagSet <TagSet object at 0x7f4e9bb93650 tags 0:0:22> encoding us-ascii>>> tagSet=<TagSet object at 0x7f4e96215250 tags 128:0:1> subtypeSpec=<ConstraintsIntersection object at 0x7f4e9bb93090> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb93110 consts <ValueSizeConstraint object at 0x7f4e9bb930d0 const
s 1, 1>>>>> tagSet=<TagSet object at 0x7f4e9621c490 tags 128:32:5> subtypeSpec=<ConstraintsIntersection object at 0x7f4e9bb8a9d0> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb8aa10>>>, <NamedType object at 0x7f4e9621c3d0 type uniformResourceIdentifier=<IA5String schema object at 0x7f4e9621c5d0 tagSet <TagSet object at 0x7f4e9621c610 tags 128:0:6> encoding us-ascii>>, <NamedType object at 0x7f4e9621c550 type iPAddress=<OctetString schema object at 0x7f4e9621c750 tagSet <TagSet object at 0x7f4e9621c790 tags 128:0:7> encoding iso-8859-1>>, <NamedType object at 0x7f4e9621c6d0 type registeredID=<ObjectIdentifier schema object at 0x7f4e9621c8d0 tagSet <TagSet object at 0x7f4e9621c910 tags 128:0:8>>>> subtypeSpec=<ConstraintsIntersection object at 0x7f4e9bb93090> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb93110 consts <ValueSizeConstraint object at 0x7f4e9bb930d0 consts 1, 1>> tagSet=<TagSet object at 0x7f4e9bb8ae90 untagged>>>> subtypeSpec=<ConstraintsIntersection object
  at 0x7f4e9bb8a9d0> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb8aa10> tagSet=<TagSet object at 0x7f4e9bb8a8d0 tags 0:32:16>> subtypeSpec=<ConstraintsIntersection object at 0x7f4e96224f90 consts <ValueSizeConstraint object at 0x7f4e96224f50 consts 1, 64>> sizeSpec=<ConstraintsIntersection object at 0x7f4e9bb8a450> tagSet=<TagSet object at 0x7f4e9bb8a310 tags 0:32:16>>
```

**Comment by tuzonghua** [comment]
Looks like it was a pip dependency issue: `pip install -I pyasn1-modules==0.2.4` fixed the issue.
