### ISSUE TITLE
KeyError: 'endpoint_resolver'

### ISSUE THREAD

**Issue by bt-wil** [snowflakedb/snowflake-connector-python#156]
I'm seeing intermittent errors when uploading files via 
* `PUT file://... ... AUTO_COMPRESS = TRUE PARALLEL = 8`

I see issues at the start of the script, but goes away after the a few passes of processing.

```
def process(self):
    with ThreadPoolExecutor(max_workers=32) as pool:
        files = [...]
        results = pool.map(self.load_file_to_snowflake, files)

def load_file_to_snowflake(self, fname):
    with SnowflakeConnection(...) as conn, conn.cursor() as curs:
        res = curs.execute(
            'PUT file://{0} {1} AUTO_COMPRESS = TRUE PARALLEL = 8'.format(fname, stage_table)
        )
        res.fetchall()
```

This exception that get raised.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/<file>.py", line xyz, in <function>
    'PUT file://{0} {1} AUTO_COMPRESS = TRUE PARALLEL = 8'.format(..., ...)
  File "/usr/local/lib/python3.6/dist-packages/snowflake/connector/cursor.py", line 515, in execute
    sf_file_transfer_agent.execute()
  File "/usr/local/lib/python3.6/dist-packages/snowflake/connector/file_transfer_agent.py", line 212, in execute
    self._transfer_accelerate_config()
  File "/usr/local/lib/python3.6/dist-packages/snowflake/connector/file_transfer_agent.py", line 285, in _transfer_accelerate_config
    use_accelerate_endpoint=False)
  File "/usr/local/lib/python3.6/dist-packages/snowflake/connector/remote_storage_util.py", line 52, in create_client
    return util_class.create_client(stage_info, use_accelerate_endpoint=False)
  File "/usr/local/lib/python3.6/dist-packages/snowflake/connector/s3_util.py", line 75, in create_client
    config=config,
  File "/usr/local/lib/python3.6/dist-packages/boto3/__init__.py", line 100, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/boto3/session.py", line 389, in resource
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.6/dist-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.6/dist-packages/botocore/session.py", line 827, in create_client
    endpoint_resolver = self._get_internal_component('endpoint_resolver')
  File "/usr/local/lib/python3.6/dist-packages/botocore/session.py", line 694, in _get_internal_component
    return self._internal_components.get_component(name)
  File "/usr/local/lib/python3.6/dist-packages/botocore/session.py", line 906, in get_component
    del self._deferred[name]
KeyError: 'endpoint_resolver'
```

It looks to be an issue with boto shared clients.

1. What version of Python are you using (`python --version`)?
```
Python 3.6.8
```

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
```
Linux-4.4.0-1032-aws-x86_64-with-Ubuntu-14.04-trusty
```

3. What are the component versions in the environment (`pip list`)? 
```
snowflake-connector-python (1.7.4)
boto3 (1.9.109)
botocore (1.12.109)
```

**Comment by smtakeda** [comment]
Looks like you came across https://github.com/boto/boto3/issues/801

**Comment by bt-wil** [comment]
I'm creating a new `SnowflakeConnection` within each thread, and though that would have fixed it.  However, it looks like `SnowflakeConnection` internally create multiple threads if `parallel` is set?

**Comment by smtakeda** [comment]
yes, for smaller files <5M or so, multiple threads start. Maybe parallel=1 works?

**Comment by adrien-mg** [comment]
Hi :wave:  We're seeing this too and we've had to disable `parallelism`. Is there any chance that this PR addresses this? https://github.com/hasgeek/imgee/pull/141 

Should requirements be updated to pin the `boto3` version to that if that makes any sense?
