### ISSUE TITLE
SNOW-872279: snowflake.connector.errors.InterfaceError: 252005: Failed to convert current row, cause: ordinal must be >= 1

### ISSUE THREAD

**Issue by jeremyyeo** [snowflakedb/snowflake-connector-python#1652]
### Python version

Python 3.9.13

### Operating system and processor architecture

macOS-13.4.1-x86_64-i386-64bit

### Installed packages

```python
asn1crypto==1.5.1
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.2.0
cryptography==40.0.2
filelock==3.12.2
idna==3.4
oscrypto==1.3.0
packaging==23.1
pycparser==2.21
pycryptodomex==3.18.0
PyJWT==2.8.0
pyOpenSSL==23.2.0
pytz==2023.3
requests==2.31.0
snowflake-connector-python==3.0.4
sortedcontainers==2.4.0
typing_extensions==4.7.1
urllib3==1.26.16
```

### What did you do?

```python
import snowflake.connector
import os

USER = os.getenv("SNOWSQL_USER")
PASSWORD = os.getenv("SNOWSQL_PWD")
ACCOUNT = os.getenv("SNOWSQL_ACCOUNT")
WAREHOUSE = "transforming"

ctx = snowflake.connector.connect(user=USER, password=PASSWORD, account=ACCOUNT)
cs = ctx.cursor()
try:
    cs.execute("select '0000-12-30'::date as i")
    one_row = cs.fetchone()
    print(one_row[0])
finally:
    cs.close()
ctx.close()
```

### What did you expect to see?

If we try to retrieve a column that has a `DATE` with leading zeros `0000-12-30` - we run into an exception.

Filing this on behalf of the dbt team - stumbled upon this because one of our customers have such data in their tables (date with leading zeros) and when they try and preview the data from the dbt Cloud IDE - which uses [dbt-snowflake](https://github.com/dbt-labs/dbt-snowflake) under the hood - which of course uses the snowflake-connector-python library - we run into this Exception.

```
snowflake.connector.errors.InterfaceError: 252005: 252005: Failed to convert current row, cause: ordinal must be >= 1
```

### Can you set logging to DEBUG and collect the logs?

```bash
2023-07-20 11:22:09,579 - MainThread connection.py:295 - __init__() - INFO - Snowflake Connector for Python Version: 3.0.4, Python Version: 3.9.13, Platform: macOS-13.4.1-x86_64-i386-64bit
2023-07-20 11:22:09,579 - MainThread connection.py:560 - connect() - DEBUG - connect
2023-07-20 11:22:09,579 - MainThread connection.py:875 - __config() - DEBUG - __config
2023-07-20 11:22:09,579 - MainThread connection.py:1012 - __config() - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
2023-07-20 11:22:09,579 - MainThread connection.py:1030 - __config() - INFO - Setting use_openssl_only mode to False
2023-07-20 11:22:09,579 - MainThread converter.py:146 - __init__() - DEBUG - use_numpy: False
2023-07-20 11:22:09,580 - MainThread connection.py:755 - __open_connection() - DEBUG - REST API object was created: ska67070.snowflakecomputing.com:443
2023-07-20 11:22:09,580 - MainThread _auth.py:171 - authenticate() - DEBUG - authenticate
2023-07-20 11:22:09,580 - MainThread _auth.py:201 - authenticate() - DEBUG - assertion content: *********
2023-07-20 11:22:09,580 - MainThread _auth.py:204 - authenticate() - DEBUG - account=ska67070, user=<REDACT>, database=None, schema=None, warehouse=None, role=None, request_id=f50caca5-11fd-4d7a-9092-050cbcdbb844
2023-07-20 11:22:09,580 - MainThread _auth.py:237 - authenticate() - DEBUG - body['data']: {'CLIENT_APP_ID': 'PythonConnector', 'CLIENT_APP_VERSION': '3.0.4', 'SVN_REVISION': None, 'ACCOUNT_NAME': 'ska67070', 'LOGIN_NAME': '<REDACT>', 'CLIENT_ENVIRONMENT': {'APPLICATION': 'PythonConnector', 'OS': 'Darwin', 'OS_VERSION': 'macOS-13.4.1-x86_64-i386-64bit', 'PYTHON_VERSION': '3.9.13', 'PYTHON_RUNTIME': 'CPython', 'PYTHON_COMPILER': 'Clang 13.0.0 (clang-1300.0.27.3)', 'OCSP_MODE': 'FAIL_OPEN', 'TRACING': 10, 'LOGIN_TIMEOUT': 120, 'NETWORK_TIMEOUT': None}, 'SESSION_PARAMETERS': {'CLIENT_PREFETCH_THREADS': 4}}
2023-07-20 11:22:09,580 - MainThread _auth.py:247 - authenticate() - DEBUG - Timeout set to 120
2023-07-20 11:22:09,581 - MainThread retry.py:351 - from_int() - DEBUG - Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
2023-07-20 11:22:09,581 - MainThread retry.py:351 - from_int() - DEBUG - Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
2023-07-20 11:22:09,581 - MainThread network.py:1169 - _use_requests_session() - DEBUG - Session status for SessionPool 'ska67070.snowflakecomputing.com', SessionPool 1/1 active sessions
2023-07-20 11:22:09,581 - MainThread network.py:851 - _request_exec_wrapper() - DEBUG - remaining request timeout: 120, retry cnt: 1
2023-07-20 11:22:09,581 - MainThread network.py:832 - add_request_guid() - DEBUG - Request guid: 2dc2a8e5-7ce6-41d3-93f2-33f1e7f811b8
2023-07-20 11:22:09,581 - MainThread network.py:1025 - _request_exec() - DEBUG - socket timeout: 60
2023-07-20 11:22:09,591 - MainThread connectionpool.py:1003 - _new_conn() - DEBUG - Starting new HTTPS connection (1): ska67070.snowflakecomputing.com:443
2023-07-20 11:22:11,013 - MainThread cache.py:545 - _save() - DEBUG - acquiring /Users/jeremy/Library/Caches/Snowflake/ocsp_response_validation_cache.lock timed out, skipping saving...
2023-07-20 11:22:11,017 - MainThread ocsp_snowflake.py:485 - reset_cache_dir() - DEBUG - cache directory: /Users/jeremy/Library/Caches/Snowflake
2023-07-20 11:22:11,133 - MainThread ssl_wrap_socket.py:81 - ssl_wrap_socket_with_ocsp() - DEBUG - OCSP Mode: FAIL_OPEN, OCSP response cache file name: None
2023-07-20 11:22:11,134 - MainThread ocsp_snowflake.py:523 - reset_ocsp_response_cache_uri() - DEBUG - ocsp_response_cache_uri: file:///Users/jeremy/Library/Caches/Snowflake/ocsp_response_cache.json
2023-07-20 11:22:11,134 - MainThread ocsp_snowflake.py:526 - reset_ocsp_response_cache_uri() - DEBUG - OCSP_VALIDATION_CACHE size: 193
2023-07-20 11:22:11,134 - MainThread ocsp_snowflake.py:333 - reset_ocsp_dynamic_cache_server_url() - DEBUG - OCSP response cache server is enabled: http://ocsp.snowflakecomputing.com/ocsp_response_cache.json
2023-07-20 11:22:11,134 - MainThread ocsp_snowflake.py:346 - reset_ocsp_dynamic_cache_server_url() - DEBUG - OCSP dynamic cache server RETRY URL: None
2023-07-20 11:22:11,134 - MainThread ocsp_snowflake.py:956 - validate() - DEBUG - validating certificate: ska67070.snowflakecomputing.com
2023-07-20 11:22:11,134 - MainThread ocsp_asn1crypto.py:435 - extract_certificate_chain() - DEBUG - # of certificates: 4
2023-07-20 11:22:11,135 - MainThread ocsp_asn1crypto.py:440 - extract_certificate_chain() - DEBUG - subject: OrderedDict([('common_name', '*.us-west-2.snowflakecomputing.com')]), issuer: OrderedDict([('country_name', 'US'), ('organization_name', 'Amazon'), ('common_name', 'Amazon RSA 2048 M01')])
2023-07-20 11:22:11,136 - MainThread ocsp_asn1crypto.py:440 - extract_certificate_chain() - DEBUG - subject: OrderedDict([('country_name', 'US'), ('organization_name', 'Amazon'), ('common_name', 'Amazon RSA 2048 M01')]), issuer: OrderedDict([('country_name', 'US'), ('organization_name', 'Amazon'), ('common_name', 'Amazon Root CA 1')])
2023-07-20 11:22:11,137 - MainThread ocsp_asn1crypto.py:440 - extract_certificate_chain() - DEBUG - subject: OrderedDict([('country_name', 'US'), ('organization_name', 'Amazon'), ('common_name', 'Amazon Root CA 1')]), issuer: OrderedDict([('country_name', 'US'), ('state_or_province_name', 'Arizona'), ('locality_name', 'Scottsdale'), ('organization_name', 'Starfield Technologies, Inc.'), ('common_name', 'Starfield Services Root Certificate Authority - G2')])
2023-07-20 11:22:11,138 - MainThread ocsp_asn1crypto.py:440 - extract_certificate_chain() - DEBUG - subject: OrderedDict([('country_name', 'US'), ('state_or_province_name', 'Arizona'), ('locality_name', 'Scottsdale'), ('organization_name', 'Starfield Technologies, Inc.'), ('common_name', 'Starfield Services Root Certificate Authority - G2')]), issuer: OrderedDict([('country_name', 'US'), ('organization_name', 'Starfield Technologies, Inc.'), ('organizational_unit_name', 'Starfield Class 2 Certification Authority')])
2023-07-20 11:22:11,141 - MainThread ocsp_asn1crypto.py:114 - read_cert_bundle() - DEBUG - reading certificate bundle: /Users/jeremy/src/dbt-sandcastles/venv_sf_connector/lib/python3.9/site-packages/certifi/cacert.pem
2023-07-20 11:22:11,158 - MainThread ocsp_asn1crypto.py:463 - create_pair_issuer_subject() - DEBUG - not found issuer_der: OrderedDict([('country_name', 'US'), ('organization_name', 'Starfield Technologies, Inc.'), ('organizational_unit_name', 'Starfield Class 2 Certification Authority')])
2023-07-20 11:22:11,160 - MainThread ocsp_snowflake.py:722 - find_cache() - DEBUG - hit cache for subject: OrderedDict([('common_name', '*.us-west-2.snowflakecomputing.com')])
2023-07-20 11:22:11,162 - MainThread ocsp_asn1crypto.py:233 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2025-09-15 19:41:06+00:00
2023-07-20 11:22:11,162 - MainThread ocsp_snowflake.py:722 - find_cache() - DEBUG - hit cache for subject: OrderedDict([('country_name', 'US'), ('organization_name', 'Amazon'), ('common_name', 'Amazon RSA 2048 M01')])
2023-07-20 11:22:11,165 - MainThread ocsp_asn1crypto.py:233 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2025-09-15 19:45:34+00:00
2023-07-20 11:22:11,166 - MainThread ocsp_snowflake.py:722 - find_cache() - DEBUG - hit cache for subject: OrderedDict([('country_name', 'US'), ('organization_name', 'Amazon'), ('common_name', 'Amazon Root CA 1')])
2023-07-20 11:22:11,168 - MainThread ocsp_asn1crypto.py:233 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2024-06-06 12:00:00+00:00
2023-07-20 11:22:11,169 - MainThread ocsp_snowflake.py:722 - find_cache() - DEBUG - hit cache for subject: OrderedDict([('country_name', 'US'), ('state_or_province_name', 'Arizona'), ('locality_name', 'Scottsdale'), ('organization_name', 'Starfield Technologies, Inc.'), ('common_name', 'Starfield Services Root Certificate Authority - G2')])
2023-07-20 11:22:11,173 - MainThread ocsp_snowflake.py:1013 - _validate() - DEBUG - ok
2023-07-20 11:22:11,574 - MainThread connectionpool.py:456 - _make_request() - DEBUG - https://ska67070.snowflakecomputing.com:443 "POST /session/v1/login-request?request_id=f50caca5-11fd-4d7a-9092-050cbcdbb844&request_guid=2dc2a8e5-7ce6-41d3-93f2-33f1e7f811b8 HTTP/1.1" 200 1533
2023-07-20 11:22:11,575 - MainThread network.py:1051 - _request_exec() - DEBUG - SUCCESS
2023-07-20 11:22:11,576 - MainThread network.py:1174 - _use_requests_session() - DEBUG - Session status for SessionPool 'ska67070.snowflakecomputing.com', SessionPool 0/1 active sessions
2023-07-20 11:22:11,576 - MainThread network.py:731 - _post_request() - DEBUG - ret[code] = None, after post request
2023-07-20 11:22:11,576 - MainThread _auth.py:366 - authenticate() - DEBUG - completed authentication
2023-07-20 11:22:11,576 - MainThread _auth.py:413 - authenticate() - DEBUG - token = ******
2023-07-20 11:22:11,576 - MainThread _auth.py:416 - authenticate() - DEBUG - master_token = ******
2023-07-20 11:22:11,577 - MainThread _auth.py:420 - authenticate() - DEBUG - id_token = NULL
2023-07-20 11:22:11,577 - MainThread _auth.py:424 - authenticate() - DEBUG - mfa_token = NULL
2023-07-20 11:22:11,578 - MainThread connection.py:674 - cursor() - DEBUG - cursor
2023-07-20 11:22:11,579 - MainThread cursor.py:738 - execute() - DEBUG - executing SQL/command
2023-07-20 11:22:11,579 - MainThread cursor.py:594 - _preprocess_pyformat_query() - DEBUG - binding: [select '0000-12-30'::date as i] with input=[None], processed=[{}]
2023-07-20 11:22:11,579 - MainThread cursor.py:806 - execute() - INFO - query: [select '0000-12-30'::date as i]
2023-07-20 11:22:11,579 - MainThread connection.py:1391 - _next_sequence_counter() - DEBUG - sequence counter: 1
2023-07-20 11:22:11,579 - MainThread cursor.py:467 - _execute_helper() - DEBUG - Request id: ff8ca7a3-8270-4800-9b73-0ef127dddee0
2023-07-20 11:22:11,579 - MainThread cursor.py:469 - _execute_helper() - DEBUG - running query [select '0000-12-30'::date as i]
2023-07-20 11:22:11,580 - MainThread cursor.py:476 - _execute_helper() - DEBUG - is_file_transfer: True
2023-07-20 11:22:11,580 - MainThread connection.py:1058 - cmd_query() - DEBUG - _cmd_query
2023-07-20 11:22:11,580 - MainThread _query_context_cache.py:156 - serialize_to_json() - DEBUG - serialize_to_json() called
2023-07-20 11:22:11,580 - MainThread connection.py:1083 - cmd_query() - DEBUG - sql=[select '0000-12-30'::date as i], sequence_id=[1], is_file_transfer=[False]
2023-07-20 11:22:11,581 - MainThread network.py:1169 - _use_requests_session() - DEBUG - Session status for SessionPool 'ska67070.snowflakecomputing.com', SessionPool 1/1 active sessions
2023-07-20 11:22:11,581 - MainThread network.py:851 - _request_exec_wrapper() - DEBUG - remaining request timeout: None, retry cnt: 1
2023-07-20 11:22:11,581 - MainThread network.py:832 - add_request_guid() - DEBUG - Request guid: 741682c2-02fa-4cdb-8c4a-36c2368833ef
2023-07-20 11:22:11,581 - MainThread network.py:1025 - _request_exec() - DEBUG - socket timeout: 60
2023-07-20 11:22:11,942 - MainThread connectionpool.py:456 - _make_request() - DEBUG - https://ska67070.snowflakecomputing.com:443 "POST /queries/v1/query-request?requestId=ff8ca7a3-8270-4800-9b73-0ef127dddee0&request_guid=741682c2-02fa-4cdb-8c4a-36c2368833ef HTTP/1.1" 200 1451
2023-07-20 11:22:11,943 - MainThread network.py:1051 - _request_exec() - DEBUG - SUCCESS
2023-07-20 11:22:11,944 - MainThread network.py:1174 - _use_requests_session() - DEBUG - Session status for SessionPool 'ska67070.snowflakecomputing.com', SessionPool 0/1 active sessions
2023-07-20 11:22:11,944 - MainThread network.py:731 - _post_request() - DEBUG - ret[code] = None, after post request
2023-07-20 11:22:11,944 - MainThread network.py:755 - _post_request() - DEBUG - Query id: 01adbd9a-0403-5e23-000d-3783198a2cba
2023-07-20 11:22:11,944 - MainThread _query_context_cache.py:188 - deserialize_json_dict() - DEBUG - deserialize_json_dict() called: data from server: {'entries': [{'id': 0, 'timestamp': 141445985174442, 'priority': 0}]}
2023-07-20 11:22:11,945 - MainThread _query_context_cache.py:229 - deserialize_json_dict() - DEBUG - deserialize {'id': 0, 'timestamp': 141445985174442, 'priority': 0}
2023-07-20 11:22:11,945 - MainThread _query_context_cache.py:102 - _sync_priority_map() - DEBUG - sync_priority_map called priority_map size = 0, new_priority_map size = 1
2023-07-20 11:22:11,945 - MainThread _query_context_cache.py:128 - trim_cache() - DEBUG - trim_cache() called. treeSet size is 1 and cache capacity is 5
2023-07-20 11:22:11,945 - MainThread _query_context_cache.py:137 - trim_cache() - DEBUG - trim_cache() returns. treeSet size is 1 and cache capacity is 5
2023-07-20 11:22:11,945 - MainThread _query_context_cache.py:268 - deserialize_json_dict() - DEBUG - deserialize_json_dict() returns
2023-07-20 11:22:11,945 - MainThread _query_context_cache.py:273 - log_cache_entries() - DEBUG - Cache Entry: (0, 141445985174442, 0)
2023-07-20 11:22:11,945 - MainThread cursor.py:813 - execute() - DEBUG - sfqid: 01adbd9a-0403-5e23-000d-3783198a2cba
2023-07-20 11:22:11,945 - MainThread cursor.py:819 - execute() - INFO - query execution done
2023-07-20 11:22:11,946 - MainThread cursor.py:833 - execute() - DEBUG - SUCCESS
2023-07-20 11:22:11,946 - MainThread cursor.py:852 - execute() - DEBUG - PUT OR GET: False
2023-07-20 11:22:11,946 - MainThread cursor.py:947 - _init_result_and_meta() - DEBUG - Query result format: arrow
2023-07-20 11:22:11,946 - MainThread cursor.py:961 - _init_result_and_meta() - INFO - Number of results in first chunk: 1
2023-07-20 11:22:11,947 - MainThread arrow_iterator.cpython-39-darwin.so:0 - __cinit__() - DEBUG - Batches read: 1
2023-07-20 11:22:11,947 - MainThread CArrowIterator.cpp:16 - CArrowIterator() - DEBUG - Arrow BatchSize: 1
2023-07-20 11:22:11,947 - MainThread CArrowChunkIterator.cpp:50 - CArrowChunkIterator() - DEBUG - Arrow chunk info: batchCount 1, columnCount 1, use_numpy: 0
2023-07-20 11:22:11,947 - MainThread result_set.py:58 - result_set_iterator() - DEBUG - beginning to schedule result batch downloads
2023-07-20 11:22:11,947 - MainThread CArrowChunkIterator.cpp:74 - next() - DEBUG - Current batch index: 0, rows in current batch: 1
Traceback (most recent call last):
  File "/Users/jeremy/src/dbt-sandcastles/sf-check.py", line 26, in <module>
    one_row = cs.fetchone()
  File "/Users/jeremy/src/dbt-sandcastles/venv_sf_connector/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 1258, in fetchone
    _next = next(self._result, None)
  File "/Users/jeremy/src/dbt-sandcastles/venv_sf_connector/lib/python3.9/site-packages/snowflake/connector/result_set.py", line 68, in result_set_iterator
    yield from first_batch_iter
  File "src/snowflake/connector/arrow_iterator.pyx", line 175, in snowflake.connector.arrow_iterator.PyArrowIterator.__next__
  File "/Users/jeremy/src/dbt-sandcastles/venv_sf_connector/lib/python3.9/site-packages/snowflake/connector/errors.py", line 297, in errorhandler_wrapper
    raise Error.errorhandler_make_exception(
snowflake.connector.errors.InterfaceError: 252005: 252005: Failed to convert current row, cause: ordinal must be >= 1
2023-07-20 11:22:11,987 - MainThread connection.py:605 - close() - INFO - closed
2023-07-20 11:22:11,987 - MainThread telemetry.py:211 - close() - DEBUG - Closing telemetry client.
2023-07-20 11:22:11,987 - MainThread connection.py:608 - close() - INFO - No async queries seem to be running, deleting session
2023-07-20 11:22:11,988 - MainThread network.py:1169 - _use_requests_session() - DEBUG - Session status for SessionPool 'ska67070.snowflakecomputing.com', SessionPool 1/1 active sessions
2023-07-20 11:22:11,988 - MainThread network.py:851 - _request_exec_wrapper() - DEBUG - remaining request timeout: 5, retry cnt: 1
2023-07-20 11:22:11,988 - MainThread network.py:832 - add_request_guid() - DEBUG - Request guid: 4fbcec44-9ee9-41d1-85b8-771fd1857b01
2023-07-20 11:22:11,988 - MainThread network.py:1025 - _request_exec() - DEBUG - socket timeout: 60
2023-07-20 11:22:11,991 - MainThread network.py:942 - _request_exec_wrapper() - DEBUG - Ignored error
Traceback (most recent call last):
  File "/Users/jeremy/src/dbt-sandcastles/venv_sf_connector/lib/python3.9/site-packages/snowflake/connector/network.py", line 861, in _request_exec_wrapper
    return_object = self._request_exec(
  File "/Users/jeremy/src/dbt-sandcastles/venv_sf_connector/lib/python3.9/site-packages/snowflake/connector/network.py", line 1138, in _request_exec
    raise err
  File "/Users/jeremy/src/dbt-sandcastles/venv_sf_connector/lib/python3.9/site-packages/snowflake/connector/network.py", line 1037, in _request_exec
    raw_ret = session.request(
  File "/Users/jeremy/src/dbt-sandcastles/venv_sf_connector/lib/python3.9/site-packages/snowflake/connector/vendored/requests/sessions.py", line 577, in request
    settings = self.merge_environment_settings(
  File "/Users/jeremy/src/dbt-sandcastles/venv_sf_connector/lib/python3.9/site-packages/snowflake/connector/vendored/requests/sessions.py", line 759, in merge_environment_settings
    env_proxies = get_environ_proxies(url, no_proxy=no_proxy)
  File "/Users/jeremy/src/dbt-sandcastles/venv_sf_connector/lib/python3.9/site-packages/snowflake/connector/vendored/requests/utils.py", line 830, in get_environ_proxies
    if should_bypass_proxies(url, no_proxy=no_proxy):
  File "/Users/jeremy/src/dbt-sandcastles/venv_sf_connector/lib/python3.9/site-packages/snowflake/connector/vendored/requests/utils.py", line 814, in should_bypass_proxies
    bypass = proxy_bypass(parsed.hostname)
  File "/Users/jeremy/.pyenv/versions/3.9.13/lib/python3.9/urllib/request.py", line 2647, in proxy_bypass
    return proxy_bypass_macosx_sysconf(host)
  File "/Users/jeremy/.pyenv/versions/3.9.13/lib/python3.9/urllib/request.py", line 2624, in proxy_bypass_macosx_sysconf
    return _proxy_bypass_macosx_sysconf(host, proxy_settings)
  File "/Users/jeremy/.pyenv/versions/3.9.13/lib/python3.9/urllib/request.py", line 2566, in _proxy_bypass_macosx_sysconf
    from fnmatch import fnmatch
ImportError: sys.meta_path is None, Python is likely shutting down
2023-07-20 11:22:11,992 - MainThread network.py:1174 - _use_requests_session() - DEBUG - Session status for SessionPool 'ska67070.snowflakecomputing.com', SessionPool 0/1 active sessions
2023-07-20 11:22:11,992 - MainThread network.py:731 - _post_request() - DEBUG - ret[code] = N/A, after post request
2023-07-20 11:22:11,994 - MainThread _query_context_cache.py:142 - clear_cache() - DEBUG - clear_cache() called
2023-07-20 11:22:11,994 - MainThread connection.py:621 - close() - DEBUG - Session is closed
2023-07-20 11:22:11,995 - MainThread cache.py:511 - _load() - DEBUG - Fail to read cache from disk due to error: name 'open' is not defined
2023-07-20 11:22:11,995 - MainThread cache.py:549 - _save() - DEBUG - Fail to write cache to disk due to error: name 'open' is not defined
```

**Comment by mwahedi** [comment]
I have the same issue currently. At what point is this going to be picked up by the team? :)

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this issue. apologies for having it unresponded for so long, we're changing that.

we're trying to cast `0000-12-30` to date but such date [does not look like a valid one in Python](https://docs.python.org/3/library/datetime.html#datetime.MINYEAR), even without Snowflake.
```
>>> import datetime
>>> datetime.date(0000, 12, 30)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: year 0 is out of range
```

as a workaround perhaps it could be considered not casting the value to date / casting it to varchar. or the customer to sanitize their data which is already loaded / put checks and validation on the newly inserted one to prevent such inconsistency.

marking this issue as closed for now but if you feel this is something which needs to be addressed by the Snowflake Python Connector, please comment and we can reopen and look further.
