### ISSUE TITLE
SNOW-883965: Extract data from Snowflake to local file got a ECONNRESET error with 

### ISSUE THREAD

**Issue by williamli2021** [snowflakedb/snowflake-connector-python#1675]
### Python version

3.9

### Operating system and processor architecture

Docker platform=linux/amd64 ubuntu:20.04 image

### Installed packages

```python
python: 3.9
snowflake-connector-python 3.1.0
```

### What did you do?

```python
I need to export a snowflake table to local file folder through COPY then GET command.

COPY INTO @%{snowflake_table}/extract/ FROM (SELECT OBJECT_CONSTRUCT(*) FROM {snowflake_table}) file_format=(type=csv field_delimiter=',' escape_unenclosed_field=none compression=none) overwrite=true 

When running "GET @%{snowflake_table}/extract file://temp_file_path/;", the python connect showed the following error:

 snowflake.connector.errors.OperationalError: 253002: While getting file(s) there was an error: 'ChunkedEncodingError(ProtocolError('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')")))', this might be caused by your access to the blob storage provider, or by Snowflake.
```

### What did you expect to see?

When repeating running this same codes, in some occasion it is successful but most of time it failed with the above error.

As part of the exploration, if I set it to 

GET @%{snowflake_table}/extract file://{tmpfile_path}/ PARALLEL=1;

then it runs successfully every time. Is there a PARALLEL problem?

### Can you set logging to DEBUG and collect the logs?

```bash
import logging
import os

for logger_name in ('snowflake.connector',):
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```

**Comment by sfc-gh-sfan** [comment]
It would be useful to share the logs. This could be a connection issue between the client and the blob storage, because Snowflake only handles the initial `GET` command to give connector necessary information to fetch data from blob storage.

But also note that we recently fixed a bug related to `ECONNRESET` so that connector will retry internally: https://github.com/snowflakedb/snowflake-connector-python/commit/ac81f8769b288c25b2b8c16754f2bfed70bbcfe9, this should go out in the next release.

**Comment by williamli2021** [comment]
Thank you @sfc-gh-sfan. Is there a part of the python connector code managing the multi-threading of the GET command data? 

If using PARALLEL=1 works but not any other number, I wonder if it's something related to the multi-threading to get data and merging in the local drive.

**Comment by sfc-gh-sfan** [comment]
We do have parallel downloading, and it might have caused blob storage to reset connection. I'd suggest you to:

- Try the latest version (or from main) to see if it fixes the issue
- Provide DEBUG level log

**Comment by williamli2021** [comment]
I installed the debug code and captured some log. Here are the logs near the exception. let me know if you want to see more:

```
dsp_flow_ml_churn  | 2023-08-03 00:26:43,248 - ThreadPoolExecutor-0_14 connectionpool.py:456 - _make_request() - DEBUG - https://sfc-or-ds-prod2-customer-stage.s3.amazonaws.com:443 "GET /c0mk-s-p2ss0074/tables/41794378372526/extract/data_0_5_19.csv HTTP/1.1" 200 16778544
dsp_flow_ml_churn  | 2023-08-03 00:26:43,304 - ThreadPoolExecutor-2_6 file_transfer_agent.py:546 - postprocess_done_cb() - DEBUG - File data_0_0_12.csv reached postprocess callback
dsp_flow_ml_churn  | 2023-08-03 00:26:43,338 - ThreadPoolExecutor-2_2 file_transfer_agent.py:546 - postprocess_done_cb() - DEBUG - File data_0_0_10.csv reached postprocess callback
dsp_flow_ml_churn  | 2023-08-03 00:26:43,344 - ThreadPoolExecutor-0_17 network.py:1218 - _use_requests_session() - DEBUG - Session status for SessionPool 'b'sfc-or-ds-prod2-customer-stage.s3.amazonaws.com'', SessionPool 19/28 active sessions
dsp_flow_ml_churn  | 2023-08-03 00:26:43,377 - ThreadPoolExecutor-0_17 file_transfer_agent.py:500 - transfer_done_cb() - DEBUG - Chunk 0/1 of file data_0_1_2.csv reached callback
dsp_flow_ml_churn  | 2023-08-03 00:26:43,379 - ThreadPoolExecutor-0_17 file_transfer_agent.py:516 - transfer_done_cb() - DEBUG - Chunk progress: data_0_1_2.csv: completed: 1 failed: 0 total: 1
dsp_flow_ml_churn  | 2023-08-03 00:26:43,379 - ThreadPoolExecutor-0_17 file_transfer_agent.py:536 - transfer_done_cb() - DEBUG - submitting data_0_1_2.csv to done_postprocess
dsp_flow_ml_churn  | 2023-08-03 00:26:43,380 - ThreadPoolExecutor-0_17 s3_storage_client.py:535 - download_chunk() - DEBUG - Downloading chunk 0
dsp_flow_ml_churn  | 2023-08-03 00:26:43,380 - ThreadPoolExecutor-0_17 network.py:1213 - _use_requests_session() - DEBUG - Session status for SessionPool 'b'sfc-or-ds-prod2-customer-stage.s3.amazonaws.com'', SessionPool 20/28 active sessions
dsp_flow_ml_churn  | 2023-08-03 00:26:43,380 - ThreadPoolExecutor-0_17 storage_client.py:286 - _send_request_with_retry() - DEBUG - storage client request with session <snowflake.connector.vendored.requests.sessions.Session object at 0x7fa7a07666d0>
dsp_flow_ml_churn  | 2023-08-03 00:26:43,386 - ThreadPoolExecutor-2_3 storage_client.py:363 - finish_download() - DEBUG - encrypted data file=/app/data/extract/data_0_1_2.csv
dsp_flow_ml_churn  | 2023-08-03 00:26:43,393 - ThreadPoolExecutor-2_3 encryption_util.py:246 - decrypt_file() - DEBUG - encrypted file: /app/data/extract/data_0_1_2.csv.part, tmp file: /tmp/tmpkzizq_p4/data_0_1_2.csv.part#dxmubqnriq
dsp_flow_ml_churn  | 2023-08-03 00:26:43,447 - ThreadPoolExecutor-0_17 connectionpool.py:456 - _make_request() - DEBUG - https://sfc-or-ds-prod2-customer-stage.s3.amazonaws.com:443 "GET /c0mk-s-p2ss0074/tables/41794378372526/extract/data_0_2_0.csv HTTP/1.1" 200 16778288
dsp_flow_ml_churn  | 2023-08-03 00:26:43,668 - ThreadPoolExecutor-2_0 file_transfer_agent.py:546 - postprocess_done_cb() - DEBUG - File data_0_1_0.csv reached postprocess callback
dsp_flow_ml_churn  | 2023-08-03 00:26:43,733 - ThreadPoolExecutor-2_3 file_transfer_agent.py:546 - postprocess_done_cb() - DEBUG - File data_0_1_2.csv reached postprocess callback
dsp_flow_ml_churn  | 2023-08-03 00:26:44,221 - ThreadPoolExecutor-2_5 file_transfer_agent.py:546 - postprocess_done_cb() - DEBUG - File data_0_0_11.csv reached postprocess callback
dsp_flow_ml_churn  | 2023-08-03 00:26:44,280 - ThreadPoolExecutor-2_4 file_transfer_agent.py:546 - postprocess_done_cb() - DEBUG - File data_0_0_6.csv reached postprocess callback
dsp_flow_ml_churn  | 2023-08-03 00:26:44,283 - ThreadPoolExecutor-0_2 network.py:1218 - _use_requests_session() - DEBUG - Session status for SessionPool 'b'sfc-or-ds-prod2-customer-stage.s3.amazonaws.com'', SessionPool 19/28 active sessions
dsp_flow_ml_churn  | 2023-08-03 00:26:44,302 - ThreadPoolExecutor-0_2 file_transfer_agent.py:500 - transfer_done_cb() - DEBUG - Chunk 0/1 of file data_0_2_1.csv reached callback
dsp_flow_ml_churn  | 2023-08-03 00:26:44,314 - ThreadPoolExecutor-0_2 file_transfer_agent.py:516 - transfer_done_cb() - DEBUG - Chunk progress: data_0_2_1.csv: completed: 1 failed: 0 total: 1
dsp_flow_ml_churn  | 2023-08-03 00:26:44,316 - ThreadPoolExecutor-0_2 file_transfer_agent.py:536 - transfer_done_cb() - DEBUG - submitting data_0_2_1.csv to done_postprocess
dsp_flow_ml_churn  | 2023-08-03 00:26:44,318 - ThreadPoolExecutor-0_2 s3_storage_client.py:535 - download_chunk() - DEBUG - Downloading chunk 0
dsp_flow_ml_churn  | 2023-08-03 00:26:44,319 - ThreadPoolExecutor-2_2 storage_client.py:363 - finish_download() - DEBUG - encrypted data file=/app/data/extract/data_0_2_1.csv
dsp_flow_ml_churn  | 2023-08-03 00:26:44,321 - ThreadPoolExecutor-0_2 network.py:1213 - _use_requests_session() - DEBUG - Session status for SessionPool 'b'sfc-or-ds-prod2-customer-stage.s3.amazonaws.com'', SessionPool 20/28 active sessions
dsp_flow_ml_churn  | 2023-08-03 00:26:44,326 - ThreadPoolExecutor-2_2 encryption_util.py:246 - decrypt_file() - DEBUG - encrypted file: /app/data/extract/data_0_2_1.csv.part, tmp file: /tmp/tmpzsqzmhn6/data_0_2_1.csv.part#wkdjhuwzpj
dsp_flow_ml_churn  | 2023-08-03 00:26:44,331 - ThreadPoolExecutor-0_2 storage_client.py:286 - _send_request_with_retry() - DEBUG - storage client request with session <snowflake.connector.vendored.requests.sessions.Session object at 0x7fa7a069dd60>
dsp_flow_ml_churn  | 2023-08-03 00:26:44,427 - ThreadPoolExecutor-0_2 connectionpool.py:456 - _make_request() - DEBUG - https://sfc-or-ds-prod2-customer-stage.s3.amazonaws.com:443 "GET /c0mk-s-p2ss0074/tables/41794378372526/extract/data_0_5_20.csv HTTP/1.1" 200 16777344
dsp_flow_ml_churn  | 2023-08-03 00:26:45,032 - ThreadPoolExecutor-2_7 file_transfer_agent.py:546 - postprocess_done_cb() - DEBUG - File data_0_0_5.csv reached postprocess callback
dsp_flow_ml_churn  | 2023-08-03 00:26:45,118 - ThreadPoolExecutor-2_1 file_transfer_agent.py:546 - postprocess_done_cb() - DEBUG - File data_0_5_0.csv reached postprocess callback
dsp_flow_ml_churn  | 2023-08-03 00:26:45,218 - ThreadPoolExecutor-0_6 network.py:1218 - _use_requests_session() - DEBUG - Session status for SessionPool 'b'sfc-or-ds-prod2-customer-stage.s3.amazonaws.com'', SessionPool 19/28 active sessions
dsp_flow_ml_churn  | 2023-08-03 00:26:45,220 - ThreadPoolExecutor-0_6 file_transfer_agent.py:578 - function_and_callback_wrapper() - ERROR - An exception was raised in <bound method SnowflakeS3RestClient.download_chunk of <snowflake.connector.s3_storage_client.SnowflakeS3RestClient object at 0x7fa7a10124f0>>
dsp_flow_ml_churn  | Traceback (most recent call last):
dsp_flow_ml_churn  |   File "/home/myuser/venv/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/contrib/pyopenssl.py", line 327, in recv_into
dsp_flow_ml_churn  |     return self.connection.recv_into(*args, **kwargs)
dsp_flow_ml_churn  |   File "/home/myuser/venv/lib/python3.9/site-packages/OpenSSL/SSL.py", line 2088, in recv_into
dsp_flow_ml_churn  |     self._raise_ssl_error(self._ssl, result)
dsp_flow_ml_churn  |   File "/home/myuser/venv/lib/python3.9/site-packages/OpenSSL/SSL.py", line 1807, in _raise_ssl_error
dsp_flow_ml_churn  |     raise SysCallError(errno, errorcode.get(errno))
dsp_flow_ml_churn  | OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')
dsp_flow_ml_churn  | 
dsp_flow_ml_churn  | During handling of the above exception, another exception occurred:
dsp_flow_ml_churn  | 
dsp_flow_ml_churn  | Traceback (most recent call last):
dsp_flow_ml_churn  |   File "/home/myuser/venv/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/response.py", line 444, in _error_catcher
dsp_flow_ml_churn  |     yield
dsp_flow_ml_churn  |   File "/home/myuser/venv/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/response.py", line 567, in read
dsp_flow_ml_churn  |     data = self._fp_read(amt) if not fp_closed else b""
dsp_flow_ml_churn  |   File "/home/myuser/venv/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/response.py", line 533, in _fp_read
dsp_flow_ml_churn  |     return self._fp.read(amt) if amt is not None else self._fp.read()
dsp_flow_ml_churn  |   File "/usr/lib/python3.9/http/client.py", line 459, in read
dsp_flow_ml_churn  |     n = self.readinto(b)
dsp_flow_ml_churn  |   File "/usr/lib/python3.9/http/client.py", line 503, in readinto
dsp_flow_ml_churn  |     n = self.fp.readinto(b)
dsp_flow_ml_churn  |   File "/usr/lib/python3.9/socket.py", line 704, in readinto
dsp_flow_ml_churn  |     return self._sock.recv_into(b)
dsp_flow_ml_churn  |   File "/home/myuser/venv/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/contrib/pyopenssl.py", line 332, in recv_into
dsp_flow_ml_churn  |     raise SocketError(str(e))
dsp_flow_ml_churn  | OSError: (104, 'ECONNRESET')
dsp_flow_ml_churn  | 
dsp_flow_ml_churn  | During handling of the above exception, another exception occurred:
dsp_flow_ml_churn  | 
dsp_flow_ml_churn  | Traceback (most recent call last):
dsp_flow_ml_churn  |   File "/home/myuser/venv/lib/python3.9/site-packages/snowflake/connector/vendored/requests/models.py", line 816, in generate
dsp_flow_ml_churn  |     yield from self.raw.stream(chunk_size, decode_content=True)
dsp_flow_ml_churn  |   File "/home/myuser/venv/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/response.py", line 628, in stream
dsp_flow_ml_churn  |     data = self.read(amt=amt, decode_content=decode_content)
dsp_flow_ml_churn  |   File "/home/myuser/venv/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/response.py", line 593, in read
dsp_flow_ml_churn  |     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
dsp_flow_ml_churn  |   File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
dsp_flow_ml_churn  |     self.gen.throw(type, value, traceback)
dsp_flow_ml_churn  |   File "/home/myuser/venv/lib/python3.9/site-packages/snowflake/connector/vendored/urllib3/response.py", line 461, in _error_catcher
dsp_flow_ml_churn  |     raise ProtocolError("Connection broken: %r" % e, e)
dsp_flow_ml_churn  | snowflake.connector.vendored.urllib3.exceptions.ProtocolError: ('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')"))
dsp_flow_ml_churn  | 
dsp_flow_ml_churn  | During handling of the above exception, another exception occurred:
dsp_flow_ml_churn  | 
dsp_flow_ml_churn  | Traceback (most recent call last):
dsp_flow_ml_churn  |   File "/home/myuser/venv/lib/python3.9/site-packages/snowflake/connector/file_transfer_agent.py", line 575, in function_and_callback_wrapper
dsp_flow_ml_churn  |     work(*args, **kwargs),
dsp_flow_ml_churn  |   File "/home/myuser/venv/lib/python3.9/site-packages/snowflake/connector/s3_storage_client.py", line 539, in download_chunk
dsp_flow_ml_churn  |     response = self._send_request_with_authentication_and_retry(
dsp_flow_ml_churn  |   File "/home/myuser/venv/lib/python3.9/site-packages/snowflake/connector/s3_storage_client.py", line 362, in _send_request_with_authentication_and_retry
dsp_flow_ml_churn  |     return self._send_request_with_retry(
dsp_flow_ml_churn  |   File "/home/myuser/venv/lib/python3.9/site-packages/snowflake/connector/storage_client.py", line 287, in _send_request_with_retry
dsp_flow_ml_churn  |     response = session.request(verb, url, **rest_kwargs)
dsp_flow_ml_churn  |   File "/home/myuser/venv/lib/python3.9/site-packages/snowflake/connector/vendored/requests/sessions.py", line 587, in request
dsp_flow_ml_churn  |     resp = self.send(prep, **send_kwargs)
dsp_flow_ml_churn  |   File "/home/myuser/venv/lib/python3.9/site-packages/snowflake/connector/vendored/requests/sessions.py", line 745, in send
dsp_flow_ml_churn  |     r.content
dsp_flow_ml_churn  |   File "/home/myuser/venv/lib/python3.9/site-packages/snowflake/connector/vendored/requests/models.py", line 899, in content
dsp_flow_ml_churn  |     self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
dsp_flow_ml_churn  |   File "/home/myuser/venv/lib/python3.9/site-packages/snowflake/connector/vendored/requests/models.py", line 818, in generate
dsp_flow_ml_churn  |     raise ChunkedEncodingError(e)
dsp_flow_ml_churn  | snowflake.connector.vendored.requests.exceptions.ChunkedEncodingError: ('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')"))
dsp_flow_ml_churn  | 
dsp_flow_ml_churn  | 2023-08-03 00:26:45,245 - ThreadPoolExecutor-0_6 file_transfer_agent.py:500 - transfer_done_cb() - DEBUG - Chunk 0/1 of file data_0_5_10.csv reached callback
dsp_flow_ml_churn  | 2023-08-03 00:26:45,249 - ThreadPoolExecutor-0_6 file_transfer_agent.py:511 - transfer_done_cb() - DEBUG - Chunk 0 of file data_0_5_10.csv failed to transfer for unexpected exception ('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')"))
dsp_flow_ml_churn  | 2023-08-03 00:26:45,256 - ThreadPoolExecutor-0_6 file_transfer_agent.py:516 - transfer_done_cb() - DEBUG - Chunk progress: data_0_5_10.csv: completed: 0 failed: 1 total: 1
dsp_flow_ml_churn  | 2023-08-03 00:26:45,257 - ThreadPoolExecutor-0_6 file_transfer_agent.py:536 - transfer_done_cb() - DEBUG - submitting data_0_5_10.csv to done_postprocess
dsp_flow_ml_churn  | 2023-08-03 00:26:45,257 - ThreadPoolExecutor-0_6 s3_storage_client.py:535 - download_chunk() - DEBUG - Downloading chunk 0
dsp_flow_ml_churn  | 2023-08-03 00:26:45,258 - ThreadPoolExecutor-0_6 network.py:1213 - _use_requests_session() - DEBUG - Session status for SessionPool 'b'sfc-or-ds-prod2-customer-stage.s3.amazonaws.com'', SessionPool 20/28 active sessions
dsp_flow_ml_churn  | 2023-08-03 00:26:45,258 - ThreadPoolExecutor-0_6 storage_client.py:286 - _send_request_with_retry() - DEBUG - storage client request with session <snowflake.connector.vendored.requests.sessions.Session object at 0x7fa7a0635700>
dsp_flow_ml_churn  | 2023-08-03 00:26:45,259 - ThreadPoolExecutor-0_6 connectionpool.py:273 - _get_conn() - DEBUG - Resetting dropped connection: sfc-or-ds-prod2-customer-stage.s3.amazonaws.com
dsp_flow_ml_churn  | 2023-08-03 00:26:45,262 - ThreadPoolExecutor-2_0 storage_client.py:393 - finish_download() - ERROR - Failed to download a file: /app/data/extract/data_0_5_10.csv
dsp_flow_ml_churn  | NoneType: None
```

**Comment by williamli2021** [comment]
Already using 3.1.0 since yesterday. I added a few lines of logs to above. The logs from a run that is using 3.1.0. Same error.

MainThread connection.py:312 - __init__() - INFO - Snowflake Connector for Python Version: 3.1.0, Python Version: 3.9.5, Platform: Linux-5.15.49-linuxkit-pr-x86_64-with-glibc2.31

**Comment by williamli2021** [comment]
The code was trying to download 600K rows from a snowflake table, resulting in 250MB file in size. There were no other downloads happening outside of this. I assume this request does not overload the server.

**Comment by sfc-gh-sfan** [comment]
Do you have some local setup that might have killed TCP connections? Based on my understanding `ECONNRESET` is a TCP level connection failure, which does not have much to do with the connector.

**Comment by sfc-gh-dszmolka** [comment]
as mentioned previously, the connection reset has likely nothing to do with the Python Connector. if you still believe it needs to be addressed on the driver side, please comment and we can look further.  perhaps running a packet trace (`tcpdump`, etc) while reproducing the connection reset could help provide further insights.
