### ISSUE TITLE
Binding data in type (dict) is not supported

### ISSUE THREAD

**Issue by coreyatc1** [snowflakedb/snowflake-connector-python#169]
per https://docs.snowflake.net/manuals/user-guide/python-connector-api.html
gives the example:
```
pyformat: .execute("... WHERE my_column = %(name)s", {"name": value})
```

However the (redacted) code:
```
cur.execute('''
        CREATE TEMPORARY TABLE identifier(%(temp_load)s)
        AS
       ...
        ''', { 'temp_load': os.environ['SNOWFLAKE_TEMP_SCHEMA'] + '.temp_load' })
```

gives the error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vwu320/retail_account_user_to_snowflake.py", line 296, in snowflake_etl
    ''', { 'temp_load': os.environ['SNOWFLAKE_TEMP_SCHEMA'] + '.temp_load' })
  File "/home/vwu320/retail_account_user_to_snowflake.py", line 203, in snow_exec
    snow_cursor.execute(sql, args)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/cursor.py", line 443, in execute
    processed_params = self._connection._process_params(params, self)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/connection.py", line 969, in _process_params
    errorvalue)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/errors.py", line 97, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/usr/local/lib/python3.6/site-packages/snowflake/connector/errors.py", line 73, in default_errorhandler
    done_format_msg=errorvalue.get(u'done_format_msg'))
snowflake.connector.errors.ProgrammingError: 252004: Failed processing pyformat-parameters; 255001: Binding data in type (dict) is not supported.
```

**Comment by smtakeda** [comment]
cannot reproduce it... This works:
```
conn.cursor().execute("""
create or replace table identifier(%(temp_load)s) (c1 int, c2 string)
""", {'temp_load': os.environ['SNOWFLAKE_TEMP_SCHEMA'] + '.temp_load'})
```
By any change, an array or tuple of dict is set?

**Comment by smtakeda** [comment]
```
conn.cursor().execute("""
create or replace table identifier(%(temp_load)s) (c1 int, c2 string)
""", ({'temp_load': os.environ['SNOWFLAKE_TEMP_SCHEMA'] + '.temp_load'}, ))
conn.close()
```
```
Traceback (most recent call last):
  File "/tmp/b.py", line 28, in <module>
    """, ({'temp_load': os.environ['SNOWFLAKE_TEMP_SCHEMA'] + '.temp_load'}, ))
  File "/tmp/p/lib64/python3.4/site-packages/snowflake/connector/cursor.py", line 443, in execute
    processed_params = self._connection._process_params(params, self)
  File "/tmp/p/lib64/python3.4/site-packages/snowflake/connector/connection.py", line 969, in _process_params
    errorvalue)
  File "/tmp/p/lib64/python3.4/site-packages/snowflake/connector/errors.py", line 97, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/tmp/p/lib64/python3.4/site-packages/snowflake/connector/errors.py", line 73, in default_errorhandler
    done_format_msg=errorvalue.get(u'done_format_msg'))
snowflake.connector.errors.ProgrammingError: 252004: None: Failed processing pyformat-parameters; 255001: None: Binding data in type (dict) is not supported.
```

**Comment by coreyatc1** [comment]
> cannot reproduce it... This works:
> 
> ```
> conn.cursor().execute("""
> create or replace table identifier(%(temp_load)s) (c1 int, c2 string)
> """, {'temp_load': os.environ['SNOWFLAKE_TEMP_SCHEMA'] + '.temp_load'})
> ```
> By any change, an array or tuple of dict is set?

The cursor was created with DictCursor, if that's what you're asking:
```
    snow_conn = snowflake.connector.connect(
                    user = ...,
                    password = decrypt(...),
                    account = ...,
                    role = ...,
                    warehouse = ...,
                    database = ...,
                    schema = ...,
                    autocommit = False,
                    validate_default_parameters = True,
                    )

    snow_cursor = snow_conn.cursor(snowflake.connector.DictCursor)
```

**Comment by coreyatc1** [comment]
Your question led me to the answer, it was a variable coercion error on my part.
