### ISSUE TITLE
Python 3.12: ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by hugovk** [snowflakedb/snowflake-connector-python#1727]
### Python version

Python 3.12.0rc2 (v3.12.0rc2:40913a56ed, Sep  5 2023, 20:28:55) [Clang 13.0.0 (clang-1300.0.29.30)]

### Operating system and processor architecture

macOS-13.5.2-arm64-arm-64bit

### Installed packages

```python
n/a, using tox:


❯ tox --version
4.11.1 from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tox/__init__.py
```

### What did you do?

```python
The [second and final Python 3.12 release candidate](https://discuss.python.org/t/python-3-12-0rc2-final-release-candidate-released/33105/5?u=hugovk) is out! :rocket:
The [second and final Python 3.12 release candidate](https://discuss.python.org/t/python-3-12-0rc2-final-release-candidate-released/33105/5?u=hugovk) is out! :rocket:

> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.

The full release is expected in 3 weeks: 2023-10-02

See also https://dev.to/hugovk/help-test-python-312-beta-1508/

---

However, when adding `py312` to `tox.ini`, it fails with:



❯ tox -e py312
ROOT: will run in automatically provisioned tox, host /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 is missing [requires (has)]: tox-external-wheels>=0.1.6
ROOT: provision> .tox/.tox/bin/python -m tox -e py312
GLOB sdist-make: /private/tmp/snowflake-connector-python/setup.py
py312 inst-nodeps: /private/tmp/snowflake-connector-python/.tox/.tmp/package/1/snowflake-connector-python-3.2.0.zip
ERROR: invocation failed (exit code 1), logfile: /private/tmp/snowflake-connector-python/.tox/py312/log/py312-3.log
===================================================================================================== log start =====================================================================================================
Processing ./.tox/.tmp/package/1/snowflake-connector-python-3.2.0.zip
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [140 lines of output]
      Collecting setuptools>=40.6.0
        Using cached setuptools-68.2.1-py3-none-any.whl (807 kB)
      Collecting wheel
        Using cached wheel-0.41.2-py3-none-any.whl (64 kB)
      Collecting cython
        Using cached Cython-3.0.2-py2.py3-none-any.whl (1.2 MB)
      Collecting pyarrow<10.1.0,>=10.0.1
        Using cached pyarrow-10.0.1.tar.gz (994 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'error'
        error: subprocess-exited-with-error

        × pip subprocess to install build dependencies did not run successfully.
        │ exit code: 2
        ╰─> [115 lines of output]
            Collecting cython>=0.29.22
              Using cached Cython-3.0.2-py2.py3-none-any.whl (1.2 MB)
            Collecting oldest-supported-numpy>=0.14
              Using cached oldest_supported_numpy-2023.8.3-py3-none-any.whl (4.8 kB)
            Collecting setuptools_scm
              Using cached setuptools_scm-7.1.0-py3-none-any.whl (43 kB)
            Collecting setuptools>=40.1.0
              Using cached setuptools-68.2.1-py3-none-any.whl (807 kB)
            Collecting wheel
              Using cached wheel-0.41.2-py3-none-any.whl (64 kB)
            Collecting numpy (from oldest-supported-numpy>=0.14)
              Using cached numpy-1.25.2.tar.gz (10.8 MB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
            ERROR: Exception:
            Traceback (most recent call last):
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
                status = run_func(*args)
                         ^^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
                return func(self, options, args)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 377, in run
                requirement_set = resolver.resolve(
                                  ^^^^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
                result = self._result = resolver.resolve(
                                        ^^^^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
                state = resolution.resolve(requirements, max_rounds=max_rounds)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 427, in resolve
                failure_causes = self._attempt_to_pin_criterion(name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 239, in _attempt_to_pin_criterion
                criteria = self._get_updated_criteria(candidate)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 230, in _get_updated_criteria
                self._add_to_criteria(criteria, requirement, parent=candidate)
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
                if not criterion.candidates:
                       ^^^^^^^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
                return bool(self._sequence)
                       ^^^^^^^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
                return any(self)
                       ^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
                return (c for c in iterator if id(c) not in self._incompatible_ids)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
                candidate = func()
                            ^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
                self._link_candidate_cache[link] = LinkCandidate(
                                                   ^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
                super().__init__(
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
                self.dist = self._prepare()
                            ^^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
                dist = self._prepare_distribution()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
                return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
                return self._prepare_linked_requirement(req, parallel_builds)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 631, in _prepare_linked_requirement
                dist = _get_prepared_distribution(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
                abstract_dist.prepare_distribution_metadata(
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 48, in prepare_distribution_metadata
                self._install_build_reqs(finder)
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 118, in _install_build_reqs
                build_reqs = self._get_build_requires_wheel()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 95, in _get_build_requires_wheel
                return backend.get_requires_for_build_wheel()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_internal/utils/misc.py", line 692, in get_requires_for_build_wheel
                return super().get_requires_for_build_wheel(config_settings=cs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
                return self._call_hook('get_requires_for_build_wheel', {
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
                raise BackendUnavailable(data.get('traceback', ''))
            pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
              File "/private/tmp/snowflake-connector-python/.tox/py312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
                obj = import_module(mod_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^
              File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
                return _bootstrap._gcd_import(name[level:], package, level)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
              File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
              File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
              File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
              File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
              File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
              File "<frozen importlib._bootstrap_external>", line 994, in exec_module
              File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
              File "/private/var/folders/c8/hl_96fcs0hjgr29njx33x20c0000gn/T/pip-build-env-qmktp7lf/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 10, in <module>
                import distutils.core
            ModuleNotFoundError: No module named 'distutils'

            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error

      × pip subprocess to install build dependencies did not run successfully.
      │ exit code: 2
      ╰─> See above for output.

      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

====================================================================================================== log end ======================================================================================================
______________________________________________________________________________________________________ summary ______________________________________________________________________________________________________
ERROR:   py312: InvocationError for command /private/tmp/snowflake-connector-python/.tox/py312/bin/python -m pip install -U --no-deps -U '/private/tmp/snowflake-connector-python/.tox/.tmp/package/1/snowflake-connector-python-3.2.0.zip[development]' (exited with code 1)


---

This will be due to the `distutils` changes in Python 3.12:

https://docs.python.org/3.12/whatsnew/3.12.html#ensurepip
```

### What did you expect to see?

Tests passed.

### Can you set logging to DEBUG and collect the logs?

```bash
n/a
```

**Comment by sfc-gh-mkeller** [comment]
@sfc-gh-aalam if you have time this week (or someone else before 3.12 releases), we should switch to `setuptools` instead of `distutils`.

**Comment by sodul** [comment]
I do not know if this requires a separate report but the pyarrow version (v10) requested in pyproject.toml is incompatible with Python 3.12. The only version compatible is v14 so in order to make the snowflake connector compatible it needs to be updated to allow pyarrow>=14.

**Comment by sfc-gh-achandrasekaran** [comment]
@sodul the latest connector release gets rid of the dependency on a particular pyarrow version. Please try it out

**Comment by sodul** [comment]
@sfc-gh-achandrasekaran thanks, this works well now.

**Comment by sfc-gh-aalam** [comment]
@sodul I'm closing this issue. please reopen if you find it necessary
