### ISSUE TITLE
JDBC driver not able to connect to Snowflake. Error code: 390100, Message: Incorrect username or password was specified

### ISSUE THREAD

**Issue by devesh27** [snowflakedb/snowflake-connector-python#176]
Hey there I am able to connect to snowflake using python JDBC driver but not able to do same with pyspark in jupyter notebook?Already confirmed correctness of my username and password.
Also used package option and jar option in .\bin\pyspark --packages .. but no success.
Is it some kind of version issue,any leads?
**Environment details :-**
    windows 10
    python 3.6.6(jupyter notebook)
    spark 2.4.3
    snowflake-jdbc 3.8.1
    spark-snowflake_2.11-2.4.13-spark_2.4
 snowflake server version :- 3.26.1
[community.snowflake question](https://community.snowflake.com/s/question/0D50Z00009DoRXlSAN/how-to-solve-py4jjavaerror-an-error-occurred-while-calling-o37load-netsnowflakeclientjdbcsnowflakesqlexception-jdbc-driver-not-able-to-connect-to-snowflake-error-code-390100-message-incorrect-username-or-password-was-specified?t=1559024924205)
**code :-**
```import pyspark
import numpy as np
from pyspark import SparkContext
from pyspark.conf import SparkConf
from pyspark.sql import SQLContext
conf = (SparkConf().setAppName("spark_data_loader").setMaster("local"))
sc = SparkContext(conf=conf).getOrCreate()
sqlContext = SQLContext(sc)

sfOptions = {
  "sfURL" : "<account_name>.snowflakecomputing.com",
  "sfAccount" : "<account_name>",
  "sfRole" : "<user_role_name>",
  "sfUser" : "<user_name>",
  "sfPassword" : "<password>",
  "sfDatabase" : "<database>",
  "sfSchema" : "<schema>",
  "sfWarehouse" : "<warehouse>",
}
df = spark.read.format(SNOWFLAKE_SOURCE_NAME)
  .options(**sfOptions)
  .option("query",  'select *  from "<database>"."<schema>"."<table>"')
  .load()
df.show() ```

**Error stacktrace :-**

``` net.snowflake.client.jdbc.SnowflakeSQLException: JDBC driver not able to connect to Snowflake. Error code: 390100, Message: Incorrect username or password was specified..
  at net.snowflake.client.core.SessionUtil.newSession(SessionUtil.java:592)
  at net.snowflake.client.core.SessionUtil.openSession(SessionUtil.java:267)
  at net.snowflake.client.core.SFSession.open(SFSession.java:462)
  at net.snowflake.client.jdbc.SnowflakeConnectionV1.<init>(SnowflakeConnectionV1.java:131)
  at net.snowflake.client.jdbc.SnowflakeDriver.connect(SnowflakeDriver.java:148)
  at java.sql.DriverManager.getConnection(DriverManager.java:664)
  at java.sql.DriverManager.getConnection(DriverManager.java:208)
  at net.snowflake.spark.snowflake.JDBCWrapper.getConnector(SnowflakeJDBCWrapper.scala:180)
  at net.snowflake.spark.snowflake.SnowflakeRelation$$anonfun$schema$1.apply(SnowflakeRelation.scala:56)
  at net.snowflake.spark.snowflake.SnowflakeRelation$$anonfun$schema$1.apply(SnowflakeRelation.scala:53)
  at scala.Option.getOrElse(Option.scala:121)
  at net.snowflake.spark.snowflake.SnowflakeRelation.schema$lzycompute(SnowflakeRelation.scala:53)
  at net.snowflake.spark.snowflake.SnowflakeRelation.schema(SnowflakeRelation.scala:52)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:403)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)
  ... 39 elided
```

**Comment by smtakeda** [comment]
Please file an issue at https://github.com/snowflakedb/spark-snowflake/ for Spark Connector issue.
