### ISSUE TITLE
SNOW-970685: [Bug] Connection Error when I used the account name + region as the argument of param `account` in `snowflake.connector.connect()`.

### ISSUE THREAD

**Issue by jacklanda** [snowflakedb/snowflake-connector-python#1805]
### Python version

Python 3.10.13 (main, Sep 11 2023, 08:39:02) [Clang 14.0.6 ]

### Operating system and processor architecture

macOS-10.16-x86_64-i386-64bit

### Installed packages

```python
aiofiles==22.1.0
aiohttp==3.8.6
aiosignal==1.3.1
aiosqlite==0.19.0
albumentations==1.3.1
annotated-types==0.6.0
anyio==4.0.0
appdirs==1.4.4
appnope==0.1.3
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asn1crypto==1.5.1
asttokens==2.4.0
async-lru==2.0.4
async-timeout==4.0.3
attrs==23.1.0
auth0-python==4.4.2
autopep8==2.0.4
awscli==1.29.69
Babel==2.13.0
backcall==0.2.0
bcrypt==4.0.1
beautifulsoup4==4.12.2
bleach==6.1.0
boto3==1.28.63
botocore==1.31.69
braceexpand==0.1.7
-e git+https://github.com/breezeml/breezeml-sdk.git@8216a2c84a753366f307d3ba1839a71885b98c92#egg=breezeml
cachetools==5.3.1
cattrs==23.1.2
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==2.1.1
click==8.1.7
clip-benchmark==1.5.0
cognite_jupyterlab_theme==3.5.2
colorama==0.4.4
comm==0.1.4
configparser==6.0.0
contourpy==1.1.1
cryptography==40.0.2
cycler==0.12.1
dataclasses==0.6
datasets==2.14.6
debugpy==1.8.0
decorator==5.1.1
defusedxml==0.7.1
dill==0.3.7
docker==6.1.3
docker-pycreds==0.4.0
docstring-to-markdown==0.13
docutils==0.16
entrypoints==0.4
exceptiongroup==1.1.3
executing==2.0.0
ExifRead-nocycle==3.0.1
fastjsonschema==2.18.1
filelock==3.12.4
fire==0.4.0
fonttools==4.43.1
fqdn==1.5.1
frozenlist==1.4.0
fsspec==2023.10.0
ftfy==6.1.1
future==0.18.3
gitdb==4.0.10
GitPython==3.1.40
google-auth==2.23.3
greenlet==3.0.0
huggingface-hub==0.19.0
idna==3.4
imageio==2.31.6
imagenetv2-pytorch @ git+https://github.com/modestyachts/ImageNetV2_pytorch@14d4456c39fe7f02a665544dd9fc37c1a5f8b635
img2dataset==1.42.0
iniconfig==2.0.0
ipykernel==6.25.2
ipython==8.16.1
ipython-genutils==0.2.0
ipywidgets==8.1.1
isoduration==20.11.0
jedi==0.19.1
jedi-language-server==0.41.1
Jinja2==3.1.2
jmespath==1.0.1
joblib==1.3.2
json5==0.9.14
jsonpointer==2.4
jsonschema==4.19.1
jsonschema-specifications==2023.7.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.8.0
jupyter-lsp==2.2.0
jupyter-ydoc==0.2.5
jupyter_client==7.4.9
jupyter_core==5.4.0
jupyter_server==2.8.0
jupyter_server_fileid==0.9.0
jupyter_server_terminals==0.4.4
jupyter_server_ydoc==0.8.0
jupyterlab==3.6.6
jupyterlab-gruvbox-dark==0.1.0
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.9
jupyterlab_server==2.25.0
jupyterthemes==0.20.0
kaggle==1.5.16
kiwisolver==1.4.5
kubernetes==28.1.0
lazy_loader==0.3
lesscpy==0.15.1
littleutils==0.2.2
lsprotocol==2023.0.0b1
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.8.0
matplotlib-inline==0.1.6
mdurl==0.1.2
mistune==3.0.2
mpmath==1.3.0
multidict==6.0.4
multiprocess==0.70.15
nbclassic==1.0.0
nbclient==0.8.0
nbconvert==7.9.2
nbformat==5.9.2
nest-asyncio==1.5.8
networkx==3.2
notebook==6.5.6
notebook_shim==0.2.3
numpy==1.26.0
oauthlib==3.2.2
ogb==1.3.6
-e git+https://github.com/breezeml/workflow-gallery.git@9ab14cdfb95944c9cd1dc79f974d9fcb7f61c0c4#egg=open_clip_torch&subdirectory=workflow_gallery/open_clip/open_clip
opencv-python-headless==4.8.1.78
oscrypto==1.3.0
outdated==0.2.2
overrides==7.4.0
packaging==23.2
pandas==1.5.3
pandocfilters==1.5.0
paramiko==2.12.0
parso==0.8.3
pathtools==0.1.2
pexpect==4.8.0
pick==2.2.0
pickleshare==0.7.5
Pillow==10.0.1
platformdirs==3.11.0
pluggy==1.3.0
ply==3.11
prometheus-client==0.17.1
promise==2.3
prompt-toolkit==3.0.39
protobuf==3.20.3
psutil==5.9.5
ptpython==3.0.23
ptyprocess==0.7.0
pudb==2023.1
pure-eval==0.2.2
pyarrow==10.0.1
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycocoevalcap==1.2
pycocotools==2.0.7
pycodestyle==2.11.1
pycparser==2.21
pycryptodomex==3.19.0
pydantic==1.10.13
pydantic_core==2.10.1
pygls==1.1.1
Pygments==2.16.1
PyHive==0.7.0
PyJWT==2.8.0
PyNaCl==1.5.0
pyOpenSSL==23.2.0
pyparsing==3.1.1
pytest==7.2.0
pytest-split==0.8.0
python-dateutil==2.8.2
python-json-logger==2.0.7
python-slugify==8.0.1
pytz==2023.3.post1
PyYAML==6.0.1
pyzmq==24.0.1
qtconsole==5.4.4
QtPy==2.4.0
qudida==0.0.4
referencing==0.30.2
regex==2023.10.3
requests==2.31.0
requests-oauthlib==1.3.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.6.0
rpds-py==0.10.6
rsa==4.7.2
ruff==0.1.3
s3transfer==0.7.0
safetensors==0.4.0
scaleapi==2.15.0
scikit-image==0.22.0
scikit-learn==1.3.2
scipy==1.11.3
scp==0.14.5
Send2Trash==1.8.2
sentencepiece==0.1.99
sentry-sdk==1.32.0
setproctitle==1.3.3
shortuuid==1.0.11
six==1.16.0
smmap==5.0.1
sniffio==1.3.0
snowflake-connector-python==3.0.2
sortedcontainers==2.4.0
soupsieve==2.5
SQLAlchemy==2.0.22
sqlglot==18.12.0
stack-data==0.6.3
sympy==1.12
termcolor==2.3.0
terminado==0.17.1
text-unidecode==1.3
threadpoolctl==3.2.0
tifffile==2023.9.26
timm==0.9.8
tinycss2==1.2.1
tokenizers==0.14.1
tomli==2.0.1
tomlkit==0.12.1
torch==2.1.0
torchvision==0.16.0
tornado==6.3.3
tqdm==4.66.1
traitlets==5.11.2
transformers==4.34.1
typeguard==3.0.2
types-python-dateutil==2.8.19.14
typing_extensions==4.8.0
tzdata==2023.3
uri-template==1.3.0
urllib3==1.26.17
urwid==2.2.3
urwid-readline==0.13
wandb==0.15.12
wcwidth==0.2.8
webcolors==1.13
webdataset==0.2.62
webencodings==0.5.1
websocket-client==1.6.4
widgetsnbextension==4.0.9
wilds==2.0.0
xgboost==2.0.1
xxhash==3.4.1
y-py==0.6.2
yarl==1.9.2
ypy-websocket==0.8.4
```

### What did you do?

```python
### Issue
Why I get failed result when try to connect to snowflake using `account + region` as the argument of parameter?

Note that I could connect successfully with only `account name` as the argument.

### Error Message
I got this error message when use `account + region` as the argument of parameter of `snowflake.connector.connect()`.

Traceback (most recent call last):
  File "/Users/jacklanda/Desktop/BreezeML/workspace/test/test-sf-conn.py", line 4, in <module>
    conn = snowflake.connector.connect(
  File "/Users/jacklanda/opt/anaconda3/envs/breezeml-sdk/lib/python3.10/site-packages/snowflake/connector/__init__.py", line 51, in Connect
    return SnowflakeConnection(**kwargs)
  File "/Users/jacklanda/opt/anaconda3/envs/breezeml-sdk/lib/python3.10/site-packages/snowflake/connector/connection.py", line 304, in __init__
    self.connect(**kwargs)
  File "/Users/jacklanda/opt/anaconda3/envs/breezeml-sdk/lib/python3.10/site-packages/snowflake/connector/connection.py", line 575, in connect
    self.__open_connection()
  File "/Users/jacklanda/opt/anaconda3/envs/breezeml-sdk/lib/python3.10/site-packages/snowflake/connector/connection.py", line 845, in __open_connection
    self.authenticate_with_retry(self.auth_class)
  File "/Users/jacklanda/opt/anaconda3/envs/breezeml-sdk/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1105, in authenticate_with_retry
    self._authenticate(auth_instance)
  File "/Users/jacklanda/opt/anaconda3/envs/breezeml-sdk/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1131, in _authenticate
    auth.authenticate(
  File "/Users/jacklanda/opt/anaconda3/envs/breezeml-sdk/lib/python3.10/site-packages/snowflake/connector/auth/_auth.py", line 259, in authenticate
    raise err.__class__(
snowflake.connector.errors.ForbiddenError: 250001 (08001): Failed to connect to DB. Verify the account name is correct: ACCOUNT.REGION.snowflakecomputing.com:443. 000403: HTTP 403: Forbidden
```

### Expected Behaviors
- It should connect successfully with the setting `account + region`
- also, it can connect successfully with the setting `account`

### Test Example
```python3
conn = snowflake.connector.connect(
    user=f"{USERNAME}",
    password=f"{PASSWORD}",
    account=f"{ACCOUNT}.{REGION}",  # it should work whatever f"{ACCOUNT}.{REGION}" or f"{ACCOUNT}"
    warehouse=f"{WAREHOUSE}",
)
```

**Comment by sfc-gh-aling** [comment]
hey @jacklanda , sorry about the late response. are you still encountering the issue. as the error described `Verify the account name is correct: ACCOUNT.REGION.snowflakecomputing.com:443. 000403: HTTP 403: Forbidden`. I'm wondering are you putting the correct region information?


our connector takes `region` as part of the config: https://github.com/snowflakedb/snowflake-connector-python/blob/main/src/snowflake/connector/connection.py#L167

and internally we concatenate the string like your did: https://github.com/snowflakedb/snowflake-connector-python/blob/main/src/snowflake/connector/util_text.py#L243

```python
def construct_hostname(region: str | None, account: str) -> str:
    """Constructs hostname from region and account."""
    if region == "us-west-2":
        region = ""
    if region:
        if account.find(".") > 0:
            account = account[0 : account.find(".")]
        host = f"{account}.{region}.snowflakecomputing.com"
    else:
        host = f"{account}.snowflakecomputing.com"
    return host
```

**Comment by jacklanda** [comment]
Thanks for helping! According to your suggestion, I fixed this issue successfully!
