### ISSUE TITLE
Using the API with VPN, and `insecure_mode` option

### ISSUE THREAD

**Issue by teizenman** [snowflakedb/snowflake-connector-python#227]
I'm trying to use the API through VPN, and it does not work, i'm receiving the following stack trace:
```
Traceback (most recent call last):
  File "~/PycharmProjects/ustam/main.py", line 10, in <module>
    insecure_mode=True,
  File "~/PycharmProjects/ustam/venv/lib/python2.7/site-packages/snowflake/connector/__init__.py", line 33, in Connect
    return SnowflakeConnection(**kwargs)
  File "~/PycharmProjects/ustam/venv/lib/python2.7/site-packages/snowflake/connector/connection.py", line 187, in __init__
    self.connect(**kwargs)
  File "~/PycharmProjects/ustam/venv/lib/python2.7/site-packages/snowflake/connector/connection.py", line 484, in connect
    self.__open_connection()
  File "~/PycharmProjects/ustam/venv/lib/python2.7/site-packages/snowflake/connector/connection.py", line 702, in __open_connection
    self.__authenticate(auth_instance)
  File "~/PycharmProjects/ustam/venv/lib/python2.7/site-packages/snowflake/connector/connection.py", line 933, in __authenticate
    session_parameters=self._session_parameters,
  File "~/PycharmProjects/ustam/venv/lib/python2.7/site-packages/snowflake/connector/auth.py", line 197, in authenticate
    socket_timeout=self._rest._connection.login_timeout)
  File "~/PycharmProjects/ustam/venv/lib/python2.7/site-packages/snowflake/connector/network.py", line 533, in _post_request
    _include_retry_params=_include_retry_params)
  File "~/PycharmProjects/ustam/venv/lib/python2.7/site-packages/snowflake/connector/network.py", line 612, in fetch
    **kwargs)
  File "~/PycharmProjects/ustam/venv/lib/python2.7/site-packages/snowflake/connector/network.py", line 714, in _request_exec_wrapper
    raise e
snowflake.connector.errors.OperationalError: 250003: Failed to get the response. Hanging? method: post, url: <URL>
```

1. What version of Python are you using (`python --version`)? 
2.7

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)? 
Darwin-18.7.0-x86_64-i386-64bit

3. What are the component versions in the environment (`pip list`)? 
```
asn1crypto                 1.2.0   
azure-common               1.1.23  
azure-nspkg                3.0.2   
azure-storage-blob         2.1.0   
azure-storage-common       2.1.0   
azure-storage-nspkg        3.1.0   
boto3                      1.10.8  
botocore                   1.13.8  
certifi                    2019.3.9
cffi                       1.13.1  
chardet                    3.0.4   
cryptography               2.8     
docutils                   0.15.2  
duo-client                 4.2.3   
enum34                     1.1.6   
future                     0.18.2  
futures                    3.3.0   
idna                       2.8     
ijson                      2.5.1   
ipaddress                  1.0.23  
jmespath                   0.9.4   
oscrypto                   1.1.0   
pip                        19.1.1  
pyasn1                     0.4.7   
pyasn1-modules             0.2.7   
pycparser                  2.19    
pycryptodomex              3.9.1   
PyJWT                      1.7.1   
pyOpenSSL                  19.0.0  
python-dateutil            2.8.1   
pytz                       2019.3  
requests                   2.22.0  
s3transfer                 0.2.1   
setuptools                 41.0.1  
six                        1.12.0  
snowflake                  0.0.3   
snowflake-connector-python 2.0.3   
urllib3                    1.24.3  
wheel                      0.33.4 
```

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```
#!/usr/bin/env python
import snowflake.connector

# Gets the version
ctx = snowflake.connector.connect(
    user='<USER>',
    password='<PASSWORD>',
    account='<ACCOUNT>',
    # protocol='http',
    insecure_mode=True,
    )
cs = ctx.cursor()
try:
    cs.execute("SELECT current_version()")
    one_row = cs.fetchone()
    print(one_row)
except:
    print('caught')
finally:
    cs.close()
ctx.close()
```

5. What did you expect to see?
`3.49.2`

6. What did you see instead?
Nothing

I saw that there's an `insecure_mode` option in the connection, but it doesn't seem to change.
What is the best way to go on forward with it?

**Comment by snowstakeda** [comment]
Please use `snowcd` to check the network connectivity.
https://docs.snowflake.net/manuals/user-guide/ecosystem-diagnose-connectivity-issues.html
Looks like Snowflake endpoint is not whitelisted.

**Comment by teizenman** [comment]
Hi @snowstakeda , I used the tool as you mentioned, and I received the following message:
`Performing 33 checks for 13 hosts
All checks passed`
Other than that, I am able to connect to the UI successfully.
All of the above are obviously done through the VPN.

Any other way you think I can troubleshoot the issue?

**Comment by smtakeda** [comment]
Can you please reach out the customer support?
We need to take a look at the log. Thanks.

**Comment by MrDopey** [comment]
I found more information by enabling the logs
https://docs.snowflake.com/en/user-guide/python-connector-example.html#logging
