### ISSUE TITLE
Occasional sslv3 bad record mac error

### ISSUE THREAD

**Issue by zoltan-fedor** [snowflakedb/snowflake-connector-python#232]
We are seeing random `sslv3 bad record mac error` errors in some long running machine learning jobs using Snowflake to retrieve data at different parts of the job.

Below are the details.

```
$ python3.6 --version
Python 3.6.8
```

```
$ python -c 'import platform; print(platform.platform())'
Linux-3.10.0-957.21.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
```

```
$ pip list
alembic (1.0.8)
amqp (2.4.2)
asn1crypto (0.24.0)
azure-common (1.1.18)
azure-storage-blob (1.5.0)
azure-storage-common (1.4.0)
billiard (3.6.0.0)
blinker (1.4)
boto (2.49.0)
boto3 (1.9.128)
botocore (1.12.128)
bz2file (0.98)
celery (4.3.0)
certifi (2019.3.9)
cffi (1.12.2)
chardet (3.0.4)
Click (7.0)
coverage (4.5.3)
cryptography (2.6.1)
cx-Oracle (7.1.2)
Cython (0.29.6)
docutils (0.14)
Flask (1.0.2)
Flask-Cache (0.13.1)
Flask-Caching (1.7.0)
Flask-Cors (3.0.7)
Flask-DebugToolbar (0.10.1)
Flask-Excel (0.0.7)
Flask-HTTPAuth (3.2.4)
Flask-JWT-Extended (3.18.0)
Flask-Limiter (1.0.1)
Flask-Login (0.4.1)
Flask-Mail (0.9.1)
flask-marshmallow (0.10.0)
Flask-Migrate (2.4.0)
Flask-Moment (0.7.0)
Flask-Script (2.0.6)
Flask-SQLAlchemy (2.4.0)
Flask-WTF (0.14.2)
future (0.17.1)
gensim (3.4.0)
idna (2.8)
ijson (2.3)
itsdangerous (1.1.0)
Jinja2 (2.10)
jmespath (0.9.4)
kombu (4.5.0)
limits (1.3)
lml (0.0.9)
logaugment (0.1.3)
Mako (1.0.8)
MarkupSafe (1.1.1)
marshmallow (2.19.2)
marshmallow-sqlalchemy (0.16.1)
nltk (3.2.5)
numpy (1.16.2)
pip (9.0.1)
pipenv (2018.11.26)
pycparser (2.19)
pycryptodomex (3.8.0)
pyexcel (0.5.13)
pyexcel-io (0.5.16)
pyexcel-webio (0.1.4)
PyJWT (1.7.1)
PyMySQL (0.9.3)
pyOpenSSL (19.0.0)
Pyro4 (4.75)
python-dateutil (2.8.0)
python-dotenv (0.10.1)
python-editor (1.0.4)
pytz (2018.9)
redis (3.2.1)
requests (2.21.0)
s3transfer (0.2.0)
scipy (1.2.1)
serpent (1.28)
setuptools (39.0.1)
six (1.12.0)
smart-open (1.8.0)
snowflake-connector-python (1.7.9)
snowflake-sqlalchemy (1.1.11)
SQLAlchemy (1.2.17)
texttable (1.6.1)
ujson (1.35)
urllib3 (1.24.1)
uWSGI (2.0.18)
vine (1.3.0)
virtualenv (16.7.4)
virtualenv-clone (0.5.3)
Werkzeug (0.15.2)
WTForms (2.2.1)
```

The error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/snowflake/connector/ssl_wrap_socket.py", line 218, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/OpenSSL/SSL.py", line 1822, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib64/python3.6/site-packages/OpenSSL/SSL.py", line 1622, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/pool.py", line 742, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/pool.py", line 929, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 486, in do_rollback
    dbapi_connection.rollback()
  File "/usr/lib/python3.6/site-packages/snowflake/connector/connection.py", line 508, in rollback
    self.cursor().execute("ROLLBACK")
  File "/usr/lib/python3.6/site-packages/snowflake/connector/cursor.py", line 480, in execute
    _is_put_get=_is_put_get)
  File "/usr/lib/python3.6/site-packages/snowflake/connector/cursor.py", line 369, in _execute_helper
    _no_results=_no_results)
  File "/usr/lib/python3.6/site-packages/snowflake/connector/connection.py", line 785, in cmd_query
    _include_retry_params=True)
  File "/usr/lib/python3.6/site-packages/snowflake/connector/network.py", line 313, in request
    timeout=timeout, _include_retry_params=_include_retry_params)
  File "/usr/lib/python3.6/site-packages/snowflake/connector/network.py", line 530, in _post_request
    _include_retry_params=_include_retry_params)
  File "/usr/lib/python3.6/site-packages/snowflake/connector/network.py", line 608, in fetch
    **kwargs)
  File "/usr/lib/python3.6/site-packages/snowflake/connector/network.py", line 685, in _request_exec_wrapper
    raise e
  File "/usr/lib/python3.6/site-packages/snowflake/connector/network.py", line 648, in _request_exec_wrapper
    **kwargs)
  File "/usr/lib/python3.6/site-packages/snowflake/connector/network.py", line 873, in _request_exec
    raise err
  File "/usr/lib/python3.6/site-packages/snowflake/connector/network.py", line 776, in _request_exec
    auth=SnowflakeAuth(token),
  File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/site-packages/snowflake/connector/ssl_wrap_socket.py", line 234, in recv_into
    return self.recv_into(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/snowflake/connector/ssl_wrap_socket.py", line 218, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/OpenSSL/SSL.py", line 1822, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib64/python3.6/site-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib64/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert bad record mac')]
```

**Comment by snowstakeda** [comment]
not sure the cause. Need investigation.
