### ISSUE TITLE
AWS SAM cannot find snowflake-connector-python wheel

### ISSUE THREAD

**Issue by n-batalha** [snowflakedb/snowflake-connector-python#261]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?

AWS Lambda 3.7 runtime

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

AWS Lambda

3. What are the component versions in the environment (`pip list`)? 

```
asn1crypto==1.3.0
azure-common==1.1.24
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
boto3==1.11.9
botocore==1.14.9
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
cryptography==2.8
docutils==0.15.2
idna==2.8
ijson==2.6.0
jmespath==0.9.4
oscrypto==1.2.0
pycparser==2.19
pycryptodomex==3.9.4
pyjwt==1.7.1
pyopenssl==19.1.0
python-dateutil==2.8.1
pytz==2019.3
requests==2.22.0
s3transfer==0.3.2
sentry-sdk==0.14.1
six==1.14.0
snowflake-connector-python==2.2.0
urllib3==1.25.8
```

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

`sam build`

5. What did you expect to see?

Exit without errors

6. What did you see instead?

```
Build Failed
Error: PythonPipBuilder:ResolveDependencies - {snowflake-connector-python==2.2.0(wheel)}
```

7. Can you set logging to DEBUG and collect the logs?

Running `run sam build --debug`

```
calling pip download -r /Users/nqb/Documents/git/s3-to-dw/upload_to_warehouse/requirements.txt --dest /var/folders/qx/wc50h91d74j_2_bx1sv2qygm0009t7/T/tmp014y48f3
Full dependency closure: {certifi==2019.11.28(wheel), snowflake-connector-python==2.2.0(wheel), azure-storage-blob==2.1.0(wheel), cffi==1.13.2(wheel), cryptography==2.8(wheel), botocore==1.14.9(wheel), sentry-sdk==0.14.1(wheel), pycparser==2.19(sdist), pycryptodomex==3.9.4(wheel), pyopenssl==19.1.0(wheel), s3transfer==0.3.2(wheel), docutils==0.15.2(wheel), urllib3==1.25.8(wheel), six==1.14.0(wheel), oscrypto==1.2.0(wheel), boto3==1.11.9(wheel), python-dateutil==2.8.1(wheel), azure-common==1.1.24(wheel), ijson==2.6.0(wheel), pyjwt==1.7.1(wheel), pytz==2019.3(wheel), jmespath==0.9.4(wheel), chardet==3.0.4(wheel), asn1crypto==1.3.0(wheel), azure-storage-common==2.1.0(wheel), requests==2.22.0(wheel), idna==2.8(wheel)}
initial compatible: {certifi==2019.11.28(wheel), azure-storage-blob==2.1.0(wheel), botocore==1.14.9(wheel), sentry-sdk==0.14.1(wheel), pyopenssl==19.1.0(wheel), s3transfer==0.3.2(wheel), docutils==0.15.2(wheel), urllib3==1.25.8(wheel), six==1.14.0(wheel), oscrypto==1.2.0(wheel), boto3==1.11.9(wheel), python-dateutil==2.8.1(wheel), azure-common==1.1.24(wheel), pyjwt==1.7.1(wheel), pytz==2019.3(wheel), jmespath==0.9.4(wheel), chardet==3.0.4(wheel), asn1crypto==1.3.0(wheel), azure-storage-common==2.1.0(wheel), requests==2.22.0(wheel), idna==2.8(wheel)}
initial incompatible: {cffi==1.13.2(wheel), cryptography==2.8(wheel), pycryptodomex==3.9.4(wheel), ijson==2.6.0(wheel), pycparser==2.19(sdist), snowflake-connector-python==2.2.0(wheel)}
Downloading missing wheels: {cffi==1.13.2(wheel), cryptography==2.8(wheel), snowflake-connector-python==2.2.0(wheel), pycryptodomex==3.9.4(wheel), ijson==2.6.0(wheel), pycparser==2.19(sdist)}
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /var/folders/qx/wc50h91d74j_2_bx1sv2qygm0009t7/T/tmp014y48f3 cffi==1.13.2
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /var/folders/qx/wc50h91d74j_2_bx1sv2qygm0009t7/T/tmp014y48f3 cryptography==2.8
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /var/folders/qx/wc50h91d74j_2_bx1sv2qygm0009t7/T/tmp014y48f3 snowflake-connector-python==2.2.0
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /var/folders/qx/wc50h91d74j_2_bx1sv2qygm0009t7/T/tmp014y48f3 pycryptodomex==3.9.4
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /var/folders/qx/wc50h91d74j_2_bx1sv2qygm0009t7/T/tmp014y48f3 ijson==2.6.0
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /var/folders/qx/wc50h91d74j_2_bx1sv2qygm0009t7/T/tmp014y48f3 pycparser==2.19
compatible wheels after second download pass: {certifi==2019.11.28(wheel), azure-storage-blob==2.1.0(wheel), cffi==1.13.2(wheel), cryptography==2.8(wheel), botocore==1.14.9(wheel), sentry-sdk==0.14.1(wheel), pycryptodomex==3.9.4(wheel), pyopenssl==19.1.0(wheel), s3transfer==0.3.2(wheel), docutils==0.15.2(wheel), urllib3==1.25.8(wheel), six==1.14.0(wheel), oscrypto==1.2.0(wheel), boto3==1.11.9(wheel), python-dateutil==2.8.1(wheel), azure-common==1.1.24(wheel), pyjwt==1.7.1(wheel), ijson==2.6.0(wheel), pytz==2019.3(wheel), jmespath==0.9.4(wheel), chardet==3.0.4(wheel), asn1crypto==1.3.0(wheel), azure-storage-common==2.1.0(wheel), requests==2.22.0(wheel), idna==2.8(wheel)}
Build missing wheels from sdists (C compiling True): {pycparser==2.19(sdist)}
calling pip wheel --no-deps --wheel-dir /var/folders/qx/wc50h91d74j_2_bx1sv2qygm0009t7/T/tmp014y48f3 /var/folders/qx/wc50h91d74j_2_bx1sv2qygm0009t7/T/tmp014y48f3/pycparser-2.19.tar.gz
compatible after building wheels (no C compiling): {certifi==2019.11.28(wheel), azure-storage-blob==2.1.0(wheel), cffi==1.13.2(wheel), cryptography==2.8(wheel), botocore==1.14.9(wheel), sentry-sdk==0.14.1(wheel), pycparser==2.19(wheel), pycryptodomex==3.9.4(wheel), pyopenssl==19.1.0(wheel), s3transfer==0.3.2(wheel), docutils==0.15.2(wheel), urllib3==1.25.8(wheel), six==1.14.0(wheel), oscrypto==1.2.0(wheel), boto3==1.11.9(wheel), python-dateutil==2.8.1(wheel), azure-common==1.1.24(wheel), pyjwt==1.7.1(wheel), ijson==2.6.0(wheel), pytz==2019.3(wheel), jmespath==0.9.4(wheel), chardet==3.0.4(wheel), asn1crypto==1.3.0(wheel), azure-storage-common==2.1.0(wheel), requests==2.22.0(wheel), idna==2.8(wheel)}
Build missing wheels from sdists (C compiling False): set()
compatible after building wheels (C compiling): {certifi==2019.11.28(wheel), azure-storage-blob==2.1.0(wheel), cffi==1.13.2(wheel), cryptography==2.8(wheel), botocore==1.14.9(wheel), sentry-sdk==0.14.1(wheel), pycparser==2.19(wheel), pycryptodomex==3.9.4(wheel), pyopenssl==19.1.0(wheel), s3transfer==0.3.2(wheel), docutils==0.15.2(wheel), urllib3==1.25.8(wheel), six==1.14.0(wheel), oscrypto==1.2.0(wheel), boto3==1.11.9(wheel), python-dateutil==2.8.1(wheel), azure-common==1.1.24(wheel), pyjwt==1.7.1(wheel), ijson==2.6.0(wheel), pytz==2019.3(wheel), jmespath==0.9.4(wheel), chardet==3.0.4(wheel), asn1crypto==1.3.0(wheel), azure-storage-common==2.1.0(wheel), requests==2.22.0(wheel), idna==2.8(wheel)}
Final compatible: {urllib3==1.25.8(wheel), six==1.14.0(wheel), certifi==2019.11.28(wheel), oscrypto==1.2.0(wheel), boto3==1.11.9(wheel), azure-storage-blob==2.1.0(wheel), python-dateutil==2.8.1(wheel), azure-common==1.1.24(wheel), pyjwt==1.7.1(wheel), ijson==2.6.0(wheel), pytz==2019.3(wheel), jmespath==0.9.4(wheel), cffi==1.13.2(wheel), cryptography==2.8(wheel), chardet==3.0.4(wheel), botocore==1.14.9(wheel), asn1crypto==1.3.0(wheel), sentry-sdk==0.14.1(wheel), pycparser==2.19(wheel), azure-storage-common==2.1.0(wheel), pycryptodomex==3.9.4(wheel), requests==2.22.0(wheel), idna==2.8(wheel), pyopenssl==19.1.0(wheel), s3transfer==0.3.2(wheel), docutils==0.15.2(wheel)}
Final incompatible: {cffi==1.13.2(wheel), cryptography==2.8(wheel), snowflake-connector-python==2.2.0(wheel), pycryptodomex==3.9.4(wheel), ijson==2.6.0(wheel)}
Final missing wheels: {snowflake-connector-python==2.2.0(wheel)}
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/Users/nqb/.local/share/virtualenvs/s3-to-dw-Y4M_h5Uv/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    requirements_path=self.manifest_path
  File "/Users/nqb/.local/share/virtualenvs/s3-to-dw-Y4M_h5Uv/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 144, in build_dependencies
    requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/Users/nqb/.local/share/virtualenvs/s3-to-dw-Y4M_h5Uv/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 213, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {snowflake-connector-python==2.2.0(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nqb/.local/share/virtualenvs/s3-to-dw-Y4M_h5Uv/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 248, in run
    action.execute()
  File "/Users/nqb/.local/share/virtualenvs/s3-to-dw-Y4M_h5Uv/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 42, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {snowflake-connector-python==2.2.0(wheel)}
```

## Note

1.9.1 does not have this issue: https://pypi.org/project/snowflake-connector-python/1.9.1/#files
2.2.0 has it and the wheels are released differently: https://pypi.org/project/snowflake-connector-python/#files

**Comment by keller00** [comment]
To me the `2.2.0` release looks right, the 1.9.1 does not.
@snowstakeda did we change how we release?

The problem must be this: `--platform manylinux1_x86_64`
We release for: `manylinux2010_x86_64`

`manylinux1_x86_64` seems to be EOL, please try to see if you could change your platform to a newer one on SAM.
I will keep looking but I don't see an obvious config option that would change your platform, but I'm not familiar with SAM.

**Comment by howryu** [comment]
Yes. `manylinux1_x86_64` is compatible with centos5, which is a really old version of centos. Either you changed upgrade your config to allow `manylinux2010` or you change to `sdist`, which only install source package and did not have any native code.

**Comment by keller00** [comment]
@n-batalha could you let us know if you were able to fix your issue with our suggestions, or if you are still having a problem?

**Comment by n-batalha** [comment]
Thank you for the prompt analysis. My understanding is that SAM just packages AWS Lambdas with other AWS resources which won't impact this. In AWS Lambda I can only upgrade to Python 3.8 https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html which we can see there uses a different "Amazon Linux 2" OS. I couldn't test this yet and just reverted the version, but logs in Google suggest this OS does not change that label:

* https://www.google.com/search?client=firefox-b-d&q=%22amazon+linux+2%22+%22manylinux1_x86_64%22
* https://www.google.com/search?client=firefox-b-d&q=%22amazon+linux+2%22+%22manylinux2010_x86_64%22

Feel free to close if you prefer, and I can reopen if Python 3.8 is confirmed not to work.
