### ISSUE TITLE
SNOW-146418: Snowflake Connector Causing Boto3 Conflicts

### ISSUE THREAD

**Issue by dudleyj2** [snowflakedb/snowflake-connector-python#290]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
3.6.5

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
AWS Lambda

3. What are the component versions in the environment (`pip list`)? 
```
boto3==1.11.17
botocore==1.14.17
snowflake-connector-python==2.2.1
++snowflake connector, boto3, botocore dependencies
```

4. What did you do?
When calling boto3 operations to S3, the snowflake connector white list is blocking the call and producing the error: 

WARNING!!! Using fail-open to connect. Driver is connecting to an HTTPS endpoint without OCSP based Certificate Revocation checking as it could not obtain a valid OCSP Response to use from the CA OCSP responder.

```
 {'eventType': 'RevocationCheckFailure', 'sfcPeerHost': '<REDACTED NAME HERE>.s3.amazonaws.com', 'certId': 'MEcwBwYFKw4DAhoEFO6ov3Yve2OQ3rtE0UX8R29Po0TMBBTAErIodGhGZ+lwJXQaAEVbBn1cRAIQCC32junGkxW+v3IHmzgQ/Q==', 'ocspRequestBase64': 'ME8wTTBLMEkwRzAHBgUrDgMCGgQU7qi/di97Y5Deu0TRRfxHb0+jRMwEFMASsih0aEZn6XAldBoARVsGfVxEAhAILfaO6caTFb6/cgebOBD9', 'ocspResponderURL': 'http://ocsp.digicert.com', 'errorMessage': "254005: None: Could not fetch OCSP Response from server. Considerchecking your whitelists : Exception - HTTPConnectionPool(host='ocsp.digicert.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd2bc8b38>: Failed to establish a new connection: [Errno -2] Name or service not known',))", 'insecureMode': False, 'failOpen': True, 'cacheEnabled': True, 'cacheHit': False, 'exceptionMessage': "254005: None: Could not fetch OCSP Response from server. Considerchecking your whitelists : Exception - HTTPConnectionPool(host='ocsp.digicert.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd2bc8b38>: Failed to establish a new connection: [Errno -2] Name or service not known',))", 'exceptionStackTrace': 'Traceback (most recent call last):\n  File "/var/task/urllib3/connection.py", line 157, in _new_conn\n    (self._dns_host, self.port), self.timeout, **extra_kw\n  File "/var/task/urllib3/util/connection.py", line 61, in create_connection\n    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n  File "/var/lang/lib/python3.6/socket.py", line 745, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -2] Name or service not known\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/var/task/urllib3/connectionpool.py", line 672, in urlopen\n    chunked=chunked,\n  File "/var/task/urllib3/connectionpool.py", line 387, in _make_request\n    conn.request(method, url, **httplib_request_kw)\n  File "/var/lang/lib/python3.6/http/client.py", line 1262, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File "/var/lang/lib/python3.6/http/client.py", line 1308, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n  File "/var/lang/lib/python3.6/http/client.py", line 1257, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File "/var/lang/lib/python3.6/http/client.py", line 1036, in _send_output\n    self.send(msg)\n  File "/var/lang/lib/python3.6/http/client.py", line 974, in send\n    self.connect()\n  File "/var/task/urllib3/connection.py", line 184, in connect\n    conn = self._new_conn()\n  File "/var/task/urllib3/connection.py", line 169, in _new_conn\n    self, "Failed to establish a new connection: %s" % e\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3fd2bc8b38>: Failed to establish a new connection: [Errno -2] Name or service not known\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/var/task/requests/adapters.py", line 449, in send\n    timeout=timeout\n  File "/var/task/urllib3/connectionpool.py", line 720, in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n  File "/var/task/urllib3/util/retry.py", line 436, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host=\'ocsp.digicert.com\', port=80): Max retries exceeded with url: / (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x7f3fd2bc8b38>: Failed to establish a new connection: [Errno -2] Name or service not known\',))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/var/task/snowflake/connector/ocsp_snowflake.py", line 1387, in _fetch_ocsp_response\n    data=payload,\n  File "/var/task/requests/sessions.py", line 533, in request\n    resp = self.send(prep, **send_kwargs)\n  File "/var/task/requests/sessions.py", line 646, in send\n    r = adapter.send(request, **kwargs)\n  File "/var/task/requests/adapters.py", line 516, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPConnectionPool(host=\'ocsp.digicert.com\', port=80): Max retries exceeded with url: / (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x7f3fd2bc8b38>: Failed to establish a new connection: [Errno -2] Name or service not known\',))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/var/task/snowflake/connector/ocsp_snowflake.py", line 1113, in validate_by_direct_connection\n    hostname, do_retry)\n  File "/var/task/snowflake/connector/ocsp_snowflake.py", line 1412, in _fetch_ocsp_response\n    errno=ER_OCSP_FAILED_TO_CONNECT_HOST)\nsnowflake.connector.errors.RevocationCheckError: 254005: None: Could not fetch OCSP Response from server. Considerchecking your whitelists : Exception - HTTPConnectionPool(host=\'ocsp.digicert.com\', port=80): Max retries exceeded with url: / (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x7f3fd2bc8b38>: Failed to establish a new connection: [Errno -2] Name or service not known\',))\n'}
```
If possible, provide a recipe for reproducing the error.
* Package includes snowflake connector and boto3
* Regular boto3 head_object call to s3 is blocked by snowflake connector's whitelist check on all s3 calls.

5. What did you expect to see? Expected to be able to call s3 with boto3 library and return object metadata, but the call is being blocked by the snowflake connector.

6. What did you see instead? Continuous reprint of above error message

7. Can you set logging to DEBUG and collect the logs?

```
import logging
import os

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']: 
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```

**Comment by dudleyj2** [comment]
https://github.com/snowflakedb/snowflake-connector-python/blob/dc31c582be713d73707331092a304928459f8411/ocsp_snowflake.py#L867

**Comment by dudleyj2** [comment]
Worked with Christ in SF Support and came up with this fix.  If you have connections to S3 outside of the snowflake connector, you need to manually import a urllib3 connection and ssl wrapper to override what the python snowflake connector is overriding, essentially to cancel it out.

```
import requests.packages.urllib3.connection as connection_
import requests.packages.urllib3.util.ssl_ as ssl_

class S3Helpers:

    @staticmethod
    def sf_connector_ssl_wrap_socket_urllib3():
        """
        Required for S3 calls using SF Connector 2.+
        """
        connection_.ssl_wrap_socket = ssl_.ssl_wrap_socket

    @staticmethod
    def get_s3_object(s3_resource, bucket, object_key):
        S3Helpers.sf_connector_ssl_wrap_socket_urllib3()
        s3_object = s3_resource.Object(bucket, object_key)
        return s3_object

```

Without overriding the call, endless OCSP warnings will happen.  This seems to be a simple trick to get it to work in case anyone else comes across this same issue.

**Comment by sfc-gh-mkeller** [comment]
Hi @dudleyj2 the plan is to build this feature into the connector natively.
Let's use this issue to track my progress on this!

**Comment by pierce-edmiston-8L** [comment]
Just wanted to say thanks for this bug report, as I ran into something similar. In my case, I have Snowflake's PrivateLink integration set up, and the `snowcd` tool reports being able to reach the OCSP cache. However, if I import `snowflake.connector`, which triggers the monkeypatching of `urllib`, then `boto3` breaks.

In my case, the solution was to define `SF_OCSP_RESPONSE_CACHE_SERVER_URL` pointing to our Snowflake account's PrivateLink OCSP URL.

```
SF_OCSP_RESPONSE_CACHE_SERVER_URL=http://ocsp.myaccount.myregion.privatelink.snowflakecomputing.com/ocsp_response_cache.json
```

It took a lot of digging to get there!

**Comment by sfc-gh-hkapre** [comment]
@sfc-gh-mkeller Have we addressed this in the driver? Can we close this out?

**Comment by sfc-gh-mkeller** [comment]
Yes @sfc-gh-hkapre we don't monkey patch our OCSP verification into the default `urllib3`, closing the ticket!
