### ISSUE TITLE
SNOW-147693: Can we call procedure from snowflake python connector ?

### ISSUE THREAD

**Issue by userx91** [snowflakedb/snowflake-connector-python#293]
1. What version of Python are you using (`python --version`)?  
3.7.6

2. What operating system and processor architecture are you using ? 
Darwin-18.7.0-x86_64-i386-64bit

3. What are the component versions in the environment (`pip list`)?  
snowflake-connector-python          2.2.2 

4. What did you do?
Tried to use the callproc() method to call a no argument procedure that I have created in my schema

5. What did you expect to see?
procedure to be executed

6. What did you see instead?
Error message stating "snowflake.connector.errors.NotSupportedError: 252008 (0A000): None: callproc is not supported."

7. Can you set logging to DEBUG and collect the logs?

Yes .. Please find the logs below

2020-03-26 00:56:54,312 - MainThread connection.py:178 - __init__() - INFO - Snowflake Connector for Python Version: 2.2.2, Python Version: 3.7.6, Platform: Darwin-18.7.0-x86_64-i386-64bit
2020-03-26 00:56:54,312 - MainThread connection.py:478 - connect() - DEBUG - connect
2020-03-26 00:56:54,312 - MainThread connection.py:714 - __config() - DEBUG - __config
2020-03-26 00:56:54,312 - MainThread connection.py:809 - __config() - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
2020-03-26 00:56:54,312 - MainThread converter.py:138 - __init__() - DEBUG - use_numpy: False
2020-03-26 00:56:54,313 - MainThread connection.py:640 - __open_connection() - DEBUG - REST API object was created: <OUR_ACCOUNT_NAME>
2020-03-26 00:56:54,313 - MainThread auth_keypair.py:92 - calculate_public_key_fingerprint() - DEBUG - Public key fingerprint is SHA256:<SHA256_FINGER_PRINT>
2020-03-26 00:56:54,315 - MainThread auth.py:120 - authenticate() - DEBUG - authenticate
2020-03-26 00:56:54,315 - MainThread auth.py:144 - authenticate() - DEBUG - assertion content: <bound method AuthByKeyPair.assertion_content of <snowflake.connector.auth_keypair.AuthByKeyPair object at 0x10d4d5790>>
2020-03-26 00:56:54,315 - MainThread auth.py:156 - authenticate() - DEBUG - account=ACCOUNT_NAME, user=USER_NAME, database=DB_NAME, schema=None, warehouse=WAREHOUSE_NAME, role=None, request_id=REQ_ID
2020-03-26 00:56:54,315 - MainThread auth.py:182 - authenticate() - DEBUG - body['data']: {'CLIENT_APP_ID': 'PythonConnector', 'CLIENT_APP_VERSION': '2.2.2', 'SVN_REVISION': None, 'ACCOUNT_NAME': 'fmrctgnonprod', 'LOGIN_NAME': 'PI_CP_DEV_BATCH_USER', 'CLIENT_ENVIRONMENT': {'APPLICATION': 'PythonConnector', 'OS': 'Darwin', 'OS_VERSION': 'Darwin-18.7.0-x86_64-i386-64bit', 'PYTHON_VERSION': '3.7.6', 'PYTHON_RUNTIME': 'CPython', 'PYTHON_COMPILER': 'Clang 11.0.0 (clang-1100.0.33.16)', 'OCSP_MODE': 'FAIL_OPEN'}, 'AUTHENTICATOR': 'SNOWFLAKE_JWT', 'TOKEN': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJGTVJDVEdOT05QUk9ELlBJX0NQX0RFVl9CQVRDSF9VU0VSLlNIQTI1NjpkMG1ldWpoYk5HTTZoVEkwM3VXL05INjBxOTVlaFZPYlkzTkk1NjZZWEdvPSIsInN1YiI6IkZNUkNUR05PTlBST0QuUElfQ1BfREVWX0JBVENIX1VTRVIiLCJpYXQiOjE1ODUxNjQ0MTQsImV4cCI6MTU4NTE2NDUzNH0.B8iCIPfe7IN1CNUZEKrFjj_0BBklbUIJwzSvKy-ALoHKFeDCXeje3rC4jMwWvHS7MbPaHds1yfTPQvvyXV5U9JA0u6Sr_UIelmPca7wZ13u_ktZRk43AQ7zPqXHfwNtM4gcOcn8K---QlxL7ikuFzuRICzxZS76QxapWjBFofDlkVj7DsmzrTVZGDzqPIgG5aP3XEPQv94NWGJSf4mtgIgIEPvBsqo3msDJYbkSwCSLuKEp7L8IwUGlH1RcfHPBMxvBEar9tU-WesOqVcUIVR1XettY1jW4VxnbZPwzz0NHhd641fzVlZLouGMoI5pW_vu9yPriBMwl2YzCLSR4B6w', 'SESSION_PARAMETERS': {'CLIENT_SESSION_KEEP_ALIVE_HEARTBEAT_FREQUENCY': 900, 'CLIENT_PREFETCH_THREADS': 4}}
2020-03-26 00:56:54,316 - MainThread network.py:931 - _use_requests_session() - DEBUG - Active requests sessions: 1, idle: 0
2020-03-26 00:56:54,316 - MainThread network.py:636 - _request_exec_wrapper() - DEBUG - remaining request timeout: 120, retry cnt: 1
2020-03-26 00:56:54,316 - MainThread network.py:775 - _request_exec() - DEBUG - socket timeout: 60
2020-03-26 00:56:55,020 - MainThread ocsp_snowflake.py:382 - reset_cache_dir() - DEBUG - cache directory: /Users/******/Library/Caches/Snowflake
2020-03-26 00:56:55,136 - MainThread ssl_wrap_socket.py:406 - ssl_wrap_socket_with_ocsp() - DEBUG - OCSP Mode: FAIL_OPEN, OCSP response cache file name: None
2020-03-26 00:56:55,136 - MainThread ocsp_snowflake.py:421 - reset_ocsp_response_cache_uri() - DEBUG - ocsp_response_cache_uri: file:///Users/*******/Library/Caches/Snowflake/ocsp_response_cache.json
2020-03-26 00:56:55,136 - MainThread ocsp_snowflake.py:423 - reset_ocsp_response_cache_uri() - DEBUG - OCSP_VALIDATION_CACHE size: 0
2020-03-26 00:56:55,136 - MainThread ocsp_snowflake.py:217 - reset_ocsp_dynamic_cache_server_url() - DEBUG - OCSP response cache server is enabled: http://ocsp.snowflakecomputing.com/ocsp_response_cache.json
2020-03-26 00:56:55,136 - MainThread ocsp_snowflake.py:251 - reset_ocsp_dynamic_cache_server_url() - DEBUG - OCSP dynamic cache server RETRY URL: None
2020-03-26 00:56:55,142 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2025-05-12 23:58:59+00:00
2020-03-26 00:56:55,143 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2023-06-11 20:40:26+00:00
2020-03-26 00:56:55,144 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2023-06-11 20:44:21+00:00
2020-03-26 00:56:55,147 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2025-05-12 23:58:59+00:00
2020-03-26 00:56:55,151 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2025-05-12 23:58:59+00:00
2020-03-26 00:56:55,152 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2025-05-12 23:58:59+00:00
2020-03-26 00:56:55,161 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2021-03-15 15:24:38+00:00
2020-03-26 00:56:55,163 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2021-03-15 15:35:39+00:00
2020-03-26 00:56:55,165 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2021-03-15 15:35:39+00:00
2020-03-26 00:56:55,167 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2021-03-15 15:24:38+00:00
2020-03-26 00:56:55,169 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2021-03-15 15:24:38+00:00
2020-03-26 00:56:55,172 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2021-03-15 15:35:39+00:00
2020-03-26 00:56:55,174 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2021-03-15 15:41:23+00:00
2020-03-26 00:56:55,176 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2021-03-15 15:41:23+00:00
2020-03-26 00:56:55,178 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2021-12-14 07:00:00+00:00
2020-03-26 00:56:55,179 - MainThread ocsp_snowflake.py:459 - read_ocsp_response_cache_file() - DEBUG - Read OCSP response cache file: /Users/********/Library/Caches/Snowflake/ocsp_response_cache.json, count=83
2020-03-26 00:56:55,179 - MainThread ocsp_snowflake.py:971 - validate() - DEBUG - validating certificate: <OUR_ACCOUNT_NAME>
2020-03-26 00:56:55,179 - MainThread ocsp_asn1crypto.py:347 - extract_certificate_chain() - DEBUG - # of certificates: 4
2020-03-26 00:56:55,180 - MainThread ocsp_asn1crypto.py:354 - extract_certificate_chain() - DEBUG - <our_cert_info>
2020-03-26 00:56:55,181 - MainThread ocsp_asn1crypto.py:354 - extract_certificate_chain() - DEBUG - <our_cert_info>
2020-03-26 00:56:55,181 - MainThread ocsp_asn1crypto.py:354 - extract_certificate_chain() - DEBUG - <our_cert_info>
2020-03-26 00:56:55,182 - MainThread ocsp_asn1crypto.py:354 - extract_certificate_chain() - DEBUG - <our_cert_info>
2020-03-26 00:56:55,184 - MainThread ocsp_asn1crypto.py:90 - read_cert_bundle() - DEBUG - reading certificate bundle: /Users/********/Projects/venv/lib/python3.7/site-packages/certifi/cacert.pem
2020-03-26 00:56:55,199 - MainThread ocsp_asn1crypto.py:376 - create_pair_issuer_subject() - DEBUG - not found issuer_der: <CERT_INFO>
2020-03-26 00:56:55,201 - MainThread ocsp_snowflake.py:587 - find_cache() - DEBUG - hit cache for subject: <CERT_INFO>
2020-03-26 00:56:55,203 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2023-06-11 20:40:26+00:00
2020-03-26 00:56:55,203 - MainThread ocsp_snowflake.py:587 - find_cache() - DEBUG - hit cache for subject: <CERT_INFO>
2020-03-26 00:56:55,205 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2023-06-11 20:44:21+00:00
2020-03-26 00:56:55,205 - MainThread ocsp_snowflake.py:587 - find_cache() - DEBUG - hit cache for subject: <CERT_INFO>
2020-03-26 00:56:55,207 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2021-12-14 07:00:00+00:00
2020-03-26 00:56:55,208 - MainThread ocsp_snowflake.py:587 - find_cache() - DEBUG - hit cache for subject: <CERT_INFO>
2020-03-26 00:56:55,209 - MainThread ocsp_snowflake.py:587 - find_cache() - DEBUG - hit cache for subject: <CERT_INFO>
2020-03-26 00:56:55,210 - MainThread ocsp_snowflake.py:1123 - validate_by_direct_connection() - DEBUG - using OCSP response cache
2020-03-26 00:56:55,210 - MainThread ocsp_asn1crypto.py:276 - process_ocsp_response() - DEBUG - Certificate is NOT attached in Basic OCSP Response. Using issuer's certificate
2020-03-26 00:56:55,210 - MainThread ocsp_asn1crypto.py:282 - process_ocsp_response() - DEBUG - Verifying the OCSP response is signed by the issuer.
2020-03-26 00:56:55,241 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2023-06-11 20:40:26+00:00
2020-03-26 00:56:55,242 - MainThread ocsp_snowflake.py:587 - find_cache() - DEBUG - hit cache for subject: <CERT_INFO>
2020-03-26 00:56:55,243 - MainThread ocsp_snowflake.py:1123 - validate_by_direct_connection() - DEBUG - using OCSP response cache
2020-03-26 00:56:55,244 - MainThread ocsp_asn1crypto.py:248 - process_ocsp_response() - DEBUG - Certificate is attached in Basic OCSP Response
2020-03-26 00:56:55,244 - MainThread ocsp_asn1crypto.py:250 - process_ocsp_response() - DEBUG - Verifying the attached certificate is signed by the issuer
2020-03-26 00:56:55,245 - MainThread ocsp_asn1crypto.py:254 - process_ocsp_response() - DEBUG - Valid Not After: 2023-06-11 20:40:26+00:00
2020-03-26 00:56:55,248 - MainThread ocsp_asn1crypto.py:282 - process_ocsp_response() - DEBUG - Verifying the OCSP response is signed by the issuer.
2020-03-26 00:56:55,252 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2023-06-11 20:44:21+00:00
2020-03-26 00:56:55,252 - MainThread ocsp_snowflake.py:587 - find_cache() - DEBUG - hit cache for subject: <CERT_INFO>
2020-03-26 00:56:55,254 - MainThread ocsp_snowflake.py:1123 - validate_by_direct_connection() - DEBUG - using OCSP response cache
2020-03-26 00:56:55,255 - MainThread ocsp_asn1crypto.py:248 - process_ocsp_response() - DEBUG - Certificate is attached in Basic OCSP Response
2020-03-26 00:56:55,255 - MainThread ocsp_asn1crypto.py:250 - process_ocsp_response() - DEBUG - Verifying the attached certificate is signed by the issuer
2020-03-26 00:56:55,255 - MainThread ocsp_asn1crypto.py:254 - process_ocsp_response() - DEBUG - Valid Not After: 2023-06-11 20:44:21+00:00
2020-03-26 00:56:55,258 - MainThread ocsp_asn1crypto.py:282 - process_ocsp_response() - DEBUG - Verifying the OCSP response is signed by the issuer.
2020-03-26 00:56:55,265 - MainThread ocsp_asn1crypto.py:194 - is_valid_time() - DEBUG - Verifying the attached certificate is signed by the issuer. Valid Not After: 2021-12-14 07:00:00+00:00
2020-03-26 00:56:55,265 - MainThread ocsp_snowflake.py:587 - find_cache() - DEBUG - hit cache for subject: <CERT_INFO>
2020-03-26 00:56:55,266 - MainThread ocsp_snowflake.py:1123 - validate_by_direct_connection() - DEBUG - using OCSP response cache
2020-03-26 00:56:55,268 - MainThread ocsp_asn1crypto.py:248 - process_ocsp_response() - DEBUG - Certificate is attached in Basic OCSP Response
2020-03-26 00:56:55,268 - MainThread ocsp_asn1crypto.py:250 - process_ocsp_response() - DEBUG - Verifying the attached certificate is signed by the issuer
2020-03-26 00:56:55,268 - MainThread ocsp_asn1crypto.py:254 - process_ocsp_response() - DEBUG - Valid Not After: 2021-12-14 07:00:00+00:00
2020-03-26 00:56:55,271 - MainThread ocsp_asn1crypto.py:282 - process_ocsp_response() - DEBUG - Verifying the OCSP response is signed by the issuer.
2020-03-26 00:56:55,274 - MainThread ocsp_snowflake.py:521 - write_ocsp_response_cache_file() - DEBUG - writing OCSP response cache file
2020-03-26 00:56:55,274 - MainThread ocsp_snowflake.py:1516 - encode_ocsp_response_cache() - DEBUG - encoding OCSP response cache to JSON
2020-03-26 00:56:55,288 - MainThread ocsp_snowflake.py:1014 - _validate() - DEBUG - ok
2020-03-26 00:56:55,707 - MainThread network.py:805 - _request_exec() - DEBUG - SUCCESS
2020-03-26 00:56:55,707 - MainThread network.py:944 - _use_requests_session() - DEBUG - Active requests sessions: 0, idle: 1
2020-03-26 00:56:55,707 - MainThread network.py:533 - _post_request() - DEBUG - ret[code] = None, after post request
2020-03-26 00:56:55,707 - MainThread auth.py:279 - authenticate() - DEBUG - completed authentication
2020-03-26 00:56:55,707 - MainThread auth.py:304 - authenticate() - DEBUG - token = ******
2020-03-26 00:56:55,707 - MainThread auth.py:308 - authenticate() - DEBUG - master_token = ******
2020-03-26 00:56:55,707 - MainThread auth.py:312 - authenticate() - DEBUG - id_token = NULL
2020-03-26 00:56:55,708 - MainThread connection.py:561 - cursor() - DEBUG - cursor
Traceback (most recent call last):
  File "/Users/******/Projects/key_gen.py", line 56, in <module>
    cur.callproc("load_function_to_populate_staging()")
  File "/Users/******/Projects/venv/lib/python3.7/site-packages/snowflake/connector/cursor.py", line 288, in callproc
    u'sqlstate': SQLSTATE_FEATURE_NOT_SUPPORTED})
  File "/Users/*****/Projects/venv/lib/python3.7/site-packages/snowflake/connector/errors.py", line 97, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, errorclass, errorvalue)
  File "/Users/*****/Projects/venv/lib/python3.7/site-packages/snowflake/connector/errors.py", line 73, in default_errorhandler
    done_format_msg=errorvalue.get(u'done_format_msg'))
snowflake.connector.errors.NotSupportedError: 252008 (0A000): None: callproc is not supported.
2020-03-26 00:56:55,738 - MainThread connection.py:501 - close() - INFO - closed
2020-03-26 00:56:55,738 - MainThread telemetry.py:113 - close() - DEBUG - Closing telemetry client.
2020-03-26 00:56:55,738 - MainThread network.py:931 - _use_requests_session() - DEBUG - Active requests sessions: 1, idle: 0
2020-03-26 00:56:55,738 - MainThread network.py:636 - _request_exec_wrapper() - DEBUG - remaining request timeout: 5, retry cnt: 1
2020-03-26 00:56:55,738 - MainThread network.py:775 - _request_exec() - DEBUG - socket timeout: 60
2020-03-26 00:56:55,739 - MainThread network.py:891 - _request_exec() - DEBUG - Hit retryable client error. Retrying... Ignore the following error stack: could not find io module state (interpreter shutdown?)
Traceback (most recent call last):
  File "/Users//********//Projectsvenv/lib/python3.7/site-packages/snowflake/connector/network.py", line 799, in _request_exec
    auth=SnowflakeAuth(token),
  File "/Users/********/Projects/venv/lib/python3.7/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users//********//Projects/venv/lib/python3.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users//********//Projects/venv/lib/python3.7/site-packages/requests/models.py", line 316, in prepare
    self.prepare_body(data, files, json)
  File "/Users//********//Projects/venv/lib/python3.7/site-packages/requests/models.py", line 476, in prepare_body
    length = super_len(data)
  File "/Users//********//Projects/venv/lib/python3.7/site-packages/requests/utils.py", line 119, in super_len
    fileno = o.fileno()
RuntimeError: could not find io module state (interpreter shutdown?)
2020-03-26 00:56:55,740 - MainThread network.py:944 - _use_requests_session() - DEBUG - Active requests sessions: 0, idle: 1
2020-03-26 00:56:55,740 - MainThread network.py:533 - _post_request() - DEBUG - ret[code] = N/A, after post request
2020-03-26 00:56:55,742 - MainThread connection.py:507 - close() - DEBUG - Session is closed

Process finished with exit code 1

**Comment by chetansurwade** [comment]
Yes you can, just the standard sql query execution as you would for any other query and use the syntax something like`CALL db_name.schema_name.proc_name` also make sure the access rights are correct. Its throws a vague error in that case.

**Comment by userx91** [comment]
Agreed the message is vague here . I ended up doing the same..
