### ISSUE TITLE
OverflowError: date value out of range

### ISSUE THREAD

**Issue by mayfield** [snowflakedb/snowflake-connector-python#3]
I created a test table with this query...

`create or replace table perf_1m(seq, text, ts TIMESTAMP, f FLOAT, d DECIMAL) as select seq8(), randstr(100, random()), TO_TIMESTAMP(1400000000 * abs(random() / random(1))/ 10), random(), TO_DECIMAL(random() * 1121.1121212214) from table(generator(rowcount=>1 * 1000 * 1000));`

Attempting to **SELECT** from that table generates the following exception.

```
Command 'main' error, traceback...
Traceback (most recent call last)
2.  File "/usr/lib/python3.5/site-packages/snowflake_connector_python-1.3.12-py3.5.egg/snowflake/connector/cursor.py", line 837, in _row_to_python
      row[idx] = conv_method(col, conv_ctx)
1.  File "/usr/lib/python3.5/site-packages/snowflake_connector_python-1.3.12-py3.5.egg/snowflake/connector/converter.py", line 295, in _TIMESTAMP_NTZ_to_python
      t = ZERO_EPOCH + timedelta(seconds=(microseconds / float(1000000)))
OverflowError: date value out of range

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last)
  8.  File "/home/mayfield/project/shellish/shellish/session.py", line 116, in execute
        raise e
  7.  File "/home/mayfield/project/shellish/shellish/session.py", line 113, in execute
        result = command.run_wrap(args)
  6.  File "/home/mayfield/project/shellish/shellish/command/command.py", line 169, in run_wrap
        raise e
  5.  File "/home/mayfield/project/shellish/shellish/command/command.py", line 165, in run_wrap
        result = self.run(args)
  4.  File "/home/mayfield/project/shellish/shellish/command/autocommand.py", line 52, in run
        return self.func(*positionals, **keywords)
  3.  File "bench.py", line 54, in main
        while q.fetchone() is not None:
  2.  File "/usr/lib/python3.5/site-packages/snowflake_connector_python-1.3.12-py3.5.egg/snowflake/connector/cursor.py", line 671, in fetchone
        return self._row_to_python(row) if row is not None else None
  1.  File "/usr/lib/python3.5/site-packages/snowflake_connector_python-1.3.12-py3.5.egg/snowflake/connector/cursor.py", line 844, in _row_to_python
        type=FIELD_ID_TO_NAME(col_desc[1]),
  TypeError: 'collections.defaultdict' object is not callable
```

**Comment by smtakeda** [comment]
@mayfield Since the year range of `datetime` is between 1 and 9999, the out of range time will cause the exception:
https://docs.python.org/2/library/datetime.html

Can you capture the exact values that caused the exception?

**Comment by mayfield** [comment]
Hi @smtakeda the value is indeed outside datetime's capability.  Do you think in this case it should erupt the entire query or return a None type in that column with a warning log?

**Comment by smtakeda** [comment]
Good question. `None` with warning log sounds interesting to me, but I would rather keeping the current all-or-nothing behavior until a demand is raised. In that case, we will need to add a flag switching the behavior raise exception or `None` with warning log.

**Comment by sfc-gh-sfan** [comment]
To clean up and re-prioritize bugs and feature requests we are closing all issues older than 6 months as of March 1, 2023. If there are any issues or feature requests that you would like us to address, please re-create them. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response
