### ISSUE TITLE
SNOW-159405: snowflake-connector-python 2.2.4 requires keyring in setup.py

### ISSUE THREAD

**Issue by worldwise001** [snowflakedb/snowflake-connector-python#305]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
3.7.7

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Darwin-19.4.0-x86_64-i386-64bit

3. What are the component versions in the environment (`pip list`)? 
snowflake-connector-python 2.2.4

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

Upgraded to 2.2.4 and tried running the snowflake connector.

5. What did you expect to see?
typical log messages

6. What did you see instead?
```
Traceback (most recent call last):
  File "/Users/shh/Development/turtle-feeder/venv/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/shh/Development/turtle-feeder/databuilder/jobs/__init__.py", line 67, in orchestrate
    self.main_task(**kwargs)
  File "/Users/shh/Development/turtle-feeder/venv/lib/python3.7/site-packages/sqmetrics/__init__.py", line 214, in wrapper
    raise e
  File "/Users/shh/Development/turtle-feeder/venv/lib/python3.7/site-packages/sqmetrics/__init__.py", line 207, in wrapper
    result = f(*args, **kwargs)
  File "/Users/shh/Development/turtle-feeder/databuilder/jobs/snowflake_importer.py", line 57, in main_task
    cursor = self.snowflake_cursor()
  File "/Users/shh/Development/turtle-feeder/databuilder/jobs/snowflake_importer.py", line 90, in snowflake_cursor
    connection = snowflake.connector.connect(**conn_info)
  File "/Users/shh/Development/turtle-feeder/venv/lib/python3.7/site-packages/snowflake/connector/__init__.py", line 53, in Connect
    return SnowflakeConnection(**kwargs)
  File "/Users/shh/Development/turtle-feeder/venv/lib/python3.7/site-packages/snowflake/connector/connection.py", line 189, in __init__
    self.connect(**kwargs)
  File "/Users/shh/Development/turtle-feeder/venv/lib/python3.7/site-packages/snowflake/connector/connection.py", line 493, in connect
    self.__open_connection()
  File "/Users/shh/Development/turtle-feeder/venv/lib/python3.7/site-packages/snowflake/connector/connection.py", line 710, in __open_connection
    self.__authenticate(auth_instance)
  File "/Users/shh/Development/turtle-feeder/venv/lib/python3.7/site-packages/snowflake/connector/connection.py", line 963, in __authenticate
    session_parameters=self._session_parameters,
  File "/Users/shh/Development/turtle-feeder/venv/lib/python3.7/site-packages/snowflake/connector/auth.py", line 352, in authenticate
    PARAMETER_CLIENT_STORE_TEMPORARY_CREDENTIAL))
  File "/Users/shh/Development/turtle-feeder/venv/lib/python3.7/site-packages/snowflake/connector/auth.py", line 401, in write_temporary_credential
    raise MissingDependencyError("Please install keyring module to enable SSO token cache feature.")
snowflake.connector.errors.MissingDependencyError: Missing optional dependency: Please install keyring module to enable SSO token cache feature.
```

7. Can you set logging to DEBUG and collect the logs?
See above.

Once I ran `pip install keyring` everything worked. I believe this means there is a missing dep in setup.py .

**Comment by sfc-gh-wshangguan** [comment]
Hi, thanks for the issue! Could you please check that are you using external browser authentication?

**Comment by worldwise001** [comment]
Yes I was using external browser authentication.

**Comment by worldwise001** [comment]
Hmm, looks like it's in the extras. I'll close this out then.

**Comment by sfc-gh-mkeller** [comment]
Thank you for letting us know, @worldwise001
