### ISSUE TITLE
Python 3.6: SyntaxError: name 'force_to_stop' is assigned to before global declaration

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/snowflake-connector-python#34]
1.4.4 caused the regression in 3.6.

https://github.com/snowflakedb/snowflake-connector-python/commit/1cdeb3c547c858358c85483f5c54ccd7efe37a77##commitcomment-23875795

@JDFagan, Thanks for reporting an issue.

**Comment by JDFagan** [comment]
Yes, from Python 3.6 console (in PyCharm), this shows the issue clearly: ```
>>> import snowflake.connector
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/snowflake/connector/__init__.py", line 21, in <module>
    from .connection import SnowflakeConnection
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/snowflake/connector/connection.py", line 17, in <module>
    from .auth_webbrowser import AuthByWebBrowser
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/jdfagan/miniconda3/envs/waypoint_extraction/lib/python3.6/site-packages/snowflake/connector/auth_webbrowser.py", line 125
    global force_to_stop
    ^
SyntaxError: name 'force_to_stop' is assigned to before global declaration
```

**Comment by smtakeda** [comment]
Fixed in https://github.com/snowflakedb/snowflake-connector-python/commit/6d7a7eac56a5255aade98a2f6b3573df85a90407.

Will be released as 1.4.5. Sorry about the regression.

**Comment by smtakeda** [comment]
v1.4.5 is out.
