### ISSUE TITLE
SNOW-187239: MissingDependencyError: Missing optional dependency: pandas

### ISSUE THREAD

**Issue by Yuchen-Peng** [snowflakedb/snowflake-connector-python#383]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
Python 3.6.1

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Linux-4.14.186-146.268.amzn2.x86_64-x86_64-with-centos-7.8.2003-Core

3. What are the component versions in the environment (`pip list`)?
Package                    Version
-------------------------- -------------------
asn1crypto                 1.4.0
azure-common               1.1.25
azure-core                 1.8.0
azure-storage-blob         12.4.0
boto3                      1.14.48
botocore                   1.17.48
certifi                    2020.6.20
cffi                       1.14.2
chardet                    3.0.4
cryptography               2.9.2
docutils                   0.15.2
idna                       2.9
isodate                    0.6.0
jmespath                   0.10.0
msrest                     0.6.18
numpy                      1.19.1
oauthlib                   3.1.0
oscrypto                   1.2.1
pandas                     1.1.1
pip                        20.2.2
pycparser                  2.20
pycryptodomex              3.9.8
PyJWT                      1.7.1
pyOpenSSL                  19.1.0
python-dateutil            2.8.1
pytz                       2020.1
requests                   2.23.0
requests-oauthlib          1.3.0
s3transfer                 0.3.3
setuptools                 49.6.0.post20200814
six                        1.15.0
snowflake-connector-python 2.3.1
urllib3                    1.25.10
wheel                      0.35.1

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

```
from snowflake.connector.pandas_tools import write_pandas
```

5. What did you expect to see?

6. What did you see instead?

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lzq857/.conda/envs/sf_pd/lib/python3.6/site-packages/snowflake/connector/pandas_tools.py", line 143, in <module>
    def pd_writer(table: pandas.io.sql.SQLTable,
  File "/home/lzq857/.conda/envs/sf_pd/lib/python3.6/site-packages/snowflake/connector/options.py", line 25, in __getattr__
    raise MissingDependencyError('pandas')
snowflake.connector.errors.MissingDependencyError: Missing optional dependency: pandas
```

7. Can you set logging to DEBUG and collect the logs?

```
import logging
import os

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']:
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```

See below for the log

```
2020-08-26 21:39:13,055 - MainThread ssl_wrap_socket.py:81 - inject_into_urllib3() - DEBUG - Injecting ssl_wrap_socket_with_ocsp
2020-08-26 21:39:13,055 - MainThread auth.py:47 - <module>() - DEBUG - Failed to import keyring module. err=[No module named 'keyring']
2020-08-26 21:39:13,056 - MainThread auth.py:67 - <module>() - DEBUG - cache directory: /home/lzq857/.cache/snowflake
2020-08-26 21:39:13,321 - MainThread cursor.py:43 - <module>() - DEBUG - Failed to import pyarrow. Cannot use pandas fetch API
2020-08-26 21:39:13,625 - MainThread arrow_result.pyx:0 - func_name not provided() - INFO - Failed to import optional packages, pyarrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lzq857/.conda/envs/sf_pd/lib/python3.6/site-packages/snowflake/connector/pandas_tools.py", line 143, in <module>
    def pd_writer(table: pandas.io.sql.SQLTable,
  File "/home/lzq857/.conda/envs/sf_pd/lib/python3.6/site-packages/snowflake/connector/options.py", line 25, in __getattr__
    raise MissingDependencyError('pandas')
snowflake.connector.errors.MissingDependencyError: Missing optional dependency: pandas
```

**Comment by sfc-gh-mkeller** [comment]
Please see: https://docs.snowflake.com/en/user-guide/python-connector-pandas.html#installation
