### ISSUE TITLE
ImportError: No module named 'azure.storage'

### ISSUE THREAD

**Issue by bi1yeu** [snowflakedb/snowflake-connector-python#40]
- Ubuntu 14.04.5
- Python 3.4.3
- Clean virtual environment
- Version specified in `setup.py`: `snowflake-connector-python==1.4.10`

Followed the installation instructions here: https://docs.snowflake.net/manuals/user-guide/python-connector-install.html

I can install `snowflake-connector-python` successfully, but I get this error when `import`ing it:

```
>>> import snowflake.connector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/.virtualenvs/example/lib/python3.4/site-packages/snowflake_connector_python-1.4.10-py3.4.egg/snowflake/connector/__init__.py", line 21, in <module>
    from .connection import SnowflakeConnection
  File "/home/vagrant/.virtualenvs/example/lib/python3.4/site-packages/snowflake_connector_python-1.4.10-py3.4.egg/snowflake/connector/connection.py", line 24, in <module>
    from .cursor import SnowflakeCursor
  File "/home/vagrant/.virtualenvs/example/lib/python3.4/site-packages/snowflake_connector_python-1.4.10-py3.4.egg/snowflake/connector/cursor.py", line 29, in <module>
    from .file_transfer_agent import (SnowflakeFileTransferAgent)
  File "/home/vagrant/.virtualenvs/example/lib/python3.4/site-packages/snowflake_connector_python-1.4.10-py3.4.egg/snowflake/connector/file_transfer_agent.py", line 31, in <module>
    from .remote_storage_util import (SnowflakeFileEncryptionMaterial, SnowflakeRemoteStorageUtil,
  File "/home/vagrant/.virtualenvs/example/lib/python3.4/site-packages/snowflake_connector_python-1.4.10-py3.4.egg/snowflake/connector/remote_storage_util.py", line 16, in <module>
    from .azure_util import SnowflakeAzureUtil
  File "/home/vagrant/.virtualenvs/example/lib/python3.4/site-packages/snowflake_connector_python-1.4.10-py3.4.egg/snowflake/connector/azure_util.py", line 8, in <module>
    from azure.storage.blob import BlockBlobService
ImportError: No module named 'azure.storage'
```

I don't get this error with version 1.4.9.

**Comment by smtakeda** [comment]
can you provide the output from
```
>pip list | grep azure
```
You should get something like this:
```
azure-common (1.1.8)
azure-nspkg (2.0.0)
azure-storage (0.34.2)
```
Also check {{site-packages}} directory if {{azure/storage}} exists? For example, if you create a virtualenv at `/tmp/a`, the site-packge is this:
```
/tmp/a/lib/python3.4/site-packages
```

**Comment by bi1yeu** [comment]
@smtakeda Thanks for the quick response.

```
$ pip list | grep azure

azure-common (1.1.8)
azure-nspkg (2.0.0)
azure-storage (0.34.2)
```

```
$ ls -l ~/.virtualenvs/example/lib/python3.4/site-packages/azure_storage-0.34.2-py3.4.egg
total 8.0K
drwxrwxr-x 3 vagrant vagrant 4.0K Nov  6 11:30 azure/
drwxrwxr-x 2 vagrant vagrant 4.0K Nov  6 11:30 EGG-INFO/
```

**Comment by smtakeda** [comment]
hmm, looks like `easy_install` was used to install `azure`? Did you happen to run `python setup.py install`? That seems to trigger easy_install and create egg directories.

Here is my test case:
```
pyvenv-3.4 /tmp/a
source /tmp/a/bin/activate
pip install -U pip
pip install -U snowflake-connetor-python
```
and site-packages would be like this where no egg directory is included.
```
>ls /tmp/a/lib/python3.4/site-packages/
asn1crypto/                    azure_storage-0.34.2.dist-info/  certifi/                       chardet/                       dateutil/                 future-0.16.0.dist-info/  jmespath/                  OpenSSL/              pyasn1/                          pycparser/                        pytz/                       s3transfer-0.1.11.dist-info/  snowflake/
asn1crypto-0.23.0.dist-info/   boto3/                           certifi-2017.11.5.dist-info/   chardet-3.0.4.dist-info/       docutils/                 idna/                     jmespath-0.9.3.dist-info/  past/                 pyasn1-0.3.7.dist-info/          pycparser-2.18.dist-info/         pytz-2017.3.dist-info/      setuptools/                   snowflake_connector_python-1.4.10.dist-info/
azure/                         boto3-1.4.7.dist-info/           cffi/                          Crypto/                        docutils-0.14.dist-info/  idna-2.6.dist-info/       libfuturize/               pip/                  pyasn1_modules/                  pycryptodome-3.4.7.dist-info/     requests/                   setuptools-12.0.5.dist-info/  snowflake_connector_python-1.4.10-py2.7-nspkg.pth
azure_common-1.1.8.dist-info/  botocore/                        cffi-1.11.2.dist-info/         cryptography/                  easy_install.py           ijson/                    libpasteurize/             pip-9.0.1.dist-info/  pyasn1_modules-0.1.5.dist-info/  pyOpenSSL-17.3.0.dist-info/       requests-2.18.4.dist-info/  six-1.11.0.dist-info/         urllib3/
azure_nspkg-2.0.0.dist-info/   botocore-1.7.39.dist-info/       _cffi_backend.cpython-34m.so*  cryptography-2.1.3.dist-info/  future/                   ijson-2.3.dist-info/      _markerlib/                pkg_resources/        __pycache__/                     python_dateutil-2.6.1.dist-info/  s3transfer/                 six.py                        urllib3-1.22.dist-info/
```

easy_install is not supported (or at least I have not figured how to support both pip and easy_install...)

In my understanding, `azure` directory must be right under `site-packages` directory for pip managed virtualenv.

**Comment by bi1yeu** [comment]
@smtakeda Yes, I did install `snowflake-connector-python` by adding it to my project's `setup.py` file under `install_requires` (`snowflake-connector-python==1.4.10`) and running `python setup.py install`. if i use `pip` directly to install `snowflake-connector-python` I don't see this error. Thanks for clarifying.

**Comment by bi1yeu** [comment]
@smtakeda Confirmed that it works if I install with `pip install -e .`. I'll go ahead and close this. Thanks for the help 👍
