### ISSUE TITLE
SNOW-329431: `StatusQuery.QUEUED_REPAIRING_WAREHOUSE` is not correctly represented in the API (typo)

### ISSUE THREAD

**Issue by fermezz** [snowflakedb/snowflake-connector-python#665]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
`Python 3.8.2`

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
`macOS-10.15.7-x86_64-i386-64bit`

3. What are the component versions in the environment (`pip freeze`)?

```
appnope==0.1.2
asn1crypto==1.4.0
azure-common==1.1.26
azure-core==1.12.0
azure-storage-blob==12.8.0
backcall==0.2.0
boto3==1.17.35
botocore==1.20.35
certifi==2020.12.5
cffi==1.14.5
chardet==3.0.4
cryptography==3.4.6
decorator==4.4.2
idna==2.10
ipdb==0.13.7
ipython==7.21.0
ipython-genutils==0.2.0
isodate==0.6.0
jedi==0.18.0
jmespath==0.10.0
msrest==0.6.21
oauthlib==3.1.0
oscrypto==1.2.1
parso==0.8.1
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.18
ptyprocess==0.7.0
pycparser==2.20
pycryptodomex==3.10.1
Pygments==2.8.1
PyJWT==2.0.1
pyOpenSSL==19.1.0
python-dateutil==2.8.1
pytz==2021.1
requests==2.25.1
requests-oauthlib==1.3.0
s3transfer==0.3.6
six==1.15.0
snowflake-connector-python==2.4.1
toml==0.10.2
traitlets==5.0.5
urllib3==1.26.4
wcwidth==0.2.5
```

4. What did you do?
Ran an async query and fetched for its status.

5. What did you expect to see?
Status being fetched and displayed successfully

6. What did you see instead?
Traceback because of `KeyError`.

```
Traceback (most recent call last):
  File "snowflake.py", line 89, in <module>
    run()
  File "snowflake.py", line 59, in run
    current_query_status = connection.get_query_status(query_id).name
  File "/Users/fmezzabotta/.virtualenvs/snowflake/lib/python3.8/site-packages/snowflake/connector/connection.py", line 1205, in get_query_status
    status, status_resp = self._get_query_status(sf_qid)
  File "/Users/fmezzabotta/.virtualenvs/snowflake/lib/python3.8/site-packages/snowflake/connector/connection.py", line 1187, in _get_query_status
    status_ret = QueryStatus[status]
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/enum.py", line 344, in __getitem__
    return cls._member_map_[name]
KeyError: 'QUEUED_REPARING_WAREHOUSE'
```

7. Can you set logging to DEBUG and collect the logs?

–––––

It seems like this was contemplated according to a [comment specifying it is a typo on purpose](https://github.com/snowflakedb/snowflake-connector-python/blob/bc9616ad568b23cb8a931d2d590041f6bac1cff9/src/snowflake/connector/constants.py#L185-L186) but the constant is named correctly (`QUEUED_REPAIRING_WAREHOUSE`) and the string coming back from the server is not (`QUEUED_REPARING_WAREHOUSE`). I'm glad to build a PR to fix this if what I'm seeing is correct.

**Comment by fermezz** [comment]
Went ahead and created a PR. Let me know if it's helpful!
