### ISSUE TITLE
SNOW-363707: Python dependency management broken for certifi for current build

### ISSUE THREAD

**Issue by jowparks** [snowflakedb/snowflake-connector-python#734]
This version of dependency handling broke my build:

https://github.com/snowflakedb/snowflake-connector-python/commit/59f67319d85f5bbca0cad7fac2da84310c73a5a1

Can you remove the less than version portion? Or combine the `certifi` lines into a single line? What is it trying to accomplish in its current format?

Error in my build:
```
[2021-06-02T17:38:55.535Z] Searching for certifi>=2017.4.17

[2021-06-02T17:38:55.535Z] Reading https://pypi.org/simple/certifi/

[2021-06-02T17:38:55.535Z] Downloading https://files.pythonhosted.org/packages/05/1b/0a0dece0e8aa492a6ec9e4ad2fe366b511558cdc73fd3abc82ba7348e875/certifi-2021.5.30-py2.py3-none-any.whl#sha256=50b1e4f8446b06f41be7dd6338db18e0990601dce795c2b1686458aa7e8fa7d8

[2021-06-02T17:38:55.535Z] Best match: certifi 2021.5.30

[2021-06-02T17:38:55.535Z] Processing certifi-2021.5.30-py2.py3-none-any.whl

[2021-06-02T17:38:55.535Z] Installing certifi-2021.5.30-py2.py3-none-any.whl to /usr/src/myapp/.eggs

[2021-06-02T17:38:55.535Z] 

[2021-06-02T17:38:55.535Z] Installed /usr/src/myapp/.eggs/certifi-2021.5.30-py3.7.egg

[2021-06-02T17:38:55.535Z] Traceback (most recent call last):

[2021-06-02T17:38:55.535Z]   File "setup.py", line 39, in <module>

[2021-06-02T17:38:55.535Z]     "Programming Language :: Python :: 3"

[2021-06-02T17:38:55.535Z]   File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup

[2021-06-02T17:38:55.535Z]     return distutils.core.setup(**attrs)

[2021-06-02T17:38:55.535Z]   File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup

[2021-06-02T17:38:55.535Z]     dist.run_commands()

[2021-06-02T17:38:55.535Z]   File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands

[2021-06-02T17:38:55.535Z]     self.run_command(cmd)

[2021-06-02T17:38:55.535Z]   File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command

[2021-06-02T17:38:55.535Z]     cmd_obj.run()

[2021-06-02T17:38:55.535Z]   File "/usr/src/myapp/.eggs/pytest_runner-5.3.1-py3.7.egg/ptr.py", line 202, in run

[2021-06-02T17:38:55.535Z]     installed_dists = self.install_dists(dist)

[2021-06-02T17:38:55.535Z]   File "/usr/src/myapp/.eggs/pytest_runner-5.3.1-py3.7.egg/ptr.py", line 153, in install_dists

[2021-06-02T17:38:55.535Z]     orig.test.install_dists(dist), self.install_extra_dists(dist)

[2021-06-02T17:38:55.535Z]   File "/usr/local/lib/python3.7/site-packages/setuptools/command/test.py", line 203, in install_dists

[2021-06-02T17:38:55.535Z]     ir_d = dist.fetch_build_eggs(dist.install_requires)

[2021-06-02T17:38:55.535Z]   File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 782, in fetch_build_eggs

[2021-06-02T17:38:55.535Z]     replace_conflicting=True,

[2021-06-02T17:38:55.535Z]   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 777, in resolve

[2021-06-02T17:38:55.535Z]     raise VersionConflict(dist, req).with_context(dependent_req)

[2021-06-02T17:38:55.535Z] pkg_resources.ContextualVersionConflict: (certifi 2021.5.30 (/usr/src/myapp/.eggs/certifi-2021.5.30-py3.7.egg), Requirement.parse('certifi<2021.0.0'), {'snowflake-connector-python'})
```

**Comment by jowparks** [comment]
Looks like this bug was fixed with an update, although I will say I ran into another one with `chardet` version not being acceptable because a dependency was installed in wrong order, these ranges should be expanded and issues caught with automated testing rather than break downstream user builds.

**Comment by jowparks** [comment]
Closing to merge with other task
