### ISSUE TITLE
SNOW-367177: Query row iterator hangs

### ISSUE THREAD

**Issue by Kache** [snowflakedb/snowflake-connector-python#748]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?

`Python 3.7.10`, have also replicated using `Python 3.9.4`

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

`Darwin-20.4.0-x86_64-i386-64bit`

3. What are the component versions in the environment (`pip freeze`)?

```
asn1crypto @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/c5/b9/72/6baab91d6f901723f6b6635377881fee0bc2b7a583460a3557a79ca679/asn1crypto-1.4.0-py2.py3-none-any.whl
azure-common @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/75/fb/12/a2b5ecc8fa7e9e7c6646780b4884a8deef0f62ad6b8e59cd2b503c5445/azure_common-1.1.27-py2.py3-none-any.whl
azure-core @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/a0/1a/c5/29f48b753ac8467a6ead81d0e948eedccccfd6bdaa4f76ea02d389f184/azure_core-1.15.0-py2.py3-none-any.whl
azure-storage-blob @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/ed/07/39/d62302e951bcf0cc176148baff61beb311a0867b7aad639066c264df08/azure_storage_blob-12.8.1-py2.py3-none-any.whl
boto3 @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/1e/40/ae/c5f4e6fac8053898c10d50cd4294bb5a102820e2e10f0ab8061cf013ad/boto3-1.17.92-py2.py3-none-any.whl
botocore @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/3a/46/96/a9a58413bf095c004b64d093990cdeba27ccd5c491b98d9e9f7a3c5eaf/botocore-1.20.92-py2.py3-none-any.whl
certifi @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/d8/df/24/ed696681f34f8916b0aef99138db9a94e37d54684b9829af34a7fd4e39/certifi-2020.12.5-py2.py3-none-any.whl
cffi @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/6f/3e/aa/695e0fce0a6ea594bbe73f9f18593d2d37564d139fbc8f58d377a00d93/cffi-1.14.5-cp39-cp39-macosx_10_9_x86_64.whl
chardet @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/8f/6f/1c/8085d730ad63c462222af30d0d01c4bd0caca5287e40b63c1fe8f529b7/chardet-3.0.4-py2.py3-none-any.whl
cryptography @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/c7/6d/36/40b404429242377c0424cb9957a04887a4be7399a62c1505197845c09f/cryptography-3.4.7-cp36-abi3-macosx_10_10_x86_64.whl
idna @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/ef/7f/a9/19cc0b8760bdf6f696290c06532496f8bb29fbdaad044f852fed00ec82/idna-2.10-py2.py3-none-any.whl
isodate @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/95/34/e8/bf99fab064e9305ca4f58f1804b8d30e544c06bcabed2658efd6783191/isodate-0.6.0-py2.py3-none-any.whl
jmespath @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/2c/f0/52/b0ba93d941bd49c8719dee7ca27d2096bf96e17948667388c3ee2ac8f8/jmespath-0.10.0-py2.py3-none-any.whl
msrest @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/de/61/68/835084c4281a3da5804afb472e90674bc826dec6fd39678408eb7e807c/msrest-0.6.21-py2.py3-none-any.whl
numpy @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/f1/86/6b/e10828b94dbaf4f94a011870967977fca85326d78a303260e12bfa0575/numpy-1.20.3-cp39-cp39-macosx_10_9_x86_64.whl
oauthlib @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/8f/79/8f/4e7de5a92b46f97baa6ac78e9bc5605815af5ee36b2dadd4b682de341b/oauthlib-3.1.1-py2.py3-none-any.whl
oscrypto @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/54/6f/a6/8cb8a12d841419cada4c991f513002914d6dcf7ed0bb908b7e31e78d21/oscrypto-1.2.1-py2.py3-none-any.whl
pandas @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/d6/46/dd/ade2cc36ffc831ce0f78205b8f3e5293bbfb14f72799761c759c028a68/pandas-1.1.5-cp39-cp39-macosx_10_9_x86_64.whl
pyarrow @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/2c/20/bf/69ebec25c24ffd2f10d58a1baad26e8a2f0d67b8bd3356a1190a3340d8/pyarrow-3.0.0-cp39-cp39-macosx_10_13_x86_64.whl
pycparser @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/37/8e/5a/0ea4f84bc7f11e0e3468110efa2c7783241ea7eaa63a92a751de06f78f/pycparser-2.20-py2.py3-none-any.whl
pycryptodomex @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/07/b5/ca/df80653dbcdc31ca50eb5e92312e487cba00ddc5fe374a3756520d3f70/pycryptodomex-3.10.1-cp35-abi3-macosx_10_9_x86_64.whl
PyJWT @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/33/2d/3b/c07cd30707fdf78d1c8279fdbc13b6aca325b3091040eff97623d32f78/PyJWT-2.1.0-py3-none-any.whl
pyOpenSSL @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/27/2a/6f/de8129dc1f8ba5d04f604e929a7f055c4ca7c08ceec8bf801182df8774/pyOpenSSL-20.0.1-py2.py3-none-any.whl
python-dateutil @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/93/67/cf/49f56d9e954addcfc50e5ffc9faee013c2eb00c6d77d56c6a22cb33b54/python_dateutil-2.8.1-py2.py3-none-any.whl
pytz @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/b0/a7/8d/54de3ab4d1ff29abbbca1e9ccbaefdc2a1b290138311b84f73bee16de1/pytz-2021.1-py2.py3-none-any.whl
requests @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/22/0a/9d/0df883fbffbb406d0cddbb35e881e4ac6bfb8f0dee8733056b6a054bf7/requests-2.25.1-py2.py3-none-any.whl
requests-oauthlib @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/11/f5/eb/81a5da1da15ae0d7c5c1cc43f729856e59f8a0f09c77051ed1841bd01d/requests_oauthlib-1.3.0-py2.py3-none-any.whl
s3transfer @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/8f/96/42/4ec7dc1795d747cb348df8b6aad3b471251863f3eab457ce33668cf8a1/s3transfer-0.4.2-py2.py3-none-any.whl
six @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/08/9f/47/c16ae03035fc69eaf100ea39657a49baaeef714e25a52575710c34cd48/six-1.16.0-py2.py3-none-any.whl
snowflake-connector-python @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/22/e2/33/3edbba6f5c8e960825f94fec6267f408e516b4a2ea3a5c55fb6736dc68/snowflake_connector_python-2.4.4-cp39-cp39-macosx_10_13_universal2.whl
urllib3 @ file:///Users/REDACTED/Library/Caches/pypoetry/artifacts/51/08/ff/7c6aaf6cf9ca83a0bf63c5121f187a40571849e9b17bd8e031898d76c2/urllib3-1.26.5-py2.py3-none-any.whl
```

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

Created in a new venv with only `snowflake-connector-python` as dependency

```python
from contextlib import contextmanager
import functools as ft
import os
from pathlib import Path

from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization
import snowflake
import snowflake.connector

ENV = os.environ


def snow_creds():
    return {
        'account': ENV['SNOWFLAKE_ACCOUNT'],
        'user': ENV['SNOWFLAKE_USER'],
    }


@ft.lru_cache()
def private_key_bytes(keypath='~/.ssh/snowflake_key.p8'):
    keyfile = Path(keypath).expanduser()
    p_key = serialization.load_pem_private_key(
        keyfile.read_bytes(),
        password=os.environ['SNOWFLAKE_PRIVATE_KEY_PASSPHRASE'].encode(),
        backend=default_backend(),
    ) if keyfile.exists() else None

    return p_key.private_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    ) if p_key else None


@contextmanager
def raw_cursor():
    context = snowflake.connector.connect(private_key=private_key_bytes(), **snow_creds())

    cursor = None
    try:
        cursor = context.cursor()
        yield cursor
    finally:
        if cursor:
            cursor.close()


def rows(sql, rows=1_000):
    with raw_cursor() as raw:
        cursor = raw.execute(sql)

        results = cursor.fetchmany(rows)
        while results:
            yield from results
            results = cursor.fetchmany(rows)


wont_hang = 'SELECT CURRENT_VERSION()'
print(next(rows(wont_hang, rows=1)))

will_hang = 'SELECT SEQ4() FROM TABLE(GENERATOR(ROWCOUNT => 100000))'
result = next(rows(will_hang, rows=1))
print(result)

# sorry if var names of queries are misleading, I now believe it hangs only b/c
# the script is trying to do something "at_exit", not b/c of the particular queries
```

5. What did you expect to see?

```
('5.21.2',)
(0,)
```

And clean exit.

6. What did you see instead?

Results are printed, but process hangs. In tests, also hangs, but with different trace.

after SIGINT:

```
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/REDACTED/.asdf/installs/python/3.7.10/lib/python3.7/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/Users/REDACTED/.asdf/installs/python/3.7.10/lib/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/Users/REDACTED/.asdf/installs/python/3.7.10/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```
(similar error /w Python 3.9 installed from homebrew)

when running similar code in my project's tests:

```
Traceback (most recent call last):
  File "$PROJ_ROOT/.venv/lib/python3.7/site-packages/snowflake/connector/network.py", line 945, in _request_exec
    raw_ret.raw, download_end_time - download_start_time
  File "$PROJ_ROOT/.venv/lib/python3.7/site-packages/snowflake/connector/chunk_downloader.py", line 368, in to_iterator
    self._cursor.connection._numpy,
AttributeError: 'NoneType' object has no attribute '_numpy'
```

I was able to "fix" this issue by setting [this line](https://github.com/snowflakedb/snowflake-connector-python/blob/0f7b9385adbd54e2e2608f3672528959ae943094/src/snowflake/connector/chunk_downloader.py#L368) to:

`            self._cursor.connection and self._cursor.connection._numpy,`

7. Can you set logging to DEBUG and collect the logs?

WIP

```
import logging
import os

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']:
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```

**Comment by Kache** [comment]
Some of my guesses as to what's going on:

The error is that `connection` is `None`. I think the error is happening during some exit handler, when the connection has closed, maybe.

New to Python and unfamiliar with `.pyx`, but `connection._numpy` looks like passed to to: use_numpy in `arrow_iterator.pyx`, which goes to CArrowChunkIterator.cpp (not familiar with cpp either) as: `m_useNumpy = PyObject_IsTrue(use_numpy);`

i.e. looks like `connection._numpy` is just used as a Boolean

**Comment by sfc-gh-mkeller** [comment]
Hi @Kache 
I tried looking at this issue by first writing a test that doesn't work without your code change and I came up with the following script:
```python
import snowflake.connector

connection_params = {
    "account": ...
}


def rows(sql, rows=1_000):
    with snowflake.connector.connect(**connection_params) as con:
        with con.cursor() as raw:
                raw.execute(sql)
                results = raw.fetchmany(rows)
                while results:
                    yield from results
                    results = raw.fetchmany(rows)


wont_hang = 'SELECT CURRENT_VERSION()'
print(next(rows(wont_hang, rows=1)))

will_hang = 'SELECT SEQ4() FROM TABLE(GENERATOR(ROWCOUNT => 100000))'
result = next(rows(will_hang, rows=1))
print(result)
```

Which produces:

```
('5.28.0',)
(0,)
```

Something to consider is that `chunk_downloader` is going away as soon as we merge #787

**Comment by Kache** [comment]
Cool! So you were able to repro? The snippet I posted was a hasty strip-down of original source where I was seeing this happening.

> `chunk_downloader` is going away

ctrl + F'd for both `._numpy` and `.connection` in the PR shows that the NPE bug is removed 👍 .

Any info on when the change will be slated for release?

**Comment by Kache** [comment]
Saw that #787 was merged. Will it make it into the next release?

**Comment by Kache** [comment]
I see the latest release has resolved this problem, thanks!
