### ISSUE TITLE
SNOW-433677: Table '"bonus"' does not exist although created earles

### ISSUE THREAD

**Issue by zopyx** [snowflakedb/snowflake-connector-python#833]
I have this script that creates a table `bonus` and tries to insert a dataframe using `write_pandas()`. However this fails badly although the table has been created (checked through the web UI):

Python 3.8.11
snowflake-connector-python==2.5.1

```
Storing dataframe in Snowflake
Traceback (most recent call last):
  File "snowflake_batch_test.py", line 37, in <module>
    success, nchunks, nrows, _ = write_pandas(
  File "/home/ajung/src/e.on/eon.bonusengine.base/.venv/lib/python3.8/site-packages/snowflake/connector/pandas_tools.py", line 202, in write_pandas
    copy_results = cursor.execute(copy_into_sql, _is_internal=True).fetchall()
  File "/home/ajung/src/e.on/eon.bonusengine.base/.venv/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 721, in execute
    Error.errorhandler_wrapper(
  File "/home/ajung/src/e.on/eon.bonusengine.base/.venv/lib/python3.8/site-packages/snowflake/connector/errors.py", line 258, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ajung/src/e.on/eon.bonusengine.base/.venv/lib/python3.8/site-packages/snowflake/connector/errors.py", line 188, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001757 (42601): SQL compilation error:
Table '"bonus"' does not exist

```

```
from eon.bonusengine.base.snowflake_connector import SnowflakeConnector

from snowflake.connector.pandas_tools import write_pandas


TABLE_CREATE = """
    CREATE OR REPLACE TABLE 
    bonus (
    postcode integer, 
    city varchar, 
    consumption integer,
    fix_price float, 
    var_cost float,
    id int
    )
"""


print(TABLE_CREATE)

print("reading sample data")
df = pandas.read_csv("sample.csv.gz")
print(f"got {len(df)} rows")


print("connecting to Snowflake")
sf = SnowflakeConnector()
sf_cursor = sf.cursor()

sf_cursor.execute("create database if not exists bonus")
sf_cursor.execute("use database bonus")

sf_cursor.execute(TABLE_CREATE)

print("Storing dataframe in Snowflake")
success, nchunks, nrows, _ = write_pandas(
        conn=sf, 
        df=df, 
        table_name='bonus',
#        database="bonus"
        )

```

**Comment by zopyx** [comment]
Obviously, the `table_name` parameter must be uppercase. SOLVED.
