### ISSUE TITLE
SNOW-467993: 2.5.1 build dependencies failing 

### ISSUE THREAD

**Issue by gasci** [snowflakedb/snowflake-connector-python#873]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   3.9.7

2. What operating system and processor architecture are you using?

   Darwin-20.6.0-arm64-arm-64bit

3. What are the component versions in the environment (`pip freeze`)?

   Replace with the output of python -m pip freeze`

      ```asn1crypto==1.4.0
      azure-common==1.1.27
      azure-core==1.17.0
      azure-storage-blob==12.8.1
      boto3==1.18.30
      botocore==1.21.30
      certifi==2021.5.30
      cffi==1.14.6
      chardet==4.0.0
      charset-normalizer==2.0.4
      cryptography==3.4.8
      Cython==0.29.24
      idna==3.2
      isodate==0.6.0
      jmespath==0.10.0
      msrest==0.6.21
      oauthlib==3.1.1
      oscrypto==1.2.1
      pycparser==2.20
      pycryptodomex==3.10.1
      PyJWT==2.1.0
      pyOpenSSL==20.0.1
      python-dateutil==2.8.2
      pytz==2021.1
      requests==2.26.0
      requests-oauthlib==1.3.0
      s3transfer==0.5.0
      six==1.16.0
      urllib3==1.26.6```

4. What did you do?

  ```python3 -m venv venv
  source venv/bin/activate
  pip3 install -r requirements.txt
  pip3 install snowflake-connector-python==2.5.1
  pip3 install --no-deps snowflake-connector-python==2.5.1
 ```

5. What did you expect to see?

     The library should have been installed correctly but I get a build error.

6. Can you set logging to DEBUG and collect the logs?

   ```Collecting snowflake-connector-python==2.5.1
  Using cached snowflake-connector-python-2.5.1.tar.gz (344 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /home/gokasci/venv/bin/python3 /home/gokasci/venv/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-3urrbfxk/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel cython 'pyarrow>=3.0.0,<3.1.0'
       cwd: None
  Complete output (210 lines):
  Collecting setuptools>=40.6.0
    Using cached setuptools-58.1.0-py3-none-any.whl (816 kB)
  Collecting wheel
    Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
  Collecting cython
    Using cached Cython-0.29.24-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.9 MB)
  Collecting pyarrow<3.1.0,>=3.0.0
    Using cached pyarrow-3.0.0.tar.gz (682 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting numpy>=1.16.6
    Using cached numpy-1.21.2-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (13.1 MB)
  Building wheels for collected packages: pyarrow
    Building wheel for pyarrow (PEP 517): started
    Building wheel for pyarrow (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/gokasci/venv/bin/python3 /tmp/tmp18rkpxbp build_wheel /tmp/tmpkucceae6
         cwd: /tmp/pip-install-q0bfswpo/pyarrow
    Complete output (183 lines):
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.8
    creating build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/benchmark.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/cuda.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/csv.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/json.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/__init__.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/feather.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/orc.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/types.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/hdfs.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/parquet.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/compute.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/flight.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/util.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/cffi.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/_generated_version.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/serialization.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/pandas_compat.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/filesystem.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/jvm.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/plasma.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/dataset.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/ipc.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/fs.py -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/compat.py -> build/lib.linux-aarch64-3.8/pyarrow
    creating build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_flight.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_serialization.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_plasma_tf_op.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_cuda.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_fs.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/arrow_7980.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_json.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_extension_type.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_types.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_ipc.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_tensor.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_feather.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/__init__.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/pandas_examples.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_csv.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_cuda_numba_interop.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_scalars.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_plasma.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_compute.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/deserialize_buffer.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_strategies.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/pandas_threaded_import.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_pandas.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_orc.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/util.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_table.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_gandiva.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_deprecations.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_cython.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_memory.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_io.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_schema.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_array.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_jvm.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_builder.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_filesystem.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_misc.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_adhoc_memory_leak.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_hdfs.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_sparse_tensor.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_convert_builtin.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_dataset.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_cffi.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/test_serialization_deprecated.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/conftest.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    copying pyarrow/tests/strategies.py -> build/lib.linux-aarch64-3.8/pyarrow/tests
    running egg_info
    writing pyarrow.egg-info/PKG-INFO
    writing dependency_links to pyarrow.egg-info/dependency_links.txt
    writing entry points to pyarrow.egg-info/entry_points.txt
    writing requirements to pyarrow.egg-info/requires.txt
    writing top-level names to pyarrow.egg-info/top_level.txt
    listing git files failed - pretending there aren't any
    reading manifest file 'pyarrow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '../LICENSE.txt'
    warning: no files found matching '../NOTICE.txt'
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '#*' found anywhere in distribution
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '.DS_Store' found anywhere in distribution
    no previously-included directories found matching '.asv'
    writing manifest file 'pyarrow.egg-info/SOURCES.txt'
    copying pyarrow/__init__.pxd -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/_compute.pxd -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/_compute.pyx -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/_csv.pxd -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/_csv.pyx -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/_cuda.pxd -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/_cuda.pyx -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/_dataset.pyx -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/_flight.pyx -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/_fs.pxd -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/_fs.pyx -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/_hdfs.pyx -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/_json.pyx -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/_orc.pxd -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/_orc.pyx -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/_parquet.pxd -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/_parquet.pyx -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/_plasma.pyx -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/_s3fs.pyx -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/array.pxi -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/benchmark.pxi -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/builder.pxi -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/compat.pxi -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/config.pxi -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/error.pxi -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/feather.pxi -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/gandiva.pyx -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/io-hdfs.pxi -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/io.pxi -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/ipc.pxi -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/lib.pxd -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/lib.pyx -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/memory.pxi -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/pandas-shim.pxi -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/public-api.pxi -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/scalar.pxi -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/serialization.pxi -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/table.pxi -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/tensor.pxi -> build/lib.linux-aarch64-3.8/pyarrow
    copying pyarrow/types.pxi -> build/lib.linux-aarch64-3.8/pyarrow
    creating build/lib.linux-aarch64-3.8/pyarrow/includes
    copying pyarrow/includes/__init__.pxd -> build/lib.linux-aarch64-3.8/pyarrow/includes
    copying pyarrow/includes/common.pxd -> build/lib.linux-aarch64-3.8/pyarrow/includes
    copying pyarrow/includes/libarrow.pxd -> build/lib.linux-aarch64-3.8/pyarrow/includes
    copying pyarrow/includes/libarrow_cuda.pxd -> build/lib.linux-aarch64-3.8/pyarrow/includes
    copying pyarrow/includes/libarrow_dataset.pxd -> build/lib.linux-aarch64-3.8/pyarrow/includes
    copying pyarrow/includes/libarrow_flight.pxd -> build/lib.linux-aarch64-3.8/pyarrow/includes
    copying pyarrow/includes/libarrow_fs.pxd -> build/lib.linux-aarch64-3.8/pyarrow/includes
    copying pyarrow/includes/libgandiva.pxd -> build/lib.linux-aarch64-3.8/pyarrow/includes
    copying pyarrow/includes/libplasma.pxd -> build/lib.linux-aarch64-3.8/pyarrow/includes
    creating build/lib.linux-aarch64-3.8/pyarrow/tensorflow
    copying pyarrow/tensorflow/plasma_op.cc -> build/lib.linux-aarch64-3.8/pyarrow/tensorflow
    copying pyarrow/tests/pyarrow_cython_example.pyx -> build/lib.linux-aarch64-3.8/pyarrow/tests
    creating build/lib.linux-aarch64-3.8/pyarrow/tests/data
    creating build/lib.linux-aarch64-3.8/pyarrow/tests/data/feather
    copying pyarrow/tests/data/feather/v0.17.0.version=2-compression=lz4.feather -> build/lib.linux-aarch64-3.8/pyarrow/tests/data/feather
    creating build/lib.linux-aarch64-3.8/pyarrow/tests/data/orc
    copying pyarrow/tests/data/orc/README.md -> build/lib.linux-aarch64-3.8/pyarrow/tests/data/orc
    copying pyarrow/tests/data/orc/TestOrcFile.emptyFile.jsn.gz -> build/lib.linux-aarch64-3.8/pyarrow/tests/data/orc
    copying pyarrow/tests/data/orc/TestOrcFile.emptyFile.orc -> build/lib.linux-aarch64-3.8/pyarrow/tests/data/orc
    copying pyarrow/tests/data/orc/TestOrcFile.test1.jsn.gz -> build/lib.linux-aarch64-3.8/pyarrow/tests/data/orc
    copying pyarrow/tests/data/orc/TestOrcFile.test1.orc -> build/lib.linux-aarch64-3.8/pyarrow/tests/data/orc
    copying pyarrow/tests/data/orc/TestOrcFile.testDate1900.jsn.gz -> build/lib.linux-aarch64-3.8/pyarrow/tests/data/orc
    copying pyarrow/tests/data/orc/TestOrcFile.testDate1900.orc -> build/lib.linux-aarch64-3.8/pyarrow/tests/data/orc
    copying pyarrow/tests/data/orc/decimal.jsn.gz -> build/lib.linux-aarch64-3.8/pyarrow/tests/data/orc
    copying pyarrow/tests/data/orc/decimal.orc -> build/lib.linux-aarch64-3.8/pyarrow/tests/data/orc
    creating build/lib.linux-aarch64-3.8/pyarrow/tests/data/parquet
    copying pyarrow/tests/data/parquet/v0.7.1.all-named-index.parquet -> build/lib.linux-aarch64-3.8/pyarrow/tests/data/parquet
    copying pyarrow/tests/data/parquet/v0.7.1.column-metadata-handling.parquet -> build/lib.linux-aarch64-3.8/pyarrow/tests/data/parquet
    copying pyarrow/tests/data/parquet/v0.7.1.parquet -> build/lib.linux-aarch64-3.8/pyarrow/tests/data/parquet
    copying pyarrow/tests/data/parquet/v0.7.1.some-named-index.parquet -> build/lib.linux-aarch64-3.8/pyarrow/tests/data/parquet
    creating build/lib.linux-aarch64-3.8/pyarrow/tests/parquet
    copying pyarrow/tests/parquet/common.py -> build/lib.linux-aarch64-3.8/pyarrow/tests/parquet
    copying pyarrow/tests/parquet/conftest.py -> build/lib.linux-aarch64-3.8/pyarrow/tests/parquet
    copying pyarrow/tests/parquet/test_basic.py -> build/lib.linux-aarch64-3.8/pyarrow/tests/parquet
    copying pyarrow/tests/parquet/test_data_types.py -> build/lib.linux-aarch64-3.8/pyarrow/tests/parquet
    copying pyarrow/tests/parquet/test_dataset.py -> build/lib.linux-aarch64-3.8/pyarrow/tests/parquet
    copying pyarrow/tests/parquet/test_datetime.py -> build/lib.linux-aarch64-3.8/pyarrow/tests/parquet
    copying pyarrow/tests/parquet/test_metadata.py -> build/lib.linux-aarch64-3.8/pyarrow/tests/parquet
    copying pyarrow/tests/parquet/test_pandas.py -> build/lib.linux-aarch64-3.8/pyarrow/tests/parquet
    copying pyarrow/tests/parquet/test_parquet_file.py -> build/lib.linux-aarch64-3.8/pyarrow/tests/parquet
    copying pyarrow/tests/parquet/test_parquet_writer.py -> build/lib.linux-aarch64-3.8/pyarrow/tests/parquet
    running build_ext
    creating /tmp/pip-install-q0bfswpo/pyarrow/build/temp.linux-aarch64-3.8
    -- Running cmake for pyarrow
    cmake -DPYTHON_EXECUTABLE=/home/gokasci/venv/bin/python3 -DPython3_EXECUTABLE=/home/gokasci/venv/bin/python3  -DPYARROW_BUILD_CUDA=off -DPYARROW_BUILD_FLIGHT=off -DPYARROW_BUILD_GANDIVA=off -DPYARROW_BUILD_DATASET=off -DPYARROW_BUILD_ORC=off -DPYARROW_BUILD_PARQUET=off -DPYARROW_BUILD_PLASMA=off -DPYARROW_BUILD_S3=off -DPYARROW_BUILD_HDFS=off -DPYARROW_USE_TENSORFLOW=off -DPYARROW_BUNDLE_ARROW_CPP=off -DPYARROW_BUNDLE_BOOST=off -DPYARROW_GENERATE_COVERAGE=off -DPYARROW_BOOST_USE_SHARED=on -DPYARROW_PARQUET_USE_SHARED=on -DCMAKE_BUILD_TYPE=release /tmp/pip-install-q0bfswpo/pyarrow
    error: command 'cmake' failed with exit status 1
    ----------------------------------------
    ERROR: Failed building wheel for pyarrow
  Failed to build pyarrow
  ERROR: Could not build wheels for pyarrow which use PEP 517 and cannot be installed directly
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/gokasci/venv/bin/python3 /home/gokasci/venv/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-3urrbfxk/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel cython 'pyarrow>=3.0.0,<3.1.0' Check the logs for full command output.```

<!--
If you need urgent assistance reach out to support for escalated issue processing https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge
-->

**Comment by sfc-gh-hkapre** [comment]
@gasci Our drivers/connectors are not yet supported on ARM. We have this item in our backlog and are looking into what will be needed.

**Comment by gasci** [comment]
We faced the same problem on some Intel computers, too. After updating to `2.6.1` the `pyarrow` dependency build problem goes away but another problem arises: **Should we add another parameter regarding the SSH private key that didn't exist before version 2.6.0?**

```bash
/home/gokasci/schedulers/venv/lib/python3.8/site-packages/pandas/io/sql.py:1685: UserWarning: The provided table name 'DEALS' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "transformers/deals_import.py", line 277, in <module>
    deals.load_s3_data()
  File "transformers/deals_import.py", line 239, in export_data_to_snowflake
    sf.send_df_to_snowflake_bulk(
  File "/home/gokasci/schedulers/transformers/classes/snowflake.py", line 114, in send_df_to_snowflake_bulk
    conn.execute(f"put file://{file_path} @{table_name}_stage ;")
  File "/home/gokasci/schedulers/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in execute
    return self._exec_driver_sql(
  File "/home/gokasci/schedulers/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1546, in _exec_driver_sql
    ret = self._execute_context(
  File "/home/gokasci/schedulers/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/home/gokasci/schedulers/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1998, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/home/gokasci/schedulers/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/gokasci/schedulers/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/home/gokasci/schedulers/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/home/gokasci/schedulers/venv/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 742, in execute
    sf_file_transfer_agent.execute()
  File "/home/gokasci/schedulers/venv/lib/python3.8/site-packages/snowflake/connector/file_transfer_agent.py", line 379, in execute
    self._transfer_accelerate_config()
  File "/home/gokasci/schedulers/venv/lib/python3.8/site-packages/snowflake/connector/file_transfer_agent.py", line 671, in _transfer_accelerate_config
    self._use_accelerate_endpoint = client.transfer_accelerate_config()
  File "/home/gokasci/schedulers/venv/lib/python3.8/site-packages/snowflake/connector/s3_storage_client.py", line 548, in transfer_accelerate_config
    response = self._send_request_with_authentication_and_retry(
  File "/home/gokasci/schedulers/venv/lib/python3.8/site-packages/snowflake/connector/s3_storage_client.py", line 290, in _send_request_with_authentication_and_retry
    SnowflakeS3RestClient._hash_bytes_hex(payload).lower().decode()
  File "/home/gokasci/schedulers/venv/lib/python3.8/site-packages/snowflake/connector/s3_storage_client.py", line 126, in _hash_bytes_hex
    return binascii.hexlify(SnowflakeS3RestClient._hash_bytes(_input))
  File "/home/gokasci/schedulers/venv/lib/python3.8/site-packages/snowflake/connector/s3_storage_client.py", line 119, in _hash_bytes
    digest = hashes.Hash(hashes.SHA256())
TypeError: __init__() missing 1 required positional argument: 'backend'```

This is the relevant part in our Python script:
```python
        """
        Exports a pandas dataframe to a snowflake table.
        No staging layer required and more robust.
        Very slow if the data is huge
        """
        engine = create_engine(
            URL(
                account=account,
                user=user,
                password=password,
                database=database,
                schema=schema,
                warehouse=warehouse,
                role=role,
            )
        )

        connection = engine.connect()

        try:
            df.to_sql(
                table_name,
                engine,
                index=False,
                if_exists=if_exists,
                chunksize=5000,
                method="multi",
            )
        finally:
            connection.close()
            engine.dispose()
```

**Comment by sfc-gh-mkeller** [comment]
Let me break down your comment @gasci

> We faced the same problem on some Intel computers, too.

We need more information than this to help you with this info, at least the OS, OS version, `python --version --version` and `python -c "import platform; print(platform.platform())"`.

> Should we add another parameter regarding the SSH private key that didn't exist before version 2.6.0?

Please do describe this in more detail!

> Your posted script

`TypeError: __init__() missing 1 required positional argument: 'backend'` can be fixed by updating `cryptography`, please try that with `python -m pip install -U cryptography`.

**Comment by gasci** [comment]
Thank you. Updating cryptography has solved our problem!
