### ISSUE TITLE
SNOW-487478: Chunk upload fails for streams with size exceeding the multipart_threshold

### ISSUE THREAD

**Issue by olegkapustin** [snowflakedb/snowflake-connector-python#909]
## Steps to reproduce:
1. Prepare data file larger than 200MB (compressed)
2. Execute the code below (mind connection details and path to the data file):

```python
from datetime import datetime
import snowflake.connector
import logging

logging.basicConfig(
    filename="the.log",
    level=logging.DEBUG)

# timestamp to avoid file name conflicts
curr_ts = datetime.now().strftime("%Y%m%d%H%M%S")

ctx = snowflake.connector.connect(
    user='<user_name>',
    password='<password>',
    account='<account_name>'
)

cs = ctx.cursor()

try:
    with open("./data/203MB.json.gz", "rb") as f:
        cs.execute(
            f"PUT file://./this/path/is/ignored/{curr_ts}_data_203MB.json.gz @db.schema.stage/{curr_ts}/", 
            file_stream=f)
        one_row = cs.fetchone()
        print(one_row[0])

finally:
    cs.close()
    print("Cursor closed")

ctx.close()
print("Connection closed")

```

## Expected result:

The file is uploaded to the internal stage.

## Actual result:

Traceback:

```
Traceback (most recent call last):
  File "snowtest.py", line 24, in <module>
    f"PUT file://./this/path/is/ignored/{curr_ts}_data_203MB.json.gz @stgtest.foo.lake/{curr_ts}/", file_stream=f)        
  File "C:\zzz\venv\lib\site-packages\snowflake\connector\cursor.py", line 743, in execute
    data = sf_file_transfer_agent.result()
  File "C:\zzz\venv\lib\site-packages\snowflake\connector\file_transfer_agent.py", line 722, in result  
    "errno": ER_FAILED_TO_UPLOAD_TO_STAGE,
  File "C:\zzz\venv\lib\site-packages\snowflake\connector\errors.py", line 258, in errorhandler_wrapper 
    error_value,
  File "C:\zzz\venv\lib\site-packages\snowflake\connector\errors.py", line 309, in hand_to_other_handler    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\zzz\venv\lib\site-packages\snowflake\connector\errors.py", line 195, in default_errorhandler 
    cursor=cursor,
snowflake.connector.errors.OperationalError: ValueError('I/O operation on closed file.')
```

Log:

```
ERROR:snowflake.connector.file_transfer_agent:An exception was raised in <bound method SnowflakeStorageClient.upload_chunk of <snowflake.connector.s3_storage_client.SnowflakeS3RestClient object at 0x0000028D08D38588>>
Traceback (most recent call last):
  File "C:\zzz\venv\lib\site-packages\snowflake\connector\file_transfer_agent.py", line 574, in function_and_callback_wrapper
    work(*args, **kwargs),
  File "C:\zzz\venv\lib\site-packages\snowflake\connector\storage_client.py", line 392, in upload_chunk
    with fd:
ValueError: I/O operation on closed file.
```

## Related code:

https://github.com/snowflakedb/snowflake-connector-python/blob/a14ed5776f25fcca9fa13853bbdb171b4f146b76/src/snowflake/connector/storage_client.py#L392

## Root cause:

[`io.IOBase`](https://docs.python.org/3/library/io.html#io.IOBase) class implements the [context manager pattern](https://docs.python.org/3/reference/datamodel.html#context-managers) and closes a stream on exit. Therefore the stream gets closed as soon as the first suite within the `with` block is completed. Processing of subsequent chunks throws the exception provided above.

**Comment by olegkapustin** [comment]
@sfc-gh-mkeller, Thank you for the fix. Do you have any idea when it will be available via pip?

**Comment by sfc-gh-mkeller** [comment]
It should be released in a couple of weeks. That's when our next planned release is
