### ISSUE TITLE
SNOW-499499: Violating NOT NULL constraint should raise IntegrityError instead of ProgrammingError

### ISSUE THREAD

**Issue by timgraham** [snowflakedb/snowflake-connector-python#922]
Trying to save a NULL in a NOT NULL column raises `ProgrammingError`:
```python
>>> import snowflake.connector
>>> conn = snowflake.connector.connect(...)
>>> conn.cursor().execute('CREATE TABLE FOO(BAR char NOT NULL)')
>>> conn.cursor().execute('INSERT INTO FOO VALUES (NULL)')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tim/.virtualenvs/django39/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 777, in execute
    Error.errorhandler_wrapper(
  File "/home/tim/.virtualenvs/django39/lib/python3.9/site-packages/snowflake/connector/errors.py", line 255, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/tim/.virtualenvs/django39/lib/python3.9/site-packages/snowflake/connector/errors.py", line 310, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/tim/.virtualenvs/django39/lib/python3.9/site-packages/snowflake/connector/errors.py", line 189, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: NULL result in a non-nullable column
```
It would be consistent with other database drivers to instead raise `IntegrityError`. Some tests in Django's test suite fail because of this difference.

**Comment by sfc-gh-mkeller** [comment]
recreate jira
